/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {24, 1, 1};
static const casadi_int casadi_s1[3] = {9, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {33, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_c0[9] = 
  {250., 0., 0., 0., 250., 0., 0., 0.,
  250.};
static const casadi_real casadi_c1[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c2[9] = 
  {30., 0., 0., 0., 30., 0., 0., 0.,
  30.};
static const casadi_real casadi_c3[9] = 
  {1.0000000000000001e-01, 0., 0., 0., 1.0000000000000001e-01, 0., 0., 0.,
  1.0000000000000001e-01};

static const casadi_real casadi_zeros[33] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* planner_payload_pointmass_multiple_cost_ext_cost_fun_jac:(i0[24],i1[9],i2[0],i3[33])->(o0,o1[33]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+4, *w02=w+7, *w04=w+43, *w06=w+55, w07, w08, *w09=w+60, *w10=w+63, *w11=w+72, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w19, *w20=w+83, *w21=w+86, *w22=w+89, *w23=w+98, w24;
  casadi_real w25, w26, *w27=w+104, *w28=w+107, *w29=w+110, w30, w31, w32, *w33=w+116, *w34=w+119, *w35=w+122, *w36=w+125;
  casadi_real *w37=w+128, *w38=w+137, *w39=w+140, *w41=w+152, *w42=w+155, *w43=w+158, *w45=w+164, *w46=w+167, *w47=w+170, *w49=w+176, *w50=w+179, *w51=w+182;
  casadi_real *w52=w+185, *w53=w+188, *w54=w+191, *w55=w+194, *w56=w+197, *w57=w+200;
  const casadi_real *cr, *cs, *ct, *wr03, *wr04, *wr05, *wr09, *wr10, *wr22, *wr39, *wr40, *wr44;
  const casadi_real *wr48;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[:3] */
  wr04 = wr03+0;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = @2' */
  casadi_copy(w02, 3, w04);
  /* #7: @5 = 
  [[250, 0, 0], 
   [0, 250, 0], 
   [0, 0, 250]] */
  wr05 = casadi_c0;
  /* #8: @6 = mac(@4,@5,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w04+j, ct=wr05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #9: @7 = mac(@6,@2,@0) */
  casadi_copy((&w00), 1, (&w07));
  for (i=0, rr=(&w07); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #10: @8 = 0.2 */
  w08 = 2.0000000000000001e-01;
  /* #11: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w02);
  /* #12: @9 = @3[3:6] */
  wr09 = wr03+3;
  /* #13: @2 = (@2-@9) */
  for (i=0, rr=w02, cs=wr09; i<3; ++i) (*rr++) -= (*cs++);
  /* #14: @9 = @2' */
  casadi_copy(w02, 3, w09);
  /* #15: @10 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr10 = casadi_c1;
  /* #16: @11 = mac(@9,@10,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #17: @12 = mac(@11,@2,@0) */
  casadi_copy((&w00), 1, (&w12));
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #18: @12 = (@8*@12) */
  w12  = (w08*w12);
  /* #19: @7 = (@7+@12) */
  w07 += w12;
  /* #20: @12 = @3[7] */
  w12 = wr03[7];
  /* #21: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w02);
  /* #22: @13 = @2[2] */
  for (rr=(&w13), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #23: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #24: @15 = @3[8] */
  w15 = wr03[8];
  /* #25: @16 = @2[1] */
  for (rr=(&w16), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #26: @17 = (@15*@16) */
  w17  = (w15*w16);
  /* #27: @14 = (@14-@17) */
  w14 -= w17;
  /* #28: @17 = @2[0] */
  for (rr=(&w17), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #29: @18 = (@15*@17) */
  w18  = (w15*w17);
  /* #30: @19 = @3[6] */
  w19 = wr03[6];
  /* #31: @13 = (@19*@13) */
  w13  = (w19*w13);
  /* #32: @18 = (@18-@13) */
  w18 -= w13;
  /* #33: @16 = (@19*@16) */
  w16  = (w19*w16);
  /* #34: @17 = (@12*@17) */
  w17  = (w12*w17);
  /* #35: @16 = (@16-@17) */
  w16 -= w17;
  /* #36: @20 = vertcat(@14, @18, @16) */
  rr=w20;
  *rr++ = w14;
  *rr++ = w18;
  *rr++ = w16;
  /* #37: @21 = @20' */
  casadi_copy(w20, 3, w21);
  /* #38: @22 = 
  [[30, 0, 0], 
   [0, 30, 0], 
   [0, 0, 30]] */
  wr22 = casadi_c2;
  /* #39: @23 = mac(@21,@22,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=wr22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @14 = mac(@23,@20,@0) */
  casadi_copy((&w00), 1, (&w14));
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @7 = (@7+@14) */
  w07 += w14;
  /* #42: @14 = @3[10] */
  w14 = wr03[10];
  /* #43: @20 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+9 : 0, 3, w20);
  /* #44: @18 = @20[2] */
  for (rr=(&w18), cs=w20+2; cs!=w20+3; cs+=1) *rr++ = *cs;
  /* #45: @16 = (@14*@18) */
  w16  = (w14*w18);
  /* #46: @17 = @3[11] */
  w17 = wr03[11];
  /* #47: @13 = @20[1] */
  for (rr=(&w13), cs=w20+1; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #48: @24 = (@17*@13) */
  w24  = (w17*w13);
  /* #49: @16 = (@16-@24) */
  w16 -= w24;
  /* #50: @24 = @20[0] */
  for (rr=(&w24), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #51: @25 = (@17*@24) */
  w25  = (w17*w24);
  /* #52: @26 = @3[9] */
  w26 = wr03[9];
  /* #53: @18 = (@26*@18) */
  w18  = (w26*w18);
  /* #54: @25 = (@25-@18) */
  w25 -= w18;
  /* #55: @13 = (@26*@13) */
  w13  = (w26*w13);
  /* #56: @24 = (@14*@24) */
  w24  = (w14*w24);
  /* #57: @13 = (@13-@24) */
  w13 -= w24;
  /* #58: @27 = vertcat(@16, @25, @13) */
  rr=w27;
  *rr++ = w16;
  *rr++ = w25;
  *rr++ = w13;
  /* #59: @28 = @27' */
  casadi_copy(w27, 3, w28);
  /* #60: @29 = mac(@28,@22,@1) */
  casadi_copy(w01, 3, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=wr22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #61: @16 = mac(@29,@27,@0) */
  casadi_copy((&w00), 1, (&w16));
  for (i=0, rr=(&w16); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #62: @7 = (@7+@16) */
  w07 += w16;
  /* #63: @16 = @3[13] */
  w16 = wr03[13];
  /* #64: @27 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+12 : 0, 3, w27);
  /* #65: @25 = @27[2] */
  for (rr=(&w25), cs=w27+2; cs!=w27+3; cs+=1) *rr++ = *cs;
  /* #66: @13 = (@16*@25) */
  w13  = (w16*w25);
  /* #67: @24 = @3[14] */
  w24 = wr03[14];
  /* #68: @18 = @27[1] */
  for (rr=(&w18), cs=w27+1; cs!=w27+2; cs+=1) *rr++ = *cs;
  /* #69: @30 = (@24*@18) */
  w30  = (w24*w18);
  /* #70: @13 = (@13-@30) */
  w13 -= w30;
  /* #71: @30 = @27[0] */
  for (rr=(&w30), cs=w27+0; cs!=w27+1; cs+=1) *rr++ = *cs;
  /* #72: @31 = (@24*@30) */
  w31  = (w24*w30);
  /* #73: @32 = @3[12] */
  w32 = wr03[12];
  /* #74: @25 = (@32*@25) */
  w25  = (w32*w25);
  /* #75: @31 = (@31-@25) */
  w31 -= w25;
  /* #76: @18 = (@32*@18) */
  w18  = (w32*w18);
  /* #77: @30 = (@16*@30) */
  w30  = (w16*w30);
  /* #78: @18 = (@18-@30) */
  w18 -= w30;
  /* #79: @33 = vertcat(@13, @31, @18) */
  rr=w33;
  *rr++ = w13;
  *rr++ = w31;
  *rr++ = w18;
  /* #80: @34 = @33' */
  casadi_copy(w33, 3, w34);
  /* #81: @35 = mac(@34,@22,@1) */
  casadi_copy(w01, 3, w35);
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=wr22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #82: @13 = mac(@35,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #83: @7 = (@7+@13) */
  w07 += w13;
  /* #84: @33 = input[0][5] */
  casadi_copy(arg[0] ? arg[0]+15 : 0, 3, w33);
  /* #85: @36 = zeros(3x1) */
  casadi_clear(w36, 3);
  /* #86: @37 = zeros(3x3) */
  casadi_clear(w37, 9);
  /* #87: @38 = @2' */
  casadi_copy(w02, 3, w38);
  /* #88: @39 = mac(@2,@38,@37) */
  casadi_copy(w37, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w02+j, ct=w38+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #89: @39 = (@10-@39) */
  for (i=0, rr=w39, cr=wr10, cs=w39; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #90: @40 = @3[15:18] */
  wr40 = wr03+15;
  /* #91: @41 = mac(@39,@40,@36) */
  casadi_copy(w36, 3, w41);
  for (i=0, rr=w41; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=wr40+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #92: @33 = (@33-@41) */
  for (i=0, rr=w33, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #93: @41 = @33' */
  casadi_copy(w33, 3, w41);
  /* #94: @42 = mac(@41,@10,@1) */
  casadi_copy(w01, 3, w42);
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #95: @13 = mac(@42,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w42+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #96: @7 = (@7+@13) */
  w07 += w13;
  /* #97: @33 = input[0][6] */
  casadi_copy(arg[0] ? arg[0]+18 : 0, 3, w33);
  /* #98: @43 = @20' */
  casadi_copy(w20, 3, w43);
  /* #99: @39 = mac(@20,@43,@37) */
  casadi_copy(w37, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w20+j, ct=w43+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #100: @39 = (@10-@39) */
  for (i=0, rr=w39, cr=wr10, cs=w39; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #101: @44 = @3[18:21] */
  wr44 = wr03+18;
  /* #102: @45 = mac(@39,@44,@36) */
  casadi_copy(w36, 3, w45);
  for (i=0, rr=w45; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=wr44+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #103: @33 = (@33-@45) */
  for (i=0, rr=w33, cs=w45; i<3; ++i) (*rr++) -= (*cs++);
  /* #104: @45 = @33' */
  casadi_copy(w33, 3, w45);
  /* #105: @46 = mac(@45,@10,@1) */
  casadi_copy(w01, 3, w46);
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w45+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #106: @13 = mac(@46,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w46+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #107: @7 = (@7+@13) */
  w07 += w13;
  /* #108: @33 = input[0][7] */
  casadi_copy(arg[0] ? arg[0]+21 : 0, 3, w33);
  /* #109: @47 = @27' */
  casadi_copy(w27, 3, w47);
  /* #110: @39 = mac(@27,@47,@37) */
  casadi_copy(w37, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w47+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #111: @39 = (@10-@39) */
  for (i=0, rr=w39, cr=wr10, cs=w39; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #112: @48 = @3[21:24] */
  wr48 = wr03+21;
  /* #113: @49 = mac(@39,@48,@36) */
  casadi_copy(w36, 3, w49);
  for (i=0, rr=w49; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=wr48+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #114: @33 = (@33-@49) */
  for (i=0, rr=w33, cs=w49; i<3; ++i) (*rr++) -= (*cs++);
  /* #115: @49 = @33' */
  casadi_copy(w33, 3, w49);
  /* #116: @50 = mac(@49,@10,@1) */
  casadi_copy(w01, 3, w50);
  for (i=0, rr=w50; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w49+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #117: @13 = mac(@50,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w50+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #118: @7 = (@7+@13) */
  w07 += w13;
  /* #119: @33 = input[1][0] */
  casadi_copy(arg[1], 3, w33);
  /* #120: @51 = @33' */
  casadi_copy(w33, 3, w51);
  /* #121: @39 = 
  [[0.1, 0, 0], 
   [0, 0.1, 0], 
   [0, 0, 0.1]] */
  wr39 = casadi_c3;
  /* #122: @52 = mac(@51,@39,@1) */
  casadi_copy(w01, 3, w52);
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w51+j, ct=wr39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #123: @13 = mac(@52,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w52+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #124: @7 = (@7+@13) */
  w07 += w13;
  /* #125: @33 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+3 : 0, 3, w33);
  /* #126: @53 = @33' */
  casadi_copy(w33, 3, w53);
  /* #127: @54 = mac(@53,@39,@1) */
  casadi_copy(w01, 3, w54);
  for (i=0, rr=w54; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w53+j, ct=wr39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #128: @13 = mac(@54,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w54+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #129: @7 = (@7+@13) */
  w07 += w13;
  /* #130: @33 = input[1][2] */
  casadi_copy(arg[1] ? arg[1]+6 : 0, 3, w33);
  /* #131: @55 = @33' */
  casadi_copy(w33, 3, w55);
  /* #132: @56 = mac(@55,@39,@1) */
  casadi_copy(w01, 3, w56);
  for (i=0, rr=w56; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w55+j, ct=wr39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #133: @0 = mac(@56,@33,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w56+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #134: @7 = (@7+@0) */
  w07 += w00;
  /* #135: output[0][0] = @7 */
  if (res[0]) res[0][0] = w07;
  /* #136: @52 = @52' */
  /* #137: @57 = @39' */
  for (i=0, rr=w57, cs=wr39; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #138: @33 = mac(@51,@57,@1) */
  casadi_copy(w01, 3, w33);
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w51+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #139: @33 = @33' */
  /* #140: @52 = (@52+@33) */
  for (i=0, rr=w52, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #141: output[1][0] = @52 */
  casadi_copy(w52, 3, res[1]);
  /* #142: @54 = @54' */
  /* #143: @52 = mac(@53,@57,@1) */
  casadi_copy(w01, 3, w52);
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w53+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #144: @52 = @52' */
  /* #145: @54 = (@54+@52) */
  for (i=0, rr=w54, cs=w52; i<3; ++i) (*rr++) += (*cs++);
  /* #146: output[1][1] = @54 */
  if (res[1]) casadi_copy(w54, 3, res[1]+3);
  /* #147: @56 = @56' */
  /* #148: @54 = mac(@55,@57,@1) */
  casadi_copy(w01, 3, w54);
  for (i=0, rr=w54; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w55+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #149: @54 = @54' */
  /* #150: @56 = (@56+@54) */
  for (i=0, rr=w56, cs=w54; i<3; ++i) (*rr++) += (*cs++);
  /* #151: output[1][2] = @56 */
  if (res[1]) casadi_copy(w56, 3, res[1]+6);
  /* #152: @6 = @6' */
  /* #153: @57 = @5' */
  for (i=0, rr=w57, cs=wr05; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #154: @56 = mac(@4,@57,@1) */
  casadi_copy(w01, 3, w56);
  for (i=0, rr=w56; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w04+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #155: @56 = @56' */
  /* #156: @6 = (@6+@56) */
  for (i=0, rr=w06, cs=w56; i<3; ++i) (*rr++) += (*cs++);
  /* #157: output[1][3] = @6 */
  if (res[1]) casadi_copy(w06, 3, res[1]+9);
  /* #158: @11 = @11' */
  /* #159: @11 = (@8*@11) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #160: @9 = (@8*@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #161: @57 = @10' */
  for (i=0, rr=w57, cs=wr10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #162: @6 = mac(@9,@57,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #163: @6 = @6' */
  /* #164: @11 = (@11+@6) */
  for (i=0, rr=w11, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #165: output[1][4] = @11 */
  if (res[1]) casadi_copy(w11, 3, res[1]+12);
  /* #166: @42 = @42' */
  /* #167: @11 = mac(@41,@57,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #168: @11 = @11' */
  /* #169: @42 = (@42+@11) */
  for (i=0, rr=w42, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #170: @11 = (-@42) */
  for (i=0, rr=w11, cs=w42; i<3; ++i) *rr++ = (- *cs++ );
  /* #171: @40 = @40' */
  /* #172: @10 = mac(@11,@40,@37) */
  casadi_copy(w37, 9, w10);
  for (i=0, rr=w10; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr40+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #173: @10 = (-@10) */
  for (i=0, rr=w10, cs=w10; i<9; ++i) *rr++ = (- *cs++ );
  /* #174: @11 = mac(@10,@2,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w10+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #175: @2 = mac(@38,@10,@1) */
  casadi_copy(w01, 3, w02);
  for (i=0, rr=w02; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #176: @2 = @2' */
  /* #177: @11 = (@11+@2) */
  for (i=0, rr=w11, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #178: @23 = @23' */
  /* #179: @10 = @22' */
  for (i=0, rr=w10, cs=wr22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #180: @2 = mac(@21,@10,@1) */
  casadi_copy(w01, 3, w02);
  for (i=0, rr=w02; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #181: @2 = @2' */
  /* #182: @23 = (@23+@2) */
  for (i=0, rr=w23, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #183: {@8, @7, @0} = vertsplit(@23) */
  w08 = w23[0];
  w07 = w23[1];
  w00 = w23[2];
  /* #184: @13 = (@15*@7) */
  w13  = (w15*w07);
  /* #185: @31 = (@12*@0) */
  w31  = (w12*w00);
  /* #186: @13 = (@13-@31) */
  w13 -= w31;
  /* #187: (@11[0] += @13) */
  for (rr=w11+0, cs=(&w13); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #188: @0 = (@19*@0) */
  w00  = (w19*w00);
  /* #189: @15 = (@15*@8) */
  w15 *= w08;
  /* #190: @0 = (@0-@15) */
  w00 -= w15;
  /* #191: (@11[1] += @0) */
  for (rr=w11+1, cs=(&w00); rr!=w11+2; rr+=1) *rr += *cs++;
  /* #192: @12 = (@12*@8) */
  w12 *= w08;
  /* #193: @19 = (@19*@7) */
  w19 *= w07;
  /* #194: @12 = (@12-@19) */
  w12 -= w19;
  /* #195: (@11[2] += @12) */
  for (rr=w11+2, cs=(&w12); rr!=w11+3; rr+=1) *rr += *cs++;
  /* #196: output[1][5] = @11 */
  if (res[1]) casadi_copy(w11, 3, res[1]+15);
  /* #197: @46 = @46' */
  /* #198: @11 = mac(@45,@57,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w45+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #199: @11 = @11' */
  /* #200: @46 = (@46+@11) */
  for (i=0, rr=w46, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #201: @11 = (-@46) */
  for (i=0, rr=w11, cs=w46; i<3; ++i) *rr++ = (- *cs++ );
  /* #202: @44 = @44' */
  /* #203: @22 = mac(@11,@44,@37) */
  casadi_copy(w37, 9, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr44+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #204: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<9; ++i) *rr++ = (- *cs++ );
  /* #205: @11 = mac(@22,@20,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #206: @20 = mac(@43,@22,@1) */
  casadi_copy(w01, 3, w20);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #207: @20 = @20' */
  /* #208: @11 = (@11+@20) */
  for (i=0, rr=w11, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #209: @29 = @29' */
  /* #210: @20 = mac(@28,@10,@1) */
  casadi_copy(w01, 3, w20);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #211: @20 = @20' */
  /* #212: @29 = (@29+@20) */
  for (i=0, rr=w29, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #213: {@12, @19, @7} = vertsplit(@29) */
  w12 = w29[0];
  w19 = w29[1];
  w07 = w29[2];
  /* #214: @8 = (@17*@19) */
  w08  = (w17*w19);
  /* #215: @0 = (@14*@7) */
  w00  = (w14*w07);
  /* #216: @8 = (@8-@0) */
  w08 -= w00;
  /* #217: (@11[0] += @8) */
  for (rr=w11+0, cs=(&w08); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #218: @7 = (@26*@7) */
  w07  = (w26*w07);
  /* #219: @17 = (@17*@12) */
  w17 *= w12;
  /* #220: @7 = (@7-@17) */
  w07 -= w17;
  /* #221: (@11[1] += @7) */
  for (rr=w11+1, cs=(&w07); rr!=w11+2; rr+=1) *rr += *cs++;
  /* #222: @14 = (@14*@12) */
  w14 *= w12;
  /* #223: @26 = (@26*@19) */
  w26 *= w19;
  /* #224: @14 = (@14-@26) */
  w14 -= w26;
  /* #225: (@11[2] += @14) */
  for (rr=w11+2, cs=(&w14); rr!=w11+3; rr+=1) *rr += *cs++;
  /* #226: output[1][6] = @11 */
  if (res[1]) casadi_copy(w11, 3, res[1]+18);
  /* #227: @50 = @50' */
  /* #228: @11 = mac(@49,@57,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w49+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #229: @11 = @11' */
  /* #230: @50 = (@50+@11) */
  for (i=0, rr=w50, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #231: @11 = (-@50) */
  for (i=0, rr=w11, cs=w50; i<3; ++i) *rr++ = (- *cs++ );
  /* #232: @48 = @48' */
  /* #233: @37 = mac(@11,@48,@37) */
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr48+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #234: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<9; ++i) *rr++ = (- *cs++ );
  /* #235: @36 = mac(@37,@27,@36) */
  for (i=0, rr=w36; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w37+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #236: @27 = mac(@47,@37,@1) */
  casadi_copy(w01, 3, w27);
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w37+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #237: @27 = @27' */
  /* #238: @36 = (@36+@27) */
  for (i=0, rr=w36, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #239: @35 = @35' */
  /* #240: @1 = mac(@34,@10,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #241: @1 = @1' */
  /* #242: @35 = (@35+@1) */
  for (i=0, rr=w35, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #243: {@14, @26, @19} = vertsplit(@35) */
  w14 = w35[0];
  w26 = w35[1];
  w19 = w35[2];
  /* #244: @12 = (@24*@26) */
  w12  = (w24*w26);
  /* #245: @7 = (@16*@19) */
  w07  = (w16*w19);
  /* #246: @12 = (@12-@7) */
  w12 -= w07;
  /* #247: (@36[0] += @12) */
  for (rr=w36+0, cs=(&w12); rr!=w36+1; rr+=1) *rr += *cs++;
  /* #248: @19 = (@32*@19) */
  w19  = (w32*w19);
  /* #249: @24 = (@24*@14) */
  w24 *= w14;
  /* #250: @19 = (@19-@24) */
  w19 -= w24;
  /* #251: (@36[1] += @19) */
  for (rr=w36+1, cs=(&w19); rr!=w36+2; rr+=1) *rr += *cs++;
  /* #252: @16 = (@16*@14) */
  w16 *= w14;
  /* #253: @32 = (@32*@26) */
  w32 *= w26;
  /* #254: @16 = (@16-@32) */
  w16 -= w32;
  /* #255: (@36[2] += @16) */
  for (rr=w36+2, cs=(&w16); rr!=w36+3; rr+=1) *rr += *cs++;
  /* #256: output[1][7] = @36 */
  if (res[1]) casadi_copy(w36, 3, res[1]+21);
  /* #257: output[1][8] = @42 */
  if (res[1]) casadi_copy(w42, 3, res[1]+24);
  /* #258: output[1][9] = @46 */
  if (res[1]) casadi_copy(w46, 3, res[1]+27);
  /* #259: output[1][10] = @50 */
  if (res[1]) casadi_copy(w50, 3, res[1]+30);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 209;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 209*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
