/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_pointmass_multiple_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {24, 1, 1};
static const casadi_int casadi_s1[3] = {9, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {33, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_c0[9] = 
  {250., 0., 0., 0., 250., 0., 0., 0.,
  250.};
static const casadi_real casadi_c1[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c2[9] = 
  {30., 0., 0., 0., 30., 0., 0., 0.,
  30.};
static const casadi_real casadi_c3[9] = 
  {1.0000000000000001e-01, 0., 0., 0., 1.0000000000000001e-01, 0., 0., 0.,
  1.0000000000000001e-01};

static const casadi_real casadi_zeros[33] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* planner_payload_pointmass_multiple_cost_ext_cost_fun:(i0[24],i1[9],i2[0],i3[33])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+4, *w02=w+7, *w04=w+43, *w06=w+55, w07, w08, w09, w10, w11, w12;
  casadi_real w13, w14, *w15=w+66, *w16=w+75, *w17=w+78, *w18=w+81, *w19=w+84;
  const casadi_real *cr, *cs, *ct, *wr02, *wr03, *wr04, *wr05, *wr15, *wr16, *wr17;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[:3] */
  wr04 = wr03+0;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = @2' */
  casadi_copy(w02, 3, w04);
  /* #7: @5 = 
  [[250, 0, 0], 
   [0, 250, 0], 
   [0, 0, 250]] */
  wr05 = casadi_c0;
  /* #8: @6 = mac(@4,@5,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w04+j, ct=wr05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #9: @7 = mac(@6,@2,@0) */
  casadi_copy((&w00), 1, (&w07));
  for (i=0, rr=(&w07); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #10: @8 = 0.2 */
  w08 = 2.0000000000000001e-01;
  /* #11: @6 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w06);
  /* #12: @2 = @3[3:6] */
  wr02 = wr03+3;
  /* #13: @6 = (@6-@2) */
  for (i=0, rr=w06, cs=wr02; i<3; ++i) (*rr++) -= (*cs++);
  /* #14: @2 = @6' */
  casadi_copy(w06, 3, w02);
  /* #15: @5 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr05 = casadi_c1;
  /* #16: @4 = mac(@2,@5,@1) */
  casadi_copy(w01, 3, w04);
  for (i=0, rr=w04; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w02+j, ct=wr05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #17: @9 = mac(@4,@6,@0) */
  casadi_copy((&w00), 1, (&w09));
  for (i=0, rr=(&w09); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w04+j, ct=w06+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #18: @8 = (@8*@9) */
  w08 *= w09;
  /* #19: @7 = (@7+@8) */
  w07 += w08;
  /* #20: @8 = @3[7] */
  w08 = wr03[7];
  /* #21: @4 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w04);
  /* #22: @9 = @4[2] */
  for (rr=(&w09), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #23: @10 = (@8*@9) */
  w10  = (w08*w09);
  /* #24: @11 = @3[8] */
  w11 = wr03[8];
  /* #25: @12 = @4[1] */
  for (rr=(&w12), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #26: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #27: @10 = (@10-@13) */
  w10 -= w13;
  /* #28: @13 = @4[0] */
  for (rr=(&w13), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #29: @11 = (@11*@13) */
  w11 *= w13;
  /* #30: @14 = @3[6] */
  w14 = wr03[6];
  /* #31: @9 = (@14*@9) */
  w09  = (w14*w09);
  /* #32: @11 = (@11-@9) */
  w11 -= w09;
  /* #33: @14 = (@14*@12) */
  w14 *= w12;
  /* #34: @8 = (@8*@13) */
  w08 *= w13;
  /* #35: @14 = (@14-@8) */
  w14 -= w08;
  /* #36: @6 = vertcat(@10, @11, @14) */
  rr=w06;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w14;
  /* #37: @2 = @6' */
  casadi_copy(w06, 3, w02);
  /* #38: @15 = 
  [[30, 0, 0], 
   [0, 30, 0], 
   [0, 0, 30]] */
  wr15 = casadi_c2;
  /* #39: @16 = mac(@2,@15,@1) */
  casadi_copy(w01, 3, w16);
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w02+j, ct=wr15+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @10 = mac(@16,@6,@0) */
  casadi_copy((&w00), 1, (&w10));
  for (i=0, rr=(&w10); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w16+j, ct=w06+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @7 = (@7+@10) */
  w07 += w10;
  /* #42: @10 = @3[10] */
  w10 = wr03[10];
  /* #43: @16 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+9 : 0, 3, w16);
  /* #44: @11 = @16[2] */
  for (rr=(&w11), cs=w16+2; cs!=w16+3; cs+=1) *rr++ = *cs;
  /* #45: @14 = (@10*@11) */
  w14  = (w10*w11);
  /* #46: @8 = @3[11] */
  w08 = wr03[11];
  /* #47: @13 = @16[1] */
  for (rr=(&w13), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #48: @12 = (@8*@13) */
  w12  = (w08*w13);
  /* #49: @14 = (@14-@12) */
  w14 -= w12;
  /* #50: @12 = @16[0] */
  for (rr=(&w12), cs=w16+0; cs!=w16+1; cs+=1) *rr++ = *cs;
  /* #51: @8 = (@8*@12) */
  w08 *= w12;
  /* #52: @9 = @3[9] */
  w09 = wr03[9];
  /* #53: @11 = (@9*@11) */
  w11  = (w09*w11);
  /* #54: @8 = (@8-@11) */
  w08 -= w11;
  /* #55: @9 = (@9*@13) */
  w09 *= w13;
  /* #56: @10 = (@10*@12) */
  w10 *= w12;
  /* #57: @9 = (@9-@10) */
  w09 -= w10;
  /* #58: @6 = vertcat(@14, @8, @9) */
  rr=w06;
  *rr++ = w14;
  *rr++ = w08;
  *rr++ = w09;
  /* #59: @2 = @6' */
  casadi_copy(w06, 3, w02);
  /* #60: @17 = mac(@2,@15,@1) */
  casadi_copy(w01, 3, w17);
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w02+j, ct=wr15+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #61: @14 = mac(@17,@6,@0) */
  casadi_copy((&w00), 1, (&w14));
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w17+j, ct=w06+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #62: @7 = (@7+@14) */
  w07 += w14;
  /* #63: @14 = @3[13] */
  w14 = wr03[13];
  /* #64: @17 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+12 : 0, 3, w17);
  /* #65: @8 = @17[2] */
  for (rr=(&w08), cs=w17+2; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #66: @9 = (@14*@8) */
  w09  = (w14*w08);
  /* #67: @10 = @3[14] */
  w10 = wr03[14];
  /* #68: @12 = @17[1] */
  for (rr=(&w12), cs=w17+1; cs!=w17+2; cs+=1) *rr++ = *cs;
  /* #69: @13 = (@10*@12) */
  w13  = (w10*w12);
  /* #70: @9 = (@9-@13) */
  w09 -= w13;
  /* #71: @13 = @17[0] */
  for (rr=(&w13), cs=w17+0; cs!=w17+1; cs+=1) *rr++ = *cs;
  /* #72: @10 = (@10*@13) */
  w10 *= w13;
  /* #73: @11 = @3[12] */
  w11 = wr03[12];
  /* #74: @8 = (@11*@8) */
  w08  = (w11*w08);
  /* #75: @10 = (@10-@8) */
  w10 -= w08;
  /* #76: @11 = (@11*@12) */
  w11 *= w12;
  /* #77: @14 = (@14*@13) */
  w14 *= w13;
  /* #78: @11 = (@11-@14) */
  w11 -= w14;
  /* #79: @6 = vertcat(@9, @10, @11) */
  rr=w06;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #80: @2 = @6' */
  casadi_copy(w06, 3, w02);
  /* #81: @18 = mac(@2,@15,@1) */
  casadi_copy(w01, 3, w18);
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w02+j, ct=wr15+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #82: @9 = mac(@18,@6,@0) */
  casadi_copy((&w00), 1, (&w09));
  for (i=0, rr=(&w09); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w18+j, ct=w06+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #83: @7 = (@7+@9) */
  w07 += w09;
  /* #84: @18 = input[0][5] */
  casadi_copy(arg[0] ? arg[0]+15 : 0, 3, w18);
  /* #85: @6 = zeros(3x1) */
  casadi_clear(w06, 3);
  /* #86: @15 = zeros(3x3) */
  casadi_clear(w15, 9);
  /* #87: @2 = @4' */
  casadi_copy(w04, 3, w02);
  /* #88: @19 = mac(@4,@2,@15) */
  casadi_copy(w15, 9, w19);
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w04+j, ct=w02+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #89: @19 = (@5-@19) */
  for (i=0, rr=w19, cr=wr05, cs=w19; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #90: @4 = @3[15:18] */
  wr04 = wr03+15;
  /* #91: @2 = mac(@19,@4,@6) */
  casadi_copy(w06, 3, w02);
  for (i=0, rr=w02; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w19+j, ct=wr04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #92: @18 = (@18-@2) */
  for (i=0, rr=w18, cs=w02; i<3; ++i) (*rr++) -= (*cs++);
  /* #93: @2 = @18' */
  casadi_copy(w18, 3, w02);
  /* #94: @4 = mac(@2,@5,@1) */
  casadi_copy(w01, 3, w04);
  for (i=0, rr=w04; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w02+j, ct=wr05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #95: @9 = mac(@4,@18,@0) */
  casadi_copy((&w00), 1, (&w09));
  for (i=0, rr=(&w09); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w04+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #96: @7 = (@7+@9) */
  w07 += w09;
  /* #97: @4 = input[0][6] */
  casadi_copy(arg[0] ? arg[0]+18 : 0, 3, w04);
  /* #98: @18 = @16' */
  casadi_copy(w16, 3, w18);
  /* #99: @19 = mac(@16,@18,@15) */
  casadi_copy(w15, 9, w19);
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w16+j, ct=w18+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #100: @19 = (@5-@19) */
  for (i=0, rr=w19, cr=wr05, cs=w19; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #101: @16 = @3[18:21] */
  wr16 = wr03+18;
  /* #102: @18 = mac(@19,@16,@6) */
  casadi_copy(w06, 3, w18);
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w19+j, ct=wr16+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #103: @4 = (@4-@18) */
  for (i=0, rr=w04, cs=w18; i<3; ++i) (*rr++) -= (*cs++);
  /* #104: @18 = @4' */
  casadi_copy(w04, 3, w18);
  /* #105: @16 = mac(@18,@5,@1) */
  casadi_copy(w01, 3, w16);
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w18+j, ct=wr05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #106: @9 = mac(@16,@4,@0) */
  casadi_copy((&w00), 1, (&w09));
  for (i=0, rr=(&w09); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w16+j, ct=w04+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #107: @7 = (@7+@9) */
  w07 += w09;
  /* #108: @16 = input[0][7] */
  casadi_copy(arg[0] ? arg[0]+21 : 0, 3, w16);
  /* #109: @4 = @17' */
  casadi_copy(w17, 3, w04);
  /* #110: @15 = mac(@17,@4,@15) */
  for (i=0, rr=w15; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w17+j, ct=w04+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #111: @15 = (@5-@15) */
  for (i=0, rr=w15, cr=wr05, cs=w15; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #112: @17 = @3[21:24] */
  wr17 = wr03+21;
  /* #113: @6 = mac(@15,@17,@6) */
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w15+j, ct=wr17+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #114: @16 = (@16-@6) */
  for (i=0, rr=w16, cs=w06; i<3; ++i) (*rr++) -= (*cs++);
  /* #115: @6 = @16' */
  casadi_copy(w16, 3, w06);
  /* #116: @17 = mac(@6,@5,@1) */
  casadi_copy(w01, 3, w17);
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=wr05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #117: @9 = mac(@17,@16,@0) */
  casadi_copy((&w00), 1, (&w09));
  for (i=0, rr=(&w09); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w17+j, ct=w16+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #118: @7 = (@7+@9) */
  w07 += w09;
  /* #119: @17 = input[1][0] */
  casadi_copy(arg[1], 3, w17);
  /* #120: @16 = @17' */
  casadi_copy(w17, 3, w16);
  /* #121: @5 = 
  [[0.1, 0, 0], 
   [0, 0.1, 0], 
   [0, 0, 0.1]] */
  wr05 = casadi_c3;
  /* #122: @6 = mac(@16,@5,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w16+j, ct=wr05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #123: @9 = mac(@6,@17,@0) */
  casadi_copy((&w00), 1, (&w09));
  for (i=0, rr=(&w09); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w17+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #124: @7 = (@7+@9) */
  w07 += w09;
  /* #125: @6 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+3 : 0, 3, w06);
  /* #126: @17 = @6' */
  casadi_copy(w06, 3, w17);
  /* #127: @16 = mac(@17,@5,@1) */
  casadi_copy(w01, 3, w16);
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w17+j, ct=wr05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #128: @9 = mac(@16,@6,@0) */
  casadi_copy((&w00), 1, (&w09));
  for (i=0, rr=(&w09); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w16+j, ct=w06+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #129: @7 = (@7+@9) */
  w07 += w09;
  /* #130: @16 = input[1][2] */
  casadi_copy(arg[1] ? arg[1]+6 : 0, 3, w16);
  /* #131: @6 = @16' */
  casadi_copy(w16, 3, w06);
  /* #132: @1 = mac(@6,@5,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=wr05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #133: @0 = mac(@1,@16,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w16+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #134: @7 = (@7+@0) */
  w07 += w00;
  /* #135: output[0][0] = @7 */
  if (res[0]) res[0][0] = w07;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_pointmass_multiple_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 93;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 93*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
