/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s5[8] = {1, 3, 0, 0, 1, 2, 0, 0};
static const casadi_int casadi_s6[24] = 
  {0, 1, 2, 9, 10, 11, 18, 19,
  20, 36, 37, 38, 54, 55, 56, 21,
  22, 23, 39, 40, 41, 57, 58, 59};
static const casadi_int casadi_s7[24] = 
  {0, 3, 6, 9, 12, 15, 18, 24,
  30, 36, 42, 48, 54, 60, 66, 72,
  78, 84, 90, 96, 102, 108, 114, 120};
static const casadi_int casadi_s8[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s9[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s10[8] = {1, 3, 0, 1, 1, 2, 0, 0};
static const casadi_int casadi_s11[24] = 
  {3, 4, 5, 12, 13, 14, 24, 25,
  26, 42, 43, 44, 60, 61, 62, 27,
  28, 29, 45, 46, 47, 63, 64, 65};
static const casadi_int casadi_s12[24] = 
  {1, 4, 7, 10, 13, 16, 19, 25,
  31, 37, 43, 49, 55, 61, 67, 73,
  79, 85, 91, 97, 103, 109, 115, 121};
static const casadi_int casadi_s13[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s14[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s15[8] = {1, 3, 0, 1, 2, 2, 0, 0};
static const casadi_int casadi_s16[24] = 
  {6, 7, 8, 15, 16, 17, 30, 31,
  32, 48, 49, 50, 66, 67, 68, 33,
  34, 35, 51, 52, 53, 69, 70, 71};
static const casadi_int casadi_s17[24] = 
  {2, 5, 8, 11, 14, 17, 20, 26,
  32, 38, 44, 50, 56, 62, 68, 74,
  80, 86, 92, 98, 104, 110, 116, 122};
static const casadi_int casadi_s18[18] = 
  {72, 73, 74, 90, 91, 92, 108, 109,
  110, 75, 76, 77, 93, 94, 95, 111,
  112, 113};
static const casadi_int casadi_s19[18] = 
  {78, 79, 80, 96, 97, 98, 114, 115,
  116, 81, 82, 83, 99, 100, 101, 117,
  118, 119};
static const casadi_int casadi_s20[18] = 
  {84, 85, 86, 102, 103, 104, 120, 121,
  122, 87, 88, 89, 105, 106, 107, 123,
  124, 125};
static const casadi_int casadi_s21[153] = 
  {24, 24, 0, 3, 6, 9, 12, 15,
  18, 24, 30, 36, 42, 48, 54, 60,
  66, 72, 78, 84, 90, 96, 102, 108,
  114, 120, 126, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 3, 4, 5, 3,
  4, 5, 3, 4, 5, 6, 7, 8,
  15, 16, 17, 6, 7, 8, 15, 16,
  17, 6, 7, 8, 15, 16, 17, 9,
  10, 11, 18, 19, 20, 9, 10, 11,
  18, 19, 20, 9, 10, 11, 18, 19,
  20, 12, 13, 14, 21, 22, 23, 12,
  13, 14, 21, 22, 23, 12, 13, 14,
  21, 22, 23, 6, 7, 8, 15, 16,
  17, 6, 7, 8, 15, 16, 17, 6,
  7, 8, 15, 16, 17, 9, 10, 11,
  18, 19, 20, 9, 10, 11, 18, 19,
  20, 9, 10, 11, 18, 19, 20, 12,
  13, 14, 21, 22, 23, 12, 13, 14,
  21, 22, 23, 12, 13, 14, 21, 22,
  23};
static const casadi_int casadi_s22[3] = {24, 1, 1};
static const casadi_int casadi_s23[3] = {0, 1, 1};
static const casadi_int casadi_s24[3] = {33, 1, 1};
static const casadi_int casadi_s25[3] = {1, 1, 1};
static const casadi_int casadi_s26[3] = {0, 0, 1};
static const casadi_int casadi_s27[3] = {0, 24, 1};

static const casadi_real casadi_c0[9] = 
  {250., 0., 0., 0., 250., 0., 0., 0.,
  250.};
static const casadi_real casadi_c1[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c2[9] = 
  {30., 0., 0., 0., 30., 0., 0., 0.,
  30.};

static const casadi_real casadi_zeros[33] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess:(i0[24],i1[0],i2[0],i3[33])->(o0,o1[24],o2[24x24,126nz],o3[],o4[0x24]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+4, *w02=w+7, *w04=w+43, *w05=w+46, *w06=w+55, w07, w08, *w09=w+60, *w11=w+72, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w19, *w20=w+83, *w21=w+86, *w23=w+98, w24, w25;
  casadi_real w26, *w27=w+104, *w28=w+107, *w29=w+110, w30, w31, w32, *w33=w+116, *w34=w+119, *w35=w+122, *w36=w+125, *w37=w+128;
  casadi_real *w38=w+137, *w39=w+140, *w40=w+149, *w41=w+152, *w42=w+155, *w43=w+158, *w44=w+161, *w45=w+164, *w46=w+167, *w47=w+170, *w48=w+173, *w49=w+176;
  casadi_real *w50=w+179, *w51=w+182, *w52=w+191, *w53=w+200, *w54=w+209, *w55=w+218, *w56=w+227, *w57=w+353, *w58=w+358, *w59=w+367, *w61=w+376, *w62=w+378;
  casadi_real *w63=w+402, *w64=w+420, *w65=w+438;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr03, *wr04, *wr05, *wr09, *wr10, *wr22, *wr40, *wr41, *wr44;
  const casadi_real *wr45, *wr48, *wr49;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[:3] */
  wr04 = wr03+0;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = @2' */
  casadi_copy(w02, 3, w04);
  /* #7: @5 = 
  [[250, 0, 0], 
   [0, 250, 0], 
   [0, 0, 250]] */
  wr05 = casadi_c0;
  /* #8: @6 = mac(@4,@5,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w04+j, ct=wr05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #9: @7 = mac(@6,@2,@0) */
  casadi_copy((&w00), 1, (&w07));
  for (i=0, rr=(&w07); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #10: @8 = 0.2 */
  w08 = 2.0000000000000001e-01;
  /* #11: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w02);
  /* #12: @9 = @3[3:6] */
  wr09 = wr03+3;
  /* #13: @2 = (@2-@9) */
  for (i=0, rr=w02, cs=wr09; i<3; ++i) (*rr++) -= (*cs++);
  /* #14: @9 = @2' */
  casadi_copy(w02, 3, w09);
  /* #15: @10 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr10 = casadi_c1;
  /* #16: @11 = mac(@9,@10,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #17: @12 = mac(@11,@2,@0) */
  casadi_copy((&w00), 1, (&w12));
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #18: @12 = (@8*@12) */
  w12  = (w08*w12);
  /* #19: @7 = (@7+@12) */
  w07 += w12;
  /* #20: @12 = @3[7] */
  w12 = wr03[7];
  /* #21: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w02);
  /* #22: @13 = @2[2] */
  for (rr=(&w13), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #23: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #24: @15 = @3[8] */
  w15 = wr03[8];
  /* #25: @16 = @2[1] */
  for (rr=(&w16), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #26: @17 = (@15*@16) */
  w17  = (w15*w16);
  /* #27: @14 = (@14-@17) */
  w14 -= w17;
  /* #28: @17 = @2[0] */
  for (rr=(&w17), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #29: @18 = (@15*@17) */
  w18  = (w15*w17);
  /* #30: @19 = @3[6] */
  w19 = wr03[6];
  /* #31: @13 = (@19*@13) */
  w13  = (w19*w13);
  /* #32: @18 = (@18-@13) */
  w18 -= w13;
  /* #33: @16 = (@19*@16) */
  w16  = (w19*w16);
  /* #34: @17 = (@12*@17) */
  w17  = (w12*w17);
  /* #35: @16 = (@16-@17) */
  w16 -= w17;
  /* #36: @20 = vertcat(@14, @18, @16) */
  rr=w20;
  *rr++ = w14;
  *rr++ = w18;
  *rr++ = w16;
  /* #37: @21 = @20' */
  casadi_copy(w20, 3, w21);
  /* #38: @22 = 
  [[30, 0, 0], 
   [0, 30, 0], 
   [0, 0, 30]] */
  wr22 = casadi_c2;
  /* #39: @23 = mac(@21,@22,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=wr22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @14 = mac(@23,@20,@0) */
  casadi_copy((&w00), 1, (&w14));
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @7 = (@7+@14) */
  w07 += w14;
  /* #42: @14 = @3[10] */
  w14 = wr03[10];
  /* #43: @20 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+9 : 0, 3, w20);
  /* #44: @18 = @20[2] */
  for (rr=(&w18), cs=w20+2; cs!=w20+3; cs+=1) *rr++ = *cs;
  /* #45: @16 = (@14*@18) */
  w16  = (w14*w18);
  /* #46: @17 = @3[11] */
  w17 = wr03[11];
  /* #47: @13 = @20[1] */
  for (rr=(&w13), cs=w20+1; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #48: @24 = (@17*@13) */
  w24  = (w17*w13);
  /* #49: @16 = (@16-@24) */
  w16 -= w24;
  /* #50: @24 = @20[0] */
  for (rr=(&w24), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #51: @25 = (@17*@24) */
  w25  = (w17*w24);
  /* #52: @26 = @3[9] */
  w26 = wr03[9];
  /* #53: @18 = (@26*@18) */
  w18  = (w26*w18);
  /* #54: @25 = (@25-@18) */
  w25 -= w18;
  /* #55: @13 = (@26*@13) */
  w13  = (w26*w13);
  /* #56: @24 = (@14*@24) */
  w24  = (w14*w24);
  /* #57: @13 = (@13-@24) */
  w13 -= w24;
  /* #58: @27 = vertcat(@16, @25, @13) */
  rr=w27;
  *rr++ = w16;
  *rr++ = w25;
  *rr++ = w13;
  /* #59: @28 = @27' */
  casadi_copy(w27, 3, w28);
  /* #60: @29 = mac(@28,@22,@1) */
  casadi_copy(w01, 3, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=wr22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #61: @16 = mac(@29,@27,@0) */
  casadi_copy((&w00), 1, (&w16));
  for (i=0, rr=(&w16); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #62: @7 = (@7+@16) */
  w07 += w16;
  /* #63: @16 = @3[13] */
  w16 = wr03[13];
  /* #64: @27 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+12 : 0, 3, w27);
  /* #65: @25 = @27[2] */
  for (rr=(&w25), cs=w27+2; cs!=w27+3; cs+=1) *rr++ = *cs;
  /* #66: @13 = (@16*@25) */
  w13  = (w16*w25);
  /* #67: @24 = @3[14] */
  w24 = wr03[14];
  /* #68: @18 = @27[1] */
  for (rr=(&w18), cs=w27+1; cs!=w27+2; cs+=1) *rr++ = *cs;
  /* #69: @30 = (@24*@18) */
  w30  = (w24*w18);
  /* #70: @13 = (@13-@30) */
  w13 -= w30;
  /* #71: @30 = @27[0] */
  for (rr=(&w30), cs=w27+0; cs!=w27+1; cs+=1) *rr++ = *cs;
  /* #72: @31 = (@24*@30) */
  w31  = (w24*w30);
  /* #73: @32 = @3[12] */
  w32 = wr03[12];
  /* #74: @25 = (@32*@25) */
  w25  = (w32*w25);
  /* #75: @31 = (@31-@25) */
  w31 -= w25;
  /* #76: @18 = (@32*@18) */
  w18  = (w32*w18);
  /* #77: @30 = (@16*@30) */
  w30  = (w16*w30);
  /* #78: @18 = (@18-@30) */
  w18 -= w30;
  /* #79: @33 = vertcat(@13, @31, @18) */
  rr=w33;
  *rr++ = w13;
  *rr++ = w31;
  *rr++ = w18;
  /* #80: @34 = @33' */
  casadi_copy(w33, 3, w34);
  /* #81: @35 = mac(@34,@22,@1) */
  casadi_copy(w01, 3, w35);
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=wr22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #82: @13 = mac(@35,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #83: @7 = (@7+@13) */
  w07 += w13;
  /* #84: @33 = input[0][5] */
  casadi_copy(arg[0] ? arg[0]+15 : 0, 3, w33);
  /* #85: @36 = zeros(3x1) */
  casadi_clear(w36, 3);
  /* #86: @37 = zeros(3x3) */
  casadi_clear(w37, 9);
  /* #87: @38 = @2' */
  casadi_copy(w02, 3, w38);
  /* #88: @39 = mac(@2,@38,@37) */
  casadi_copy(w37, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w02+j, ct=w38+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #89: @39 = (@10-@39) */
  for (i=0, rr=w39, cr=wr10, cs=w39; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #90: @40 = @3[15:18] */
  wr40 = wr03+15;
  /* #91: @41 = mac(@39,@40,@36) */
  casadi_copy(w36, 3, w41);
  for (i=0, rr=w41; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=wr40+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #92: @33 = (@33-@41) */
  for (i=0, rr=w33, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #93: @41 = @33' */
  casadi_copy(w33, 3, w41);
  /* #94: @42 = mac(@41,@10,@1) */
  casadi_copy(w01, 3, w42);
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #95: @13 = mac(@42,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w42+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #96: @7 = (@7+@13) */
  w07 += w13;
  /* #97: @33 = input[0][6] */
  casadi_copy(arg[0] ? arg[0]+18 : 0, 3, w33);
  /* #98: @43 = @20' */
  casadi_copy(w20, 3, w43);
  /* #99: @39 = mac(@20,@43,@37) */
  casadi_copy(w37, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w20+j, ct=w43+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #100: @39 = (@10-@39) */
  for (i=0, rr=w39, cr=wr10, cs=w39; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #101: @44 = @3[18:21] */
  wr44 = wr03+18;
  /* #102: @45 = mac(@39,@44,@36) */
  casadi_copy(w36, 3, w45);
  for (i=0, rr=w45; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=wr44+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #103: @33 = (@33-@45) */
  for (i=0, rr=w33, cs=w45; i<3; ++i) (*rr++) -= (*cs++);
  /* #104: @45 = @33' */
  casadi_copy(w33, 3, w45);
  /* #105: @46 = mac(@45,@10,@1) */
  casadi_copy(w01, 3, w46);
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w45+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #106: @13 = mac(@46,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w46+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #107: @7 = (@7+@13) */
  w07 += w13;
  /* #108: @33 = input[0][7] */
  casadi_copy(arg[0] ? arg[0]+21 : 0, 3, w33);
  /* #109: @47 = @27' */
  casadi_copy(w27, 3, w47);
  /* #110: @39 = mac(@27,@47,@37) */
  casadi_copy(w37, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w47+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #111: @39 = (@10-@39) */
  for (i=0, rr=w39, cr=wr10, cs=w39; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #112: @48 = @3[21:24] */
  wr48 = wr03+21;
  /* #113: @49 = mac(@39,@48,@36) */
  casadi_copy(w36, 3, w49);
  for (i=0, rr=w49; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=wr48+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #114: @33 = (@33-@49) */
  for (i=0, rr=w33, cs=w49; i<3; ++i) (*rr++) -= (*cs++);
  /* #115: @49 = @33' */
  casadi_copy(w33, 3, w49);
  /* #116: @50 = mac(@49,@10,@1) */
  casadi_copy(w01, 3, w50);
  for (i=0, rr=w50; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w49+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #117: @0 = mac(@50,@33,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w50+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #118: @7 = (@7+@0) */
  w07 += w00;
  /* #119: output[0][0] = @7 */
  if (res[0]) res[0][0] = w07;
  /* #120: @6 = @6' */
  /* #121: @39 = @5' */
  for (i=0, rr=w39, cs=wr05; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #122: @33 = mac(@4,@39,@1) */
  casadi_copy(w01, 3, w33);
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w04+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #123: @33 = @33' */
  /* #124: @6 = (@6+@33) */
  for (i=0, rr=w06, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #125: output[1][0] = @6 */
  casadi_copy(w06, 3, res[1]);
  /* #126: @11 = @11' */
  /* #127: @11 = (@8*@11) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #128: @9 = (@8*@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #129: @51 = @10' */
  for (i=0, rr=w51, cs=wr10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #130: @6 = mac(@9,@51,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #131: @6 = @6' */
  /* #132: @11 = (@11+@6) */
  for (i=0, rr=w11, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #133: output[1][1] = @11 */
  if (res[1]) casadi_copy(w11, 3, res[1]+3);
  /* #134: @42 = @42' */
  /* #135: @11 = mac(@41,@51,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #136: @11 = @11' */
  /* #137: @42 = (@42+@11) */
  for (i=0, rr=w42, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #138: @11 = (-@42) */
  for (i=0, rr=w11, cs=w42; i<3; ++i) *rr++ = (- *cs++ );
  /* #139: @41 = @40' */
  wr41 = wr40;
  /* #140: @52 = mac(@11,@41,@37) */
  casadi_copy(w37, 9, w52);
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #141: @52 = (-@52) */
  for (i=0, rr=w52, cs=w52; i<9; ++i) *rr++ = (- *cs++ );
  /* #142: @11 = mac(@52,@2,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w52+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #143: @6 = mac(@38,@52,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w52+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #144: @6 = @6' */
  /* #145: @11 = (@11+@6) */
  for (i=0, rr=w11, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #146: @23 = @23' */
  /* #147: @53 = @22' */
  for (i=0, rr=w53, cs=wr22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #148: @6 = mac(@21,@53,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #149: @6 = @6' */
  /* #150: @23 = (@23+@6) */
  for (i=0, rr=w23, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #151: {@7, @0, @13} = vertsplit(@23) */
  w07 = w23[0];
  w00 = w23[1];
  w13 = w23[2];
  /* #152: @31 = (@15*@0) */
  w31  = (w15*w00);
  /* #153: @18 = (@12*@13) */
  w18  = (w12*w13);
  /* #154: @31 = (@31-@18) */
  w31 -= w18;
  /* #155: (@11[0] += @31) */
  for (rr=w11+0, cs=(&w31); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #156: @13 = (@19*@13) */
  w13  = (w19*w13);
  /* #157: @31 = (@15*@7) */
  w31  = (w15*w07);
  /* #158: @13 = (@13-@31) */
  w13 -= w31;
  /* #159: (@11[1] += @13) */
  for (rr=w11+1, cs=(&w13); rr!=w11+2; rr+=1) *rr += *cs++;
  /* #160: @7 = (@12*@7) */
  w07  = (w12*w07);
  /* #161: @0 = (@19*@0) */
  w00  = (w19*w00);
  /* #162: @7 = (@7-@0) */
  w07 -= w00;
  /* #163: (@11[2] += @7) */
  for (rr=w11+2, cs=(&w07); rr!=w11+3; rr+=1) *rr += *cs++;
  /* #164: output[1][2] = @11 */
  if (res[1]) casadi_copy(w11, 3, res[1]+6);
  /* #165: @46 = @46' */
  /* #166: @11 = mac(@45,@51,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w45+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #167: @11 = @11' */
  /* #168: @46 = (@46+@11) */
  for (i=0, rr=w46, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #169: @11 = (-@46) */
  for (i=0, rr=w11, cs=w46; i<3; ++i) *rr++ = (- *cs++ );
  /* #170: @45 = @44' */
  wr45 = wr44;
  /* #171: @54 = mac(@11,@45,@37) */
  casadi_copy(w37, 9, w54);
  for (i=0, rr=w54; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #172: @54 = (-@54) */
  for (i=0, rr=w54, cs=w54; i<9; ++i) *rr++ = (- *cs++ );
  /* #173: @11 = mac(@54,@20,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w54+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #174: @23 = mac(@43,@54,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w54+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #175: @23 = @23' */
  /* #176: @11 = (@11+@23) */
  for (i=0, rr=w11, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #177: @29 = @29' */
  /* #178: @23 = mac(@28,@53,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #179: @23 = @23' */
  /* #180: @29 = (@29+@23) */
  for (i=0, rr=w29, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #181: {@7, @0, @13} = vertsplit(@29) */
  w07 = w29[0];
  w00 = w29[1];
  w13 = w29[2];
  /* #182: @31 = (@17*@0) */
  w31  = (w17*w00);
  /* #183: @18 = (@14*@13) */
  w18  = (w14*w13);
  /* #184: @31 = (@31-@18) */
  w31 -= w18;
  /* #185: (@11[0] += @31) */
  for (rr=w11+0, cs=(&w31); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #186: @13 = (@26*@13) */
  w13  = (w26*w13);
  /* #187: @31 = (@17*@7) */
  w31  = (w17*w07);
  /* #188: @13 = (@13-@31) */
  w13 -= w31;
  /* #189: (@11[1] += @13) */
  for (rr=w11+1, cs=(&w13); rr!=w11+2; rr+=1) *rr += *cs++;
  /* #190: @7 = (@14*@7) */
  w07  = (w14*w07);
  /* #191: @0 = (@26*@0) */
  w00  = (w26*w00);
  /* #192: @7 = (@7-@0) */
  w07 -= w00;
  /* #193: (@11[2] += @7) */
  for (rr=w11+2, cs=(&w07); rr!=w11+3; rr+=1) *rr += *cs++;
  /* #194: output[1][3] = @11 */
  if (res[1]) casadi_copy(w11, 3, res[1]+9);
  /* #195: @50 = @50' */
  /* #196: @11 = mac(@49,@51,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w49+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #197: @11 = @11' */
  /* #198: @50 = (@50+@11) */
  for (i=0, rr=w50, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #199: @11 = (-@50) */
  for (i=0, rr=w11, cs=w50; i<3; ++i) *rr++ = (- *cs++ );
  /* #200: @49 = @48' */
  wr49 = wr48;
  /* #201: @55 = mac(@11,@49,@37) */
  casadi_copy(w37, 9, w55);
  for (i=0, rr=w55; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #202: @55 = (-@55) */
  for (i=0, rr=w55, cs=w55; i<9; ++i) *rr++ = (- *cs++ );
  /* #203: @11 = mac(@55,@27,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w55+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #204: @29 = mac(@47,@55,@1) */
  casadi_copy(w01, 3, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w55+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #205: @29 = @29' */
  /* #206: @11 = (@11+@29) */
  for (i=0, rr=w11, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #207: @35 = @35' */
  /* #208: @29 = mac(@34,@53,@1) */
  casadi_copy(w01, 3, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #209: @29 = @29' */
  /* #210: @35 = (@35+@29) */
  for (i=0, rr=w35, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #211: {@7, @0, @13} = vertsplit(@35) */
  w07 = w35[0];
  w00 = w35[1];
  w13 = w35[2];
  /* #212: @31 = (@24*@0) */
  w31  = (w24*w00);
  /* #213: @18 = (@16*@13) */
  w18  = (w16*w13);
  /* #214: @31 = (@31-@18) */
  w31 -= w18;
  /* #215: (@11[0] += @31) */
  for (rr=w11+0, cs=(&w31); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #216: @13 = (@32*@13) */
  w13  = (w32*w13);
  /* #217: @31 = (@24*@7) */
  w31  = (w24*w07);
  /* #218: @13 = (@13-@31) */
  w13 -= w31;
  /* #219: (@11[1] += @13) */
  for (rr=w11+1, cs=(&w13); rr!=w11+2; rr+=1) *rr += *cs++;
  /* #220: @7 = (@16*@7) */
  w07  = (w16*w07);
  /* #221: @0 = (@32*@0) */
  w00  = (w32*w00);
  /* #222: @7 = (@7-@0) */
  w07 -= w00;
  /* #223: (@11[2] += @7) */
  for (rr=w11+2, cs=(&w07); rr!=w11+3; rr+=1) *rr += *cs++;
  /* #224: output[1][4] = @11 */
  if (res[1]) casadi_copy(w11, 3, res[1]+12);
  /* #225: output[1][5] = @42 */
  if (res[1]) casadi_copy(w42, 3, res[1]+15);
  /* #226: output[1][6] = @46 */
  if (res[1]) casadi_copy(w46, 3, res[1]+18);
  /* #227: output[1][7] = @50 */
  if (res[1]) casadi_copy(w50, 3, res[1]+21);
  /* #228: @56 = zeros(24x24,126nz) */
  casadi_clear(w56, 126);
  /* #229: @57 = ones(24x1,5nz) */
  casadi_fill(w57, 5, 1.);
  /* #230: {@7, @0, @13, @31, @18, NULL, NULL, NULL} = vertsplit(@57) */
  w07 = w57[0];
  w00 = w57[1];
  w13 = w57[2];
  w31 = w57[3];
  w18 = w57[4];
  /* #231: @7 = @7' */
  /* #232: @50 = mac(@7,@5,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w07), casadi_s2, wr05, casadi_s1, w50, casadi_s0, w, 0);
  /* #233: @50 = @50' */
  /* #234: @46 = mac(@7,@39,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w07), casadi_s2, w39, casadi_s1, w46, casadi_s0, w, 0);
  /* #235: @46 = @46' */
  /* #236: @50 = (@50+@46) */
  for (i=0, rr=w50, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #237: @0 = @0' */
  /* #238: @46 = mac(@0,@10,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w00), casadi_s2, wr10, casadi_s1, w46, casadi_s0, w, 0);
  /* #239: @46 = @46' */
  /* #240: @46 = (@8*@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #241: @0 = (@8*@0) */
  w00  = (w08*w00);
  /* #242: @42 = mac(@0,@51,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w00), casadi_s2, w51, casadi_s1, w42, casadi_s0, w, 0);
  /* #243: @42 = @42' */
  /* #244: @46 = (@46+@42) */
  for (i=0, rr=w46, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #245: @42 = mac(@52,@13,@36) */
  casadi_copy(w36, 3, w42);
  casadi_mtimes(w52, casadi_s1, (&w13), casadi_s4, w42, casadi_s3, w, 0);
  /* #246: @0 = @13' */
  w00 = w13;
  /* #247: @58 = mac(@2,@0,@37) */
  casadi_copy(w37, 9, w58);
  casadi_mtimes(w02, casadi_s3, (&w00), casadi_s2, w58, casadi_s1, w, 0);
  /* #248: @59 = mac(@13,@38,@37) */
  casadi_copy(w37, 9, w59);
  casadi_mtimes((&w13), casadi_s4, w38, casadi_s0, w59, casadi_s1, w, 0);
  /* #249: @58 = (@58+@59) */
  for (i=0, rr=w58, cs=w59; i<9; ++i) (*rr++) += (*cs++);
  /* #250: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #251: @11 = mac(@58,@40,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=wr40+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #252: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) *rr++ = (- *cs++ );
  /* #253: @11 = @11' */
  /* #254: @35 = mac(@11,@10,@1) */
  casadi_copy(w01, 3, w35);
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #255: @35 = @35' */
  /* #256: @29 = mac(@11,@51,@1) */
  casadi_copy(w01, 3, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #257: @29 = @29' */
  /* #258: @35 = (@35+@29) */
  for (i=0, rr=w35, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #259: @29 = (-@35) */
  for (i=0, rr=w29, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #260: @58 = mac(@29,@41,@37) */
  casadi_copy(w37, 9, w58);
  for (i=0, rr=w58; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #261: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #262: @29 = mac(@58,@2,@36) */
  casadi_copy(w36, 3, w29);
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #263: @42 = (@42+@29) */
  for (i=0, rr=w42, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #264: @29 = mac(@38,@58,@1) */
  casadi_copy(w01, 3, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w58+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #265: @11 = mac(@0,@52,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w00), casadi_s2, w52, casadi_s1, w11, casadi_s0, w, 0);
  /* #266: @29 = (@29+@11) */
  for (i=0, rr=w29, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #267: @29 = @29' */
  /* #268: @42 = (@42+@29) */
  for (i=0, rr=w42, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #269: @60 = 00 */
  /* #270: @0 = @13[0] */
  for (rr=(&w00), cs=(&w13)+0; cs!=(&w13)+1; cs+=1) *rr++ = *cs;
  /* #271: @13 = (@15*@0) */
  w13  = (w15*w00);
  /* #272: @0 = (@12*@0) */
  w00  = (w12*w00);
  /* #273: @0 = (-@0) */
  w00 = (- w00 );
  /* #274: @61 = vertcat(@60, @13, @0) */
  rr=w61;
  *rr++ = w13;
  *rr++ = w00;
  /* #275: @61 = @61' */
  /* #276: @29 = mac(@61,@22,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes(w61, casadi_s5, wr22, casadi_s1, w29, casadi_s0, w, 0);
  /* #277: @29 = @29' */
  /* #278: @11 = mac(@61,@53,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes(w61, casadi_s5, w53, casadi_s1, w11, casadi_s0, w, 0);
  /* #279: @11 = @11' */
  /* #280: @29 = (@29+@11) */
  for (i=0, rr=w29, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #281: {@13, @0, @7} = vertsplit(@29) */
  w13 = w29[0];
  w00 = w29[1];
  w07 = w29[2];
  /* #282: @30 = (@15*@0) */
  w30  = (w15*w00);
  /* #283: @25 = (@12*@7) */
  w25  = (w12*w07);
  /* #284: @30 = (@30-@25) */
  w30 -= w25;
  /* #285: (@42[0] += @30) */
  for (rr=w42+0, cs=(&w30); rr!=w42+1; rr+=1) *rr += *cs++;
  /* #286: @7 = (@19*@7) */
  w07  = (w19*w07);
  /* #287: @30 = (@15*@13) */
  w30  = (w15*w13);
  /* #288: @7 = (@7-@30) */
  w07 -= w30;
  /* #289: (@42[1] += @7) */
  for (rr=w42+1, cs=(&w07); rr!=w42+2; rr+=1) *rr += *cs++;
  /* #290: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #291: @0 = (@19*@0) */
  w00  = (w19*w00);
  /* #292: @13 = (@13-@0) */
  w13 -= w00;
  /* #293: (@42[2] += @13) */
  for (rr=w42+2, cs=(&w13); rr!=w42+3; rr+=1) *rr += *cs++;
  /* #294: @29 = mac(@54,@31,@36) */
  casadi_copy(w36, 3, w29);
  casadi_mtimes(w54, casadi_s1, (&w31), casadi_s4, w29, casadi_s3, w, 0);
  /* #295: @13 = @31' */
  w13 = w31;
  /* #296: @58 = mac(@20,@13,@37) */
  casadi_copy(w37, 9, w58);
  casadi_mtimes(w20, casadi_s3, (&w13), casadi_s2, w58, casadi_s1, w, 0);
  /* #297: @59 = mac(@31,@43,@37) */
  casadi_copy(w37, 9, w59);
  casadi_mtimes((&w31), casadi_s4, w43, casadi_s0, w59, casadi_s1, w, 0);
  /* #298: @58 = (@58+@59) */
  for (i=0, rr=w58, cs=w59; i<9; ++i) (*rr++) += (*cs++);
  /* #299: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #300: @11 = mac(@58,@44,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=wr44+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #301: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) *rr++ = (- *cs++ );
  /* #302: @11 = @11' */
  /* #303: @34 = mac(@11,@10,@1) */
  casadi_copy(w01, 3, w34);
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #304: @34 = @34' */
  /* #305: @23 = mac(@11,@51,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #306: @23 = @23' */
  /* #307: @34 = (@34+@23) */
  for (i=0, rr=w34, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #308: @23 = (-@34) */
  for (i=0, rr=w23, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #309: @58 = mac(@23,@45,@37) */
  casadi_copy(w37, 9, w58);
  for (i=0, rr=w58; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w23+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #310: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #311: @23 = mac(@58,@20,@36) */
  casadi_copy(w36, 3, w23);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #312: @29 = (@29+@23) */
  for (i=0, rr=w29, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #313: @23 = mac(@43,@58,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w58+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #314: @11 = mac(@13,@54,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w13), casadi_s2, w54, casadi_s1, w11, casadi_s0, w, 0);
  /* #315: @23 = (@23+@11) */
  for (i=0, rr=w23, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #316: @23 = @23' */
  /* #317: @29 = (@29+@23) */
  for (i=0, rr=w29, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #318: @13 = @31[0] */
  for (rr=(&w13), cs=(&w31)+0; cs!=(&w31)+1; cs+=1) *rr++ = *cs;
  /* #319: @31 = (@17*@13) */
  w31  = (w17*w13);
  /* #320: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #321: @13 = (-@13) */
  w13 = (- w13 );
  /* #322: @61 = vertcat(@60, @31, @13) */
  rr=w61;
  *rr++ = w31;
  *rr++ = w13;
  /* #323: @61 = @61' */
  /* #324: @23 = mac(@61,@22,@1) */
  casadi_copy(w01, 3, w23);
  casadi_mtimes(w61, casadi_s5, wr22, casadi_s1, w23, casadi_s0, w, 0);
  /* #325: @23 = @23' */
  /* #326: @11 = mac(@61,@53,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes(w61, casadi_s5, w53, casadi_s1, w11, casadi_s0, w, 0);
  /* #327: @11 = @11' */
  /* #328: @23 = (@23+@11) */
  for (i=0, rr=w23, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #329: {@31, @13, @0} = vertsplit(@23) */
  w31 = w23[0];
  w13 = w23[1];
  w00 = w23[2];
  /* #330: @7 = (@17*@13) */
  w07  = (w17*w13);
  /* #331: @30 = (@14*@0) */
  w30  = (w14*w00);
  /* #332: @7 = (@7-@30) */
  w07 -= w30;
  /* #333: (@29[0] += @7) */
  for (rr=w29+0, cs=(&w07); rr!=w29+1; rr+=1) *rr += *cs++;
  /* #334: @0 = (@26*@0) */
  w00  = (w26*w00);
  /* #335: @7 = (@17*@31) */
  w07  = (w17*w31);
  /* #336: @0 = (@0-@7) */
  w00 -= w07;
  /* #337: (@29[1] += @0) */
  for (rr=w29+1, cs=(&w00); rr!=w29+2; rr+=1) *rr += *cs++;
  /* #338: @31 = (@14*@31) */
  w31  = (w14*w31);
  /* #339: @13 = (@26*@13) */
  w13  = (w26*w13);
  /* #340: @31 = (@31-@13) */
  w31 -= w13;
  /* #341: (@29[2] += @31) */
  for (rr=w29+2, cs=(&w31); rr!=w29+3; rr+=1) *rr += *cs++;
  /* #342: @23 = mac(@55,@18,@36) */
  casadi_copy(w36, 3, w23);
  casadi_mtimes(w55, casadi_s1, (&w18), casadi_s4, w23, casadi_s3, w, 0);
  /* #343: @31 = @18' */
  w31 = w18;
  /* #344: @58 = mac(@27,@31,@37) */
  casadi_copy(w37, 9, w58);
  casadi_mtimes(w27, casadi_s3, (&w31), casadi_s2, w58, casadi_s1, w, 0);
  /* #345: @59 = mac(@18,@47,@37) */
  casadi_copy(w37, 9, w59);
  casadi_mtimes((&w18), casadi_s4, w47, casadi_s0, w59, casadi_s1, w, 0);
  /* #346: @58 = (@58+@59) */
  for (i=0, rr=w58, cs=w59; i<9; ++i) (*rr++) += (*cs++);
  /* #347: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #348: @11 = mac(@58,@48,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=wr48+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #349: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) *rr++ = (- *cs++ );
  /* #350: @11 = @11' */
  /* #351: @28 = mac(@11,@10,@1) */
  casadi_copy(w01, 3, w28);
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #352: @28 = @28' */
  /* #353: @6 = mac(@11,@51,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #354: @6 = @6' */
  /* #355: @28 = (@28+@6) */
  for (i=0, rr=w28, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #356: @6 = (-@28) */
  for (i=0, rr=w06, cs=w28; i<3; ++i) *rr++ = (- *cs++ );
  /* #357: @58 = mac(@6,@49,@37) */
  casadi_copy(w37, 9, w58);
  for (i=0, rr=w58; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w06+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #358: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #359: @6 = mac(@58,@27,@36) */
  casadi_copy(w36, 3, w06);
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #360: @23 = (@23+@6) */
  for (i=0, rr=w23, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #361: @6 = mac(@47,@58,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w58+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #362: @11 = mac(@31,@55,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w31), casadi_s2, w55, casadi_s1, w11, casadi_s0, w, 0);
  /* #363: @6 = (@6+@11) */
  for (i=0, rr=w06, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #364: @6 = @6' */
  /* #365: @23 = (@23+@6) */
  for (i=0, rr=w23, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #366: @31 = @18[0] */
  for (rr=(&w31), cs=(&w18)+0; cs!=(&w18)+1; cs+=1) *rr++ = *cs;
  /* #367: @18 = (@24*@31) */
  w18  = (w24*w31);
  /* #368: @31 = (@16*@31) */
  w31  = (w16*w31);
  /* #369: @31 = (-@31) */
  w31 = (- w31 );
  /* #370: @61 = vertcat(@60, @18, @31) */
  rr=w61;
  *rr++ = w18;
  *rr++ = w31;
  /* #371: @61 = @61' */
  /* #372: @6 = mac(@61,@22,@1) */
  casadi_copy(w01, 3, w06);
  casadi_mtimes(w61, casadi_s5, wr22, casadi_s1, w06, casadi_s0, w, 0);
  /* #373: @6 = @6' */
  /* #374: @11 = mac(@61,@53,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes(w61, casadi_s5, w53, casadi_s1, w11, casadi_s0, w, 0);
  /* #375: @11 = @11' */
  /* #376: @6 = (@6+@11) */
  for (i=0, rr=w06, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #377: {@18, @31, @13} = vertsplit(@6) */
  w18 = w06[0];
  w31 = w06[1];
  w13 = w06[2];
  /* #378: @0 = (@24*@31) */
  w00  = (w24*w31);
  /* #379: @7 = (@16*@13) */
  w07  = (w16*w13);
  /* #380: @0 = (@0-@7) */
  w00 -= w07;
  /* #381: (@23[0] += @0) */
  for (rr=w23+0, cs=(&w00); rr!=w23+1; rr+=1) *rr += *cs++;
  /* #382: @13 = (@32*@13) */
  w13  = (w32*w13);
  /* #383: @0 = (@24*@18) */
  w00  = (w24*w18);
  /* #384: @13 = (@13-@0) */
  w13 -= w00;
  /* #385: (@23[1] += @13) */
  for (rr=w23+1, cs=(&w13); rr!=w23+2; rr+=1) *rr += *cs++;
  /* #386: @18 = (@16*@18) */
  w18  = (w16*w18);
  /* #387: @31 = (@32*@31) */
  w31  = (w32*w31);
  /* #388: @18 = (@18-@31) */
  w18 -= w31;
  /* #389: (@23[2] += @18) */
  for (rr=w23+2, cs=(&w18); rr!=w23+3; rr+=1) *rr += *cs++;
  /* #390: @62 = vertcat(@50, @46, @42, @29, @23, @35, @34, @28) */
  rr=w62;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  /* #391: (@56[0, 1, 2, 9, 10, 11, 18, 19, 20, 36, 37, 38, 54, 55, 56, 21, 22, 23, 39, 40, 41, 57, 58, 59] = @62) */
  for (cii=casadi_s6, rr=w56, cs=w62; cii!=casadi_s6+24; ++cii, ++cs) rr[*cii] = *cs;
  /* #392: (@56[0, 3, 6, 9, 12, 15, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 120] = @62) */
  for (cii=casadi_s7, rr=w56, cs=w62; cii!=casadi_s7+24; ++cii, ++cs) rr[*cii] = *cs;
  /* #393: @57 = ones(24x1,5nz) */
  casadi_fill(w57, 5, 1.);
  /* #394: {@18, @31, @13, @0, @7, NULL, NULL, NULL} = vertsplit(@57) */
  w18 = w57[0];
  w31 = w57[1];
  w13 = w57[2];
  w00 = w57[3];
  w07 = w57[4];
  /* #395: @18 = @18' */
  /* #396: @50 = mac(@18,@5,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w18), casadi_s8, wr05, casadi_s1, w50, casadi_s0, w, 0);
  /* #397: @50 = @50' */
  /* #398: @46 = mac(@18,@39,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w18), casadi_s8, w39, casadi_s1, w46, casadi_s0, w, 0);
  /* #399: @46 = @46' */
  /* #400: @50 = (@50+@46) */
  for (i=0, rr=w50, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #401: @31 = @31' */
  /* #402: @46 = mac(@31,@10,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w31), casadi_s8, wr10, casadi_s1, w46, casadi_s0, w, 0);
  /* #403: @46 = @46' */
  /* #404: @46 = (@8*@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #405: @31 = (@8*@31) */
  w31  = (w08*w31);
  /* #406: @42 = mac(@31,@51,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w31), casadi_s8, w51, casadi_s1, w42, casadi_s0, w, 0);
  /* #407: @42 = @42' */
  /* #408: @46 = (@46+@42) */
  for (i=0, rr=w46, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #409: @42 = mac(@52,@13,@36) */
  casadi_copy(w36, 3, w42);
  casadi_mtimes(w52, casadi_s1, (&w13), casadi_s9, w42, casadi_s3, w, 0);
  /* #410: @31 = @13' */
  w31 = w13;
  /* #411: @58 = mac(@2,@31,@37) */
  casadi_copy(w37, 9, w58);
  casadi_mtimes(w02, casadi_s3, (&w31), casadi_s8, w58, casadi_s1, w, 0);
  /* #412: @59 = mac(@13,@38,@37) */
  casadi_copy(w37, 9, w59);
  casadi_mtimes((&w13), casadi_s9, w38, casadi_s0, w59, casadi_s1, w, 0);
  /* #413: @58 = (@58+@59) */
  for (i=0, rr=w58, cs=w59; i<9; ++i) (*rr++) += (*cs++);
  /* #414: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #415: @29 = mac(@58,@40,@36) */
  casadi_copy(w36, 3, w29);
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=wr40+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #416: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) *rr++ = (- *cs++ );
  /* #417: @29 = @29' */
  /* #418: @23 = mac(@29,@10,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #419: @23 = @23' */
  /* #420: @35 = mac(@29,@51,@1) */
  casadi_copy(w01, 3, w35);
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #421: @35 = @35' */
  /* #422: @23 = (@23+@35) */
  for (i=0, rr=w23, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #423: @35 = (-@23) */
  for (i=0, rr=w35, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #424: @58 = mac(@35,@41,@37) */
  casadi_copy(w37, 9, w58);
  for (i=0, rr=w58; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w35+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #425: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #426: @35 = mac(@58,@2,@36) */
  casadi_copy(w36, 3, w35);
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #427: @42 = (@42+@35) */
  for (i=0, rr=w42, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #428: @35 = mac(@38,@58,@1) */
  casadi_copy(w01, 3, w35);
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w58+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #429: @29 = mac(@31,@52,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes((&w31), casadi_s8, w52, casadi_s1, w29, casadi_s0, w, 0);
  /* #430: @35 = (@35+@29) */
  for (i=0, rr=w35, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #431: @35 = @35' */
  /* #432: @42 = (@42+@35) */
  for (i=0, rr=w42, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #433: @31 = @13[0] */
  for (rr=(&w31), cs=(&w13)+0; cs!=(&w13)+1; cs+=1) *rr++ = *cs;
  /* #434: @13 = (@15*@31) */
  w13  = (w15*w31);
  /* #435: @13 = (-@13) */
  w13 = (- w13 );
  /* #436: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #437: @61 = vertcat(@13, @60, @31) */
  rr=w61;
  *rr++ = w13;
  *rr++ = w31;
  /* #438: @61 = @61' */
  /* #439: @35 = mac(@61,@22,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes(w61, casadi_s10, wr22, casadi_s1, w35, casadi_s0, w, 0);
  /* #440: @35 = @35' */
  /* #441: @29 = mac(@61,@53,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes(w61, casadi_s10, w53, casadi_s1, w29, casadi_s0, w, 0);
  /* #442: @29 = @29' */
  /* #443: @35 = (@35+@29) */
  for (i=0, rr=w35, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #444: {@13, @31, @18} = vertsplit(@35) */
  w13 = w35[0];
  w31 = w35[1];
  w18 = w35[2];
  /* #445: @30 = (@15*@31) */
  w30  = (w15*w31);
  /* #446: @25 = (@12*@18) */
  w25  = (w12*w18);
  /* #447: @30 = (@30-@25) */
  w30 -= w25;
  /* #448: (@42[0] += @30) */
  for (rr=w42+0, cs=(&w30); rr!=w42+1; rr+=1) *rr += *cs++;
  /* #449: @18 = (@19*@18) */
  w18  = (w19*w18);
  /* #450: @30 = (@15*@13) */
  w30  = (w15*w13);
  /* #451: @18 = (@18-@30) */
  w18 -= w30;
  /* #452: (@42[1] += @18) */
  for (rr=w42+1, cs=(&w18); rr!=w42+2; rr+=1) *rr += *cs++;
  /* #453: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #454: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #455: @13 = (@13-@31) */
  w13 -= w31;
  /* #456: (@42[2] += @13) */
  for (rr=w42+2, cs=(&w13); rr!=w42+3; rr+=1) *rr += *cs++;
  /* #457: @35 = mac(@54,@0,@36) */
  casadi_copy(w36, 3, w35);
  casadi_mtimes(w54, casadi_s1, (&w00), casadi_s9, w35, casadi_s3, w, 0);
  /* #458: @13 = @0' */
  w13 = w00;
  /* #459: @58 = mac(@20,@13,@37) */
  casadi_copy(w37, 9, w58);
  casadi_mtimes(w20, casadi_s3, (&w13), casadi_s8, w58, casadi_s1, w, 0);
  /* #460: @59 = mac(@0,@43,@37) */
  casadi_copy(w37, 9, w59);
  casadi_mtimes((&w00), casadi_s9, w43, casadi_s0, w59, casadi_s1, w, 0);
  /* #461: @58 = (@58+@59) */
  for (i=0, rr=w58, cs=w59; i<9; ++i) (*rr++) += (*cs++);
  /* #462: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #463: @29 = mac(@58,@44,@36) */
  casadi_copy(w36, 3, w29);
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=wr44+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #464: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) *rr++ = (- *cs++ );
  /* #465: @29 = @29' */
  /* #466: @34 = mac(@29,@10,@1) */
  casadi_copy(w01, 3, w34);
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #467: @34 = @34' */
  /* #468: @28 = mac(@29,@51,@1) */
  casadi_copy(w01, 3, w28);
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #469: @28 = @28' */
  /* #470: @34 = (@34+@28) */
  for (i=0, rr=w34, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #471: @28 = (-@34) */
  for (i=0, rr=w28, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #472: @58 = mac(@28,@45,@37) */
  casadi_copy(w37, 9, w58);
  for (i=0, rr=w58; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #473: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #474: @28 = mac(@58,@20,@36) */
  casadi_copy(w36, 3, w28);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #475: @35 = (@35+@28) */
  for (i=0, rr=w35, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #476: @28 = mac(@43,@58,@1) */
  casadi_copy(w01, 3, w28);
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w58+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #477: @29 = mac(@13,@54,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes((&w13), casadi_s8, w54, casadi_s1, w29, casadi_s0, w, 0);
  /* #478: @28 = (@28+@29) */
  for (i=0, rr=w28, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #479: @28 = @28' */
  /* #480: @35 = (@35+@28) */
  for (i=0, rr=w35, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #481: @13 = @0[0] */
  for (rr=(&w13), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #482: @0 = (@17*@13) */
  w00  = (w17*w13);
  /* #483: @0 = (-@0) */
  w00 = (- w00 );
  /* #484: @13 = (@26*@13) */
  w13  = (w26*w13);
  /* #485: @61 = vertcat(@0, @60, @13) */
  rr=w61;
  *rr++ = w00;
  *rr++ = w13;
  /* #486: @61 = @61' */
  /* #487: @28 = mac(@61,@22,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes(w61, casadi_s10, wr22, casadi_s1, w28, casadi_s0, w, 0);
  /* #488: @28 = @28' */
  /* #489: @29 = mac(@61,@53,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes(w61, casadi_s10, w53, casadi_s1, w29, casadi_s0, w, 0);
  /* #490: @29 = @29' */
  /* #491: @28 = (@28+@29) */
  for (i=0, rr=w28, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #492: {@0, @13, @31} = vertsplit(@28) */
  w00 = w28[0];
  w13 = w28[1];
  w31 = w28[2];
  /* #493: @18 = (@17*@13) */
  w18  = (w17*w13);
  /* #494: @30 = (@14*@31) */
  w30  = (w14*w31);
  /* #495: @18 = (@18-@30) */
  w18 -= w30;
  /* #496: (@35[0] += @18) */
  for (rr=w35+0, cs=(&w18); rr!=w35+1; rr+=1) *rr += *cs++;
  /* #497: @31 = (@26*@31) */
  w31  = (w26*w31);
  /* #498: @18 = (@17*@0) */
  w18  = (w17*w00);
  /* #499: @31 = (@31-@18) */
  w31 -= w18;
  /* #500: (@35[1] += @31) */
  for (rr=w35+1, cs=(&w31); rr!=w35+2; rr+=1) *rr += *cs++;
  /* #501: @0 = (@14*@0) */
  w00  = (w14*w00);
  /* #502: @13 = (@26*@13) */
  w13  = (w26*w13);
  /* #503: @0 = (@0-@13) */
  w00 -= w13;
  /* #504: (@35[2] += @0) */
  for (rr=w35+2, cs=(&w00); rr!=w35+3; rr+=1) *rr += *cs++;
  /* #505: @28 = mac(@55,@7,@36) */
  casadi_copy(w36, 3, w28);
  casadi_mtimes(w55, casadi_s1, (&w07), casadi_s9, w28, casadi_s3, w, 0);
  /* #506: @0 = @7' */
  w00 = w07;
  /* #507: @58 = mac(@27,@0,@37) */
  casadi_copy(w37, 9, w58);
  casadi_mtimes(w27, casadi_s3, (&w00), casadi_s8, w58, casadi_s1, w, 0);
  /* #508: @59 = mac(@7,@47,@37) */
  casadi_copy(w37, 9, w59);
  casadi_mtimes((&w07), casadi_s9, w47, casadi_s0, w59, casadi_s1, w, 0);
  /* #509: @58 = (@58+@59) */
  for (i=0, rr=w58, cs=w59; i<9; ++i) (*rr++) += (*cs++);
  /* #510: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #511: @29 = mac(@58,@48,@36) */
  casadi_copy(w36, 3, w29);
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=wr48+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #512: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) *rr++ = (- *cs++ );
  /* #513: @29 = @29' */
  /* #514: @6 = mac(@29,@10,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #515: @6 = @6' */
  /* #516: @11 = mac(@29,@51,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #517: @11 = @11' */
  /* #518: @6 = (@6+@11) */
  for (i=0, rr=w06, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #519: @11 = (-@6) */
  for (i=0, rr=w11, cs=w06; i<3; ++i) *rr++ = (- *cs++ );
  /* #520: @58 = mac(@11,@49,@37) */
  casadi_copy(w37, 9, w58);
  for (i=0, rr=w58; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #521: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #522: @11 = mac(@58,@27,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #523: @28 = (@28+@11) */
  for (i=0, rr=w28, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #524: @11 = mac(@47,@58,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w58+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #525: @29 = mac(@0,@55,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes((&w00), casadi_s8, w55, casadi_s1, w29, casadi_s0, w, 0);
  /* #526: @11 = (@11+@29) */
  for (i=0, rr=w11, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #527: @11 = @11' */
  /* #528: @28 = (@28+@11) */
  for (i=0, rr=w28, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #529: @0 = @7[0] */
  for (rr=(&w00), cs=(&w07)+0; cs!=(&w07)+1; cs+=1) *rr++ = *cs;
  /* #530: @7 = (@24*@0) */
  w07  = (w24*w00);
  /* #531: @7 = (-@7) */
  w07 = (- w07 );
  /* #532: @0 = (@32*@0) */
  w00  = (w32*w00);
  /* #533: @61 = vertcat(@7, @60, @0) */
  rr=w61;
  *rr++ = w07;
  *rr++ = w00;
  /* #534: @61 = @61' */
  /* #535: @11 = mac(@61,@22,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes(w61, casadi_s10, wr22, casadi_s1, w11, casadi_s0, w, 0);
  /* #536: @11 = @11' */
  /* #537: @29 = mac(@61,@53,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes(w61, casadi_s10, w53, casadi_s1, w29, casadi_s0, w, 0);
  /* #538: @29 = @29' */
  /* #539: @11 = (@11+@29) */
  for (i=0, rr=w11, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #540: {@7, @0, @13} = vertsplit(@11) */
  w07 = w11[0];
  w00 = w11[1];
  w13 = w11[2];
  /* #541: @31 = (@24*@0) */
  w31  = (w24*w00);
  /* #542: @18 = (@16*@13) */
  w18  = (w16*w13);
  /* #543: @31 = (@31-@18) */
  w31 -= w18;
  /* #544: (@28[0] += @31) */
  for (rr=w28+0, cs=(&w31); rr!=w28+1; rr+=1) *rr += *cs++;
  /* #545: @13 = (@32*@13) */
  w13  = (w32*w13);
  /* #546: @31 = (@24*@7) */
  w31  = (w24*w07);
  /* #547: @13 = (@13-@31) */
  w13 -= w31;
  /* #548: (@28[1] += @13) */
  for (rr=w28+1, cs=(&w13); rr!=w28+2; rr+=1) *rr += *cs++;
  /* #549: @7 = (@16*@7) */
  w07  = (w16*w07);
  /* #550: @0 = (@32*@0) */
  w00  = (w32*w00);
  /* #551: @7 = (@7-@0) */
  w07 -= w00;
  /* #552: (@28[2] += @7) */
  for (rr=w28+2, cs=(&w07); rr!=w28+3; rr+=1) *rr += *cs++;
  /* #553: @62 = vertcat(@50, @46, @42, @35, @28, @23, @34, @6) */
  rr=w62;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  /* #554: (@56[3, 4, 5, 12, 13, 14, 24, 25, 26, 42, 43, 44, 60, 61, 62, 27, 28, 29, 45, 46, 47, 63, 64, 65] = @62) */
  for (cii=casadi_s11, rr=w56, cs=w62; cii!=casadi_s11+24; ++cii, ++cs) rr[*cii] = *cs;
  /* #555: (@56[1, 4, 7, 10, 13, 16, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97, 103, 109, 115, 121] = @62) */
  for (cii=casadi_s12, rr=w56, cs=w62; cii!=casadi_s12+24; ++cii, ++cs) rr[*cii] = *cs;
  /* #556: @57 = ones(24x1,5nz) */
  casadi_fill(w57, 5, 1.);
  /* #557: {@7, @0, @13, @31, @18, NULL, NULL, NULL} = vertsplit(@57) */
  w07 = w57[0];
  w00 = w57[1];
  w13 = w57[2];
  w31 = w57[3];
  w18 = w57[4];
  /* #558: @7 = @7' */
  /* #559: @50 = mac(@7,@5,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w07), casadi_s13, wr05, casadi_s1, w50, casadi_s0, w, 0);
  /* #560: @50 = @50' */
  /* #561: @46 = mac(@7,@39,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w07), casadi_s13, w39, casadi_s1, w46, casadi_s0, w, 0);
  /* #562: @46 = @46' */
  /* #563: @50 = (@50+@46) */
  for (i=0, rr=w50, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #564: @0 = @0' */
  /* #565: @46 = mac(@0,@10,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w00), casadi_s13, wr10, casadi_s1, w46, casadi_s0, w, 0);
  /* #566: @46 = @46' */
  /* #567: @46 = (@8*@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #568: @8 = (@8*@0) */
  w08 *= w00;
  /* #569: @42 = mac(@8,@51,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w08), casadi_s13, w51, casadi_s1, w42, casadi_s0, w, 0);
  /* #570: @42 = @42' */
  /* #571: @46 = (@46+@42) */
  for (i=0, rr=w46, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #572: @42 = mac(@52,@13,@36) */
  casadi_copy(w36, 3, w42);
  casadi_mtimes(w52, casadi_s1, (&w13), casadi_s14, w42, casadi_s3, w, 0);
  /* #573: @8 = @13' */
  w08 = w13;
  /* #574: @39 = mac(@2,@8,@37) */
  casadi_copy(w37, 9, w39);
  casadi_mtimes(w02, casadi_s3, (&w08), casadi_s13, w39, casadi_s1, w, 0);
  /* #575: @5 = mac(@13,@38,@37) */
  casadi_copy(w37, 9, w05);
  casadi_mtimes((&w13), casadi_s14, w38, casadi_s0, w05, casadi_s1, w, 0);
  /* #576: @39 = (@39+@5) */
  for (i=0, rr=w39, cs=w05; i<9; ++i) (*rr++) += (*cs++);
  /* #577: @39 = (-@39) */
  for (i=0, rr=w39, cs=w39; i<9; ++i) *rr++ = (- *cs++ );
  /* #578: @35 = mac(@39,@40,@36) */
  casadi_copy(w36, 3, w35);
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=wr40+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #579: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #580: @35 = @35' */
  /* #581: @40 = mac(@35,@10,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #582: @40 = @40' */
  /* #583: @28 = mac(@35,@51,@1) */
  casadi_copy(w01, 3, w28);
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #584: @28 = @28' */
  /* #585: @40 = (@40+@28) */
  for (i=0, rr=w40, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #586: @28 = (-@40) */
  for (i=0, rr=w28, cs=w40; i<3; ++i) *rr++ = (- *cs++ );
  /* #587: @39 = mac(@28,@41,@37) */
  casadi_copy(w37, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #588: @39 = (-@39) */
  for (i=0, rr=w39, cs=w39; i<9; ++i) *rr++ = (- *cs++ );
  /* #589: @28 = mac(@39,@2,@36) */
  casadi_copy(w36, 3, w28);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #590: @42 = (@42+@28) */
  for (i=0, rr=w42, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #591: @28 = mac(@38,@39,@1) */
  casadi_copy(w01, 3, w28);
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #592: @35 = mac(@8,@52,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes((&w08), casadi_s13, w52, casadi_s1, w35, casadi_s0, w, 0);
  /* #593: @28 = (@28+@35) */
  for (i=0, rr=w28, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #594: @28 = @28' */
  /* #595: @42 = (@42+@28) */
  for (i=0, rr=w42, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #596: @8 = @13[0] */
  for (rr=(&w08), cs=(&w13)+0; cs!=(&w13)+1; cs+=1) *rr++ = *cs;
  /* #597: @13 = (@12*@8) */
  w13  = (w12*w08);
  /* #598: @8 = (@19*@8) */
  w08  = (w19*w08);
  /* #599: @8 = (-@8) */
  w08 = (- w08 );
  /* #600: @61 = vertcat(@13, @8, @60) */
  rr=w61;
  *rr++ = w13;
  *rr++ = w08;
  /* #601: @61 = @61' */
  /* #602: @28 = mac(@61,@22,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes(w61, casadi_s15, wr22, casadi_s1, w28, casadi_s0, w, 0);
  /* #603: @28 = @28' */
  /* #604: @35 = mac(@61,@53,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes(w61, casadi_s15, w53, casadi_s1, w35, casadi_s0, w, 0);
  /* #605: @35 = @35' */
  /* #606: @28 = (@28+@35) */
  for (i=0, rr=w28, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #607: {@13, @8, @0} = vertsplit(@28) */
  w13 = w28[0];
  w08 = w28[1];
  w00 = w28[2];
  /* #608: @7 = (@15*@8) */
  w07  = (w15*w08);
  /* #609: @30 = (@12*@0) */
  w30  = (w12*w00);
  /* #610: @7 = (@7-@30) */
  w07 -= w30;
  /* #611: (@42[0] += @7) */
  for (rr=w42+0, cs=(&w07); rr!=w42+1; rr+=1) *rr += *cs++;
  /* #612: @0 = (@19*@0) */
  w00  = (w19*w00);
  /* #613: @15 = (@15*@13) */
  w15 *= w13;
  /* #614: @0 = (@0-@15) */
  w00 -= w15;
  /* #615: (@42[1] += @0) */
  for (rr=w42+1, cs=(&w00); rr!=w42+2; rr+=1) *rr += *cs++;
  /* #616: @12 = (@12*@13) */
  w12 *= w13;
  /* #617: @19 = (@19*@8) */
  w19 *= w08;
  /* #618: @12 = (@12-@19) */
  w12 -= w19;
  /* #619: (@42[2] += @12) */
  for (rr=w42+2, cs=(&w12); rr!=w42+3; rr+=1) *rr += *cs++;
  /* #620: @28 = mac(@54,@31,@36) */
  casadi_copy(w36, 3, w28);
  casadi_mtimes(w54, casadi_s1, (&w31), casadi_s14, w28, casadi_s3, w, 0);
  /* #621: @12 = @31' */
  w12 = w31;
  /* #622: @52 = mac(@20,@12,@37) */
  casadi_copy(w37, 9, w52);
  casadi_mtimes(w20, casadi_s3, (&w12), casadi_s13, w52, casadi_s1, w, 0);
  /* #623: @39 = mac(@31,@43,@37) */
  casadi_copy(w37, 9, w39);
  casadi_mtimes((&w31), casadi_s14, w43, casadi_s0, w39, casadi_s1, w, 0);
  /* #624: @52 = (@52+@39) */
  for (i=0, rr=w52, cs=w39; i<9; ++i) (*rr++) += (*cs++);
  /* #625: @52 = (-@52) */
  for (i=0, rr=w52, cs=w52; i<9; ++i) *rr++ = (- *cs++ );
  /* #626: @35 = mac(@52,@44,@36) */
  casadi_copy(w36, 3, w35);
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w52+j, ct=wr44+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #627: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #628: @35 = @35' */
  /* #629: @44 = mac(@35,@10,@1) */
  casadi_copy(w01, 3, w44);
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #630: @44 = @44' */
  /* #631: @23 = mac(@35,@51,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #632: @23 = @23' */
  /* #633: @44 = (@44+@23) */
  for (i=0, rr=w44, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #634: @23 = (-@44) */
  for (i=0, rr=w23, cs=w44; i<3; ++i) *rr++ = (- *cs++ );
  /* #635: @52 = mac(@23,@45,@37) */
  casadi_copy(w37, 9, w52);
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w23+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #636: @52 = (-@52) */
  for (i=0, rr=w52, cs=w52; i<9; ++i) *rr++ = (- *cs++ );
  /* #637: @23 = mac(@52,@20,@36) */
  casadi_copy(w36, 3, w23);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w52+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #638: @28 = (@28+@23) */
  for (i=0, rr=w28, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #639: @23 = mac(@43,@52,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w52+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #640: @35 = mac(@12,@54,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes((&w12), casadi_s13, w54, casadi_s1, w35, casadi_s0, w, 0);
  /* #641: @23 = (@23+@35) */
  for (i=0, rr=w23, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #642: @23 = @23' */
  /* #643: @28 = (@28+@23) */
  for (i=0, rr=w28, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #644: @12 = @31[0] */
  for (rr=(&w12), cs=(&w31)+0; cs!=(&w31)+1; cs+=1) *rr++ = *cs;
  /* #645: @31 = (@14*@12) */
  w31  = (w14*w12);
  /* #646: @12 = (@26*@12) */
  w12  = (w26*w12);
  /* #647: @12 = (-@12) */
  w12 = (- w12 );
  /* #648: @61 = vertcat(@31, @12, @60) */
  rr=w61;
  *rr++ = w31;
  *rr++ = w12;
  /* #649: @61 = @61' */
  /* #650: @23 = mac(@61,@22,@1) */
  casadi_copy(w01, 3, w23);
  casadi_mtimes(w61, casadi_s15, wr22, casadi_s1, w23, casadi_s0, w, 0);
  /* #651: @23 = @23' */
  /* #652: @35 = mac(@61,@53,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes(w61, casadi_s15, w53, casadi_s1, w35, casadi_s0, w, 0);
  /* #653: @35 = @35' */
  /* #654: @23 = (@23+@35) */
  for (i=0, rr=w23, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #655: {@31, @12, @19} = vertsplit(@23) */
  w31 = w23[0];
  w12 = w23[1];
  w19 = w23[2];
  /* #656: @8 = (@17*@12) */
  w08  = (w17*w12);
  /* #657: @13 = (@14*@19) */
  w13  = (w14*w19);
  /* #658: @8 = (@8-@13) */
  w08 -= w13;
  /* #659: (@28[0] += @8) */
  for (rr=w28+0, cs=(&w08); rr!=w28+1; rr+=1) *rr += *cs++;
  /* #660: @19 = (@26*@19) */
  w19  = (w26*w19);
  /* #661: @17 = (@17*@31) */
  w17 *= w31;
  /* #662: @19 = (@19-@17) */
  w19 -= w17;
  /* #663: (@28[1] += @19) */
  for (rr=w28+1, cs=(&w19); rr!=w28+2; rr+=1) *rr += *cs++;
  /* #664: @14 = (@14*@31) */
  w14 *= w31;
  /* #665: @26 = (@26*@12) */
  w26 *= w12;
  /* #666: @14 = (@14-@26) */
  w14 -= w26;
  /* #667: (@28[2] += @14) */
  for (rr=w28+2, cs=(&w14); rr!=w28+3; rr+=1) *rr += *cs++;
  /* #668: @23 = mac(@55,@18,@36) */
  casadi_copy(w36, 3, w23);
  casadi_mtimes(w55, casadi_s1, (&w18), casadi_s14, w23, casadi_s3, w, 0);
  /* #669: @14 = @18' */
  w14 = w18;
  /* #670: @54 = mac(@27,@14,@37) */
  casadi_copy(w37, 9, w54);
  casadi_mtimes(w27, casadi_s3, (&w14), casadi_s13, w54, casadi_s1, w, 0);
  /* #671: @52 = mac(@18,@47,@37) */
  casadi_copy(w37, 9, w52);
  casadi_mtimes((&w18), casadi_s14, w47, casadi_s0, w52, casadi_s1, w, 0);
  /* #672: @54 = (@54+@52) */
  for (i=0, rr=w54, cs=w52; i<9; ++i) (*rr++) += (*cs++);
  /* #673: @54 = (-@54) */
  for (i=0, rr=w54, cs=w54; i<9; ++i) *rr++ = (- *cs++ );
  /* #674: @35 = mac(@54,@48,@36) */
  casadi_copy(w36, 3, w35);
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w54+j, ct=wr48+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #675: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #676: @35 = @35' */
  /* #677: @48 = mac(@35,@10,@1) */
  casadi_copy(w01, 3, w48);
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #678: @48 = @48' */
  /* #679: @34 = mac(@35,@51,@1) */
  casadi_copy(w01, 3, w34);
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #680: @34 = @34' */
  /* #681: @48 = (@48+@34) */
  for (i=0, rr=w48, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #682: @34 = (-@48) */
  for (i=0, rr=w34, cs=w48; i<3; ++i) *rr++ = (- *cs++ );
  /* #683: @54 = mac(@34,@49,@37) */
  casadi_copy(w37, 9, w54);
  for (i=0, rr=w54; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w34+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #684: @54 = (-@54) */
  for (i=0, rr=w54, cs=w54; i<9; ++i) *rr++ = (- *cs++ );
  /* #685: @34 = mac(@54,@27,@36) */
  casadi_copy(w36, 3, w34);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w54+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #686: @23 = (@23+@34) */
  for (i=0, rr=w23, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #687: @34 = mac(@47,@54,@1) */
  casadi_copy(w01, 3, w34);
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w54+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #688: @35 = mac(@14,@55,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes((&w14), casadi_s13, w55, casadi_s1, w35, casadi_s0, w, 0);
  /* #689: @34 = (@34+@35) */
  for (i=0, rr=w34, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #690: @34 = @34' */
  /* #691: @23 = (@23+@34) */
  for (i=0, rr=w23, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #692: @14 = @18[0] */
  for (rr=(&w14), cs=(&w18)+0; cs!=(&w18)+1; cs+=1) *rr++ = *cs;
  /* #693: @18 = (@16*@14) */
  w18  = (w16*w14);
  /* #694: @14 = (@32*@14) */
  w14  = (w32*w14);
  /* #695: @14 = (-@14) */
  w14 = (- w14 );
  /* #696: @61 = vertcat(@18, @14, @60) */
  rr=w61;
  *rr++ = w18;
  *rr++ = w14;
  /* #697: @61 = @61' */
  /* #698: @34 = mac(@61,@22,@1) */
  casadi_copy(w01, 3, w34);
  casadi_mtimes(w61, casadi_s15, wr22, casadi_s1, w34, casadi_s0, w, 0);
  /* #699: @34 = @34' */
  /* #700: @35 = mac(@61,@53,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes(w61, casadi_s15, w53, casadi_s1, w35, casadi_s0, w, 0);
  /* #701: @35 = @35' */
  /* #702: @34 = (@34+@35) */
  for (i=0, rr=w34, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #703: {@18, @14, @26} = vertsplit(@34) */
  w18 = w34[0];
  w14 = w34[1];
  w26 = w34[2];
  /* #704: @12 = (@24*@14) */
  w12  = (w24*w14);
  /* #705: @31 = (@16*@26) */
  w31  = (w16*w26);
  /* #706: @12 = (@12-@31) */
  w12 -= w31;
  /* #707: (@23[0] += @12) */
  for (rr=w23+0, cs=(&w12); rr!=w23+1; rr+=1) *rr += *cs++;
  /* #708: @26 = (@32*@26) */
  w26  = (w32*w26);
  /* #709: @24 = (@24*@18) */
  w24 *= w18;
  /* #710: @26 = (@26-@24) */
  w26 -= w24;
  /* #711: (@23[1] += @26) */
  for (rr=w23+1, cs=(&w26); rr!=w23+2; rr+=1) *rr += *cs++;
  /* #712: @16 = (@16*@18) */
  w16 *= w18;
  /* #713: @32 = (@32*@14) */
  w32 *= w14;
  /* #714: @16 = (@16-@32) */
  w16 -= w32;
  /* #715: (@23[2] += @16) */
  for (rr=w23+2, cs=(&w16); rr!=w23+3; rr+=1) *rr += *cs++;
  /* #716: @62 = vertcat(@50, @46, @42, @28, @23, @40, @44, @48) */
  rr=w62;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<3; ++i) *rr++ = *cs++;
  /* #717: (@56[6, 7, 8, 15, 16, 17, 30, 31, 32, 48, 49, 50, 66, 67, 68, 33, 34, 35, 51, 52, 53, 69, 70, 71] = @62) */
  for (cii=casadi_s16, rr=w56, cs=w62; cii!=casadi_s16+24; ++cii, ++cs) rr[*cii] = *cs;
  /* #718: (@56[2, 5, 8, 11, 14, 17, 20, 26, 32, 38, 44, 50, 56, 62, 68, 74, 80, 86, 92, 98, 104, 110, 116, 122] = @62) */
  for (cii=casadi_s17, rr=w56, cs=w62; cii!=casadi_s17+24; ++cii, ++cs) rr[*cii] = *cs;
  /* #719: @60 = zeros(3x1,0nz) */
  /* #720: @50 = ones(24x1,3nz) */
  casadi_fill(w50, 3, 1.);
  /* #721: {NULL, NULL, NULL, NULL, NULL, @16, @32, @14} = vertsplit(@50) */
  w16 = w50[0];
  w32 = w50[1];
  w14 = w50[2];
  /* #722: @16 = @16' */
  /* #723: @50 = mac(@16,@10,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w16), casadi_s2, wr10, casadi_s1, w50, casadi_s0, w, 0);
  /* #724: @50 = @50' */
  /* #725: @46 = mac(@16,@51,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w16), casadi_s2, w51, casadi_s1, w46, casadi_s0, w, 0);
  /* #726: @46 = @46' */
  /* #727: @50 = (@50+@46) */
  for (i=0, rr=w50, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #728: @46 = (-@50) */
  for (i=0, rr=w46, cs=w50; i<3; ++i) *rr++ = (- *cs++ );
  /* #729: @53 = mac(@46,@41,@37) */
  casadi_copy(w37, 9, w53);
  for (i=0, rr=w53; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w46+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #730: @53 = (-@53) */
  for (i=0, rr=w53, cs=w53; i<9; ++i) *rr++ = (- *cs++ );
  /* #731: @46 = mac(@53,@2,@36) */
  casadi_copy(w36, 3, w46);
  for (i=0, rr=w46; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w53+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #732: @42 = mac(@38,@53,@1) */
  casadi_copy(w01, 3, w42);
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #733: @42 = @42' */
  /* #734: @46 = (@46+@42) */
  for (i=0, rr=w46, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #735: @32 = @32' */
  /* #736: @42 = mac(@32,@10,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w32), casadi_s2, wr10, casadi_s1, w42, casadi_s0, w, 0);
  /* #737: @42 = @42' */
  /* #738: @28 = mac(@32,@51,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes((&w32), casadi_s2, w51, casadi_s1, w28, casadi_s0, w, 0);
  /* #739: @28 = @28' */
  /* #740: @42 = (@42+@28) */
  for (i=0, rr=w42, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #741: @28 = (-@42) */
  for (i=0, rr=w28, cs=w42; i<3; ++i) *rr++ = (- *cs++ );
  /* #742: @53 = mac(@28,@45,@37) */
  casadi_copy(w37, 9, w53);
  for (i=0, rr=w53; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #743: @53 = (-@53) */
  for (i=0, rr=w53, cs=w53; i<9; ++i) *rr++ = (- *cs++ );
  /* #744: @28 = mac(@53,@20,@36) */
  casadi_copy(w36, 3, w28);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w53+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #745: @23 = mac(@43,@53,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #746: @23 = @23' */
  /* #747: @28 = (@28+@23) */
  for (i=0, rr=w28, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #748: @14 = @14' */
  /* #749: @23 = mac(@14,@10,@1) */
  casadi_copy(w01, 3, w23);
  casadi_mtimes((&w14), casadi_s2, wr10, casadi_s1, w23, casadi_s0, w, 0);
  /* #750: @23 = @23' */
  /* #751: @40 = mac(@14,@51,@1) */
  casadi_copy(w01, 3, w40);
  casadi_mtimes((&w14), casadi_s2, w51, casadi_s1, w40, casadi_s0, w, 0);
  /* #752: @40 = @40' */
  /* #753: @23 = (@23+@40) */
  for (i=0, rr=w23, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #754: @40 = (-@23) */
  for (i=0, rr=w40, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #755: @53 = mac(@40,@49,@37) */
  casadi_copy(w37, 9, w53);
  for (i=0, rr=w53; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w40+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #756: @53 = (-@53) */
  for (i=0, rr=w53, cs=w53; i<9; ++i) *rr++ = (- *cs++ );
  /* #757: @40 = mac(@53,@27,@36) */
  casadi_copy(w36, 3, w40);
  for (i=0, rr=w40; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w53+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #758: @44 = mac(@47,@53,@1) */
  casadi_copy(w01, 3, w44);
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #759: @44 = @44' */
  /* #760: @40 = (@40+@44) */
  for (i=0, rr=w40, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #761: @63 = vertcat(@60, @60, @46, @28, @40, @50, @42, @23) */
  rr=w63;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  /* #762: @64 = @63[:18] */
  for (rr=w64, cs=w63+0; cs!=w63+18; cs+=1) *rr++ = *cs;
  /* #763: (@56[72, 73, 74, 90, 91, 92, 108, 109, 110, 75, 76, 77, 93, 94, 95, 111, 112, 113] = @64) */
  for (cii=casadi_s18, rr=w56, cs=w64; cii!=casadi_s18+18; ++cii, ++cs) rr[*cii] = *cs;
  /* #764: (@56[21:129:6] = @64) */
  for (rr=w56+21, cs=w64; rr!=w56+129; rr+=6) *rr = *cs++;
  /* #765: @46 = ones(24x1,3nz) */
  casadi_fill(w46, 3, 1.);
  /* #766: {NULL, NULL, NULL, NULL, NULL, @14, @32, @16} = vertsplit(@46) */
  w14 = w46[0];
  w32 = w46[1];
  w16 = w46[2];
  /* #767: @14 = @14' */
  /* #768: @46 = mac(@14,@10,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w14), casadi_s8, wr10, casadi_s1, w46, casadi_s0, w, 0);
  /* #769: @46 = @46' */
  /* #770: @28 = mac(@14,@51,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes((&w14), casadi_s8, w51, casadi_s1, w28, casadi_s0, w, 0);
  /* #771: @28 = @28' */
  /* #772: @46 = (@46+@28) */
  for (i=0, rr=w46, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #773: @28 = (-@46) */
  for (i=0, rr=w28, cs=w46; i<3; ++i) *rr++ = (- *cs++ );
  /* #774: @53 = mac(@28,@41,@37) */
  casadi_copy(w37, 9, w53);
  for (i=0, rr=w53; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #775: @53 = (-@53) */
  for (i=0, rr=w53, cs=w53; i<9; ++i) *rr++ = (- *cs++ );
  /* #776: @28 = mac(@53,@2,@36) */
  casadi_copy(w36, 3, w28);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w53+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #777: @40 = mac(@38,@53,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #778: @40 = @40' */
  /* #779: @28 = (@28+@40) */
  for (i=0, rr=w28, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #780: @32 = @32' */
  /* #781: @40 = mac(@32,@10,@1) */
  casadi_copy(w01, 3, w40);
  casadi_mtimes((&w32), casadi_s8, wr10, casadi_s1, w40, casadi_s0, w, 0);
  /* #782: @40 = @40' */
  /* #783: @50 = mac(@32,@51,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w32), casadi_s8, w51, casadi_s1, w50, casadi_s0, w, 0);
  /* #784: @50 = @50' */
  /* #785: @40 = (@40+@50) */
  for (i=0, rr=w40, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #786: @50 = (-@40) */
  for (i=0, rr=w50, cs=w40; i<3; ++i) *rr++ = (- *cs++ );
  /* #787: @53 = mac(@50,@45,@37) */
  casadi_copy(w37, 9, w53);
  for (i=0, rr=w53; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w50+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #788: @53 = (-@53) */
  for (i=0, rr=w53, cs=w53; i<9; ++i) *rr++ = (- *cs++ );
  /* #789: @50 = mac(@53,@20,@36) */
  casadi_copy(w36, 3, w50);
  for (i=0, rr=w50; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w53+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #790: @42 = mac(@43,@53,@1) */
  casadi_copy(w01, 3, w42);
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #791: @42 = @42' */
  /* #792: @50 = (@50+@42) */
  for (i=0, rr=w50, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #793: @16 = @16' */
  /* #794: @42 = mac(@16,@10,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w16), casadi_s8, wr10, casadi_s1, w42, casadi_s0, w, 0);
  /* #795: @42 = @42' */
  /* #796: @23 = mac(@16,@51,@1) */
  casadi_copy(w01, 3, w23);
  casadi_mtimes((&w16), casadi_s8, w51, casadi_s1, w23, casadi_s0, w, 0);
  /* #797: @23 = @23' */
  /* #798: @42 = (@42+@23) */
  for (i=0, rr=w42, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #799: @23 = (-@42) */
  for (i=0, rr=w23, cs=w42; i<3; ++i) *rr++ = (- *cs++ );
  /* #800: @53 = mac(@23,@49,@37) */
  casadi_copy(w37, 9, w53);
  for (i=0, rr=w53; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w23+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #801: @53 = (-@53) */
  for (i=0, rr=w53, cs=w53; i<9; ++i) *rr++ = (- *cs++ );
  /* #802: @23 = mac(@53,@27,@36) */
  casadi_copy(w36, 3, w23);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w53+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #803: @44 = mac(@47,@53,@1) */
  casadi_copy(w01, 3, w44);
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #804: @44 = @44' */
  /* #805: @23 = (@23+@44) */
  for (i=0, rr=w23, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #806: @64 = vertcat(@60, @60, @28, @50, @23, @46, @40, @42) */
  rr=w64;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  /* #807: @63 = @64[:18] */
  for (rr=w63, cs=w64+0; cs!=w64+18; cs+=1) *rr++ = *cs;
  /* #808: (@56[78, 79, 80, 96, 97, 98, 114, 115, 116, 81, 82, 83, 99, 100, 101, 117, 118, 119] = @63) */
  for (cii=casadi_s19, rr=w56, cs=w63; cii!=casadi_s19+18; ++cii, ++cs) rr[*cii] = *cs;
  /* #809: (@56[22:130:6] = @63) */
  for (rr=w56+22, cs=w63; rr!=w56+130; rr+=6) *rr = *cs++;
  /* #810: @28 = ones(24x1,3nz) */
  casadi_fill(w28, 3, 1.);
  /* #811: {NULL, NULL, NULL, NULL, NULL, @16, @32, @14} = vertsplit(@28) */
  w16 = w28[0];
  w32 = w28[1];
  w14 = w28[2];
  /* #812: @16 = @16' */
  /* #813: @28 = mac(@16,@10,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes((&w16), casadi_s13, wr10, casadi_s1, w28, casadi_s0, w, 0);
  /* #814: @28 = @28' */
  /* #815: @50 = mac(@16,@51,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w16), casadi_s13, w51, casadi_s1, w50, casadi_s0, w, 0);
  /* #816: @50 = @50' */
  /* #817: @28 = (@28+@50) */
  for (i=0, rr=w28, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #818: @50 = (-@28) */
  for (i=0, rr=w50, cs=w28; i<3; ++i) *rr++ = (- *cs++ );
  /* #819: @53 = mac(@50,@41,@37) */
  casadi_copy(w37, 9, w53);
  for (i=0, rr=w53; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w50+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #820: @53 = (-@53) */
  for (i=0, rr=w53, cs=w53; i<9; ++i) *rr++ = (- *cs++ );
  /* #821: @50 = mac(@53,@2,@36) */
  casadi_copy(w36, 3, w50);
  for (i=0, rr=w50; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w53+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #822: @2 = mac(@38,@53,@1) */
  casadi_copy(w01, 3, w02);
  for (i=0, rr=w02; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #823: @2 = @2' */
  /* #824: @50 = (@50+@2) */
  for (i=0, rr=w50, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #825: @32 = @32' */
  /* #826: @2 = mac(@32,@10,@1) */
  casadi_copy(w01, 3, w02);
  casadi_mtimes((&w32), casadi_s13, wr10, casadi_s1, w02, casadi_s0, w, 0);
  /* #827: @2 = @2' */
  /* #828: @38 = mac(@32,@51,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w32), casadi_s13, w51, casadi_s1, w38, casadi_s0, w, 0);
  /* #829: @38 = @38' */
  /* #830: @2 = (@2+@38) */
  for (i=0, rr=w02, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #831: @38 = (-@2) */
  for (i=0, rr=w38, cs=w02; i<3; ++i) *rr++ = (- *cs++ );
  /* #832: @53 = mac(@38,@45,@37) */
  casadi_copy(w37, 9, w53);
  for (i=0, rr=w53; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w38+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #833: @53 = (-@53) */
  for (i=0, rr=w53, cs=w53; i<9; ++i) *rr++ = (- *cs++ );
  /* #834: @38 = mac(@53,@20,@36) */
  casadi_copy(w36, 3, w38);
  for (i=0, rr=w38; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w53+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #835: @20 = mac(@43,@53,@1) */
  casadi_copy(w01, 3, w20);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #836: @20 = @20' */
  /* #837: @38 = (@38+@20) */
  for (i=0, rr=w38, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #838: @14 = @14' */
  /* #839: @20 = mac(@14,@10,@1) */
  casadi_copy(w01, 3, w20);
  casadi_mtimes((&w14), casadi_s13, wr10, casadi_s1, w20, casadi_s0, w, 0);
  /* #840: @20 = @20' */
  /* #841: @43 = mac(@14,@51,@1) */
  casadi_copy(w01, 3, w43);
  casadi_mtimes((&w14), casadi_s13, w51, casadi_s1, w43, casadi_s0, w, 0);
  /* #842: @43 = @43' */
  /* #843: @20 = (@20+@43) */
  for (i=0, rr=w20, cs=w43; i<3; ++i) (*rr++) += (*cs++);
  /* #844: @43 = (-@20) */
  for (i=0, rr=w43, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #845: @37 = mac(@43,@49,@37) */
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w43+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #846: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<9; ++i) *rr++ = (- *cs++ );
  /* #847: @36 = mac(@37,@27,@36) */
  for (i=0, rr=w36; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w37+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #848: @1 = mac(@47,@37,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w37+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #849: @1 = @1' */
  /* #850: @36 = (@36+@1) */
  for (i=0, rr=w36, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #851: @63 = vertcat(@60, @60, @50, @38, @36, @28, @2, @20) */
  rr=w63;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  /* #852: @64 = @63[:18] */
  for (rr=w64, cs=w63+0; cs!=w63+18; cs+=1) *rr++ = *cs;
  /* #853: (@56[84, 85, 86, 102, 103, 104, 120, 121, 122, 87, 88, 89, 105, 106, 107, 123, 124, 125] = @64) */
  for (cii=casadi_s20, rr=w56, cs=w64; cii!=casadi_s20+18; ++cii, ++cs) rr[*cii] = *cs;
  /* #854: (@56[23:131:6] = @64) */
  for (rr=w56+23, cs=w64; rr!=w56+131; rr+=6) *rr = *cs++;
  /* #855: @65 = @56' */
  casadi_trans(w56,casadi_s21, w65, casadi_s21, iw);
  /* #856: output[2][0] = @65 */
  casadi_copy(w65, 126, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s22;
    case 1: return casadi_s23;
    case 2: return casadi_s23;
    case 3: return casadi_s24;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s25;
    case 1: return casadi_s22;
    case 2: return casadi_s21;
    case 3: return casadi_s26;
    case 4: return casadi_s27;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 25;
  if (sz_w) *sz_w = 564;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 25*sizeof(casadi_int);
  if (sz_w) *sz_w = 564*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
