/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s5[8] = {1, 3, 0, 0, 1, 2, 0, 0};
static const casadi_int casadi_s6[33] = 
  {0, 1, 2, 9, 10, 11, 18, 19,
  20, 27, 28, 29, 36, 37, 38, 45,
  46, 47, 63, 64, 65, 81, 82, 83,
  48, 49, 50, 66, 67, 68, 84, 85,
  86};
static const casadi_int casadi_s7[33] = 
  {0, 3, 6, 9, 12, 15, 18, 21,
  24, 27, 30, 33, 36, 39, 42, 45,
  51, 57, 63, 69, 75, 81, 87, 93,
  99, 105, 111, 117, 123, 129, 135, 141,
  147};
static const casadi_int casadi_s8[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s9[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s10[8] = {1, 3, 0, 1, 1, 2, 0, 0};
static const casadi_int casadi_s11[33] = 
  {3, 4, 5, 12, 13, 14, 21, 22,
  23, 30, 31, 32, 39, 40, 41, 51,
  52, 53, 69, 70, 71, 87, 88, 89,
  54, 55, 56, 72, 73, 74, 90, 91,
  92};
static const casadi_int casadi_s12[33] = 
  {1, 4, 7, 10, 13, 16, 19, 22,
  25, 28, 31, 34, 37, 40, 43, 46,
  52, 58, 64, 70, 76, 82, 88, 94,
  100, 106, 112, 118, 124, 130, 136, 142,
  148};
static const casadi_int casadi_s13[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s14[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s15[8] = {1, 3, 0, 1, 2, 2, 0, 0};
static const casadi_int casadi_s16[33] = 
  {6, 7, 8, 15, 16, 17, 24, 25,
  26, 33, 34, 35, 42, 43, 44, 57,
  58, 59, 75, 76, 77, 93, 94, 95,
  60, 61, 62, 78, 79, 80, 96, 97,
  98};
static const casadi_int casadi_s17[33] = 
  {2, 5, 8, 11, 14, 17, 20, 23,
  26, 29, 32, 35, 38, 41, 44, 47,
  53, 59, 65, 71, 77, 83, 89, 95,
  101, 107, 113, 119, 125, 131, 137, 143,
  149};
static const casadi_int casadi_s18[18] = 
  {99, 100, 101, 117, 118, 119, 135, 136,
  137, 102, 103, 104, 120, 121, 122, 138,
  139, 140};
static const casadi_int casadi_s19[18] = 
  {105, 106, 107, 123, 124, 125, 141, 142,
  143, 108, 109, 110, 126, 127, 128, 144,
  145, 146};
static const casadi_int casadi_s20[18] = 
  {111, 112, 113, 129, 130, 131, 147, 148,
  149, 114, 115, 116, 132, 133, 134, 150,
  151, 152};
static const casadi_int casadi_s21[189] = 
  {33, 33, 0, 3, 6, 9, 12, 15,
  18, 21, 24, 27, 30, 33, 36, 39,
  42, 45, 51, 57, 63, 69, 75, 81,
  87, 93, 99, 105, 111, 117, 123, 129,
  135, 141, 147, 153, 0, 1, 2, 0,
  1, 2, 0, 1, 2, 3, 4, 5,
  3, 4, 5, 3, 4, 5, 6, 7,
  8, 6, 7, 8, 6, 7, 8, 9,
  10, 11, 9, 10, 11, 9, 10, 11,
  12, 13, 14, 12, 13, 14, 12, 13,
  14, 15, 16, 17, 24, 25, 26, 15,
  16, 17, 24, 25, 26, 15, 16, 17,
  24, 25, 26, 18, 19, 20, 27, 28,
  29, 18, 19, 20, 27, 28, 29, 18,
  19, 20, 27, 28, 29, 21, 22, 23,
  30, 31, 32, 21, 22, 23, 30, 31,
  32, 21, 22, 23, 30, 31, 32, 15,
  16, 17, 24, 25, 26, 15, 16, 17,
  24, 25, 26, 15, 16, 17, 24, 25,
  26, 18, 19, 20, 27, 28, 29, 18,
  19, 20, 27, 28, 29, 18, 19, 20,
  27, 28, 29, 21, 22, 23, 30, 31,
  32, 21, 22, 23, 30, 31, 32, 21,
  22, 23, 30, 31, 32};
static const casadi_int casadi_s22[3] = {24, 1, 1};
static const casadi_int casadi_s23[3] = {9, 1, 1};
static const casadi_int casadi_s24[3] = {0, 1, 1};
static const casadi_int casadi_s25[3] = {33, 1, 1};
static const casadi_int casadi_s26[3] = {1, 1, 1};
static const casadi_int casadi_s27[3] = {0, 0, 1};
static const casadi_int casadi_s28[3] = {0, 33, 1};

static const casadi_real casadi_c0[9] = 
  {250., 0., 0., 0., 250., 0., 0., 0.,
  250.};
static const casadi_real casadi_c1[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c2[9] = 
  {30., 0., 0., 0., 30., 0., 0., 0.,
  30.};
static const casadi_real casadi_c3[9] = 
  {1.0000000000000001e-01, 0., 0., 0., 1.0000000000000001e-01, 0., 0., 0.,
  1.0000000000000001e-01};

static const casadi_real casadi_zeros[33] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess:(i0[24],i1[9],i2[0],i3[33])->(o0,o1[33],o2[33x33,153nz],o3[],o4[0x33]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+4, *w02=w+7, *w03=w+10, *w04=w+43, *w05=w+46, *w06=w+55, w07, w08, *w09=w+60, *w11=w+72;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+83, *w21=w+86, *w23=w+98, w24;
  casadi_real w25, w26, *w27=w+104, *w28=w+107, *w29=w+110, w30, w31, w32, *w33=w+116, *w34=w+119, *w35=w+122, *w36=w+125;
  casadi_real *w37=w+128, *w38=w+137, *w39=w+140, *w40=w+149, *w41=w+152, *w42=w+155, *w43=w+158, *w44=w+161, *w45=w+164, *w46=w+167, *w47=w+170, *w48=w+173;
  casadi_real *w49=w+176, *w50=w+179, *w51=w+182, *w52=w+185, *w53=w+188, *w54=w+191, *w55=w+194, *w56=w+197, *w57=w+200, *w58=w+209, *w59=w+218, *w60=w+227;
  casadi_real *w61=w+236, *w62=w+245, *w63=w+254, *w64=w+263, *w65=w+416, w66, *w67=w+425, *w68=w+434, *w70=w+443, *w71=w+445, *w72=w+463, *w73=w+481;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr03, *wr04, *wr05, *wr09, *wr10, *wr22, *wr39, *wr40, *wr41;
  const casadi_real *wr44, *wr45, *wr48, *wr49;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[:3] */
  wr04 = wr03+0;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = @2' */
  casadi_copy(w02, 3, w04);
  /* #7: @5 = 
  [[250, 0, 0], 
   [0, 250, 0], 
   [0, 0, 250]] */
  wr05 = casadi_c0;
  /* #8: @6 = mac(@4,@5,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w04+j, ct=wr05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #9: @7 = mac(@6,@2,@0) */
  casadi_copy((&w00), 1, (&w07));
  for (i=0, rr=(&w07); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #10: @8 = 0.2 */
  w08 = 2.0000000000000001e-01;
  /* #11: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w02);
  /* #12: @9 = @3[3:6] */
  wr09 = wr03+3;
  /* #13: @2 = (@2-@9) */
  for (i=0, rr=w02, cs=wr09; i<3; ++i) (*rr++) -= (*cs++);
  /* #14: @9 = @2' */
  casadi_copy(w02, 3, w09);
  /* #15: @10 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr10 = casadi_c1;
  /* #16: @11 = mac(@9,@10,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #17: @12 = mac(@11,@2,@0) */
  casadi_copy((&w00), 1, (&w12));
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #18: @12 = (@8*@12) */
  w12  = (w08*w12);
  /* #19: @7 = (@7+@12) */
  w07 += w12;
  /* #20: @12 = @3[7] */
  w12 = wr03[7];
  /* #21: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w02);
  /* #22: @13 = @2[2] */
  for (rr=(&w13), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #23: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #24: @15 = @3[8] */
  w15 = wr03[8];
  /* #25: @16 = @2[1] */
  for (rr=(&w16), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #26: @17 = (@15*@16) */
  w17  = (w15*w16);
  /* #27: @14 = (@14-@17) */
  w14 -= w17;
  /* #28: @17 = @2[0] */
  for (rr=(&w17), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #29: @18 = (@15*@17) */
  w18  = (w15*w17);
  /* #30: @19 = @3[6] */
  w19 = wr03[6];
  /* #31: @13 = (@19*@13) */
  w13  = (w19*w13);
  /* #32: @18 = (@18-@13) */
  w18 -= w13;
  /* #33: @16 = (@19*@16) */
  w16  = (w19*w16);
  /* #34: @17 = (@12*@17) */
  w17  = (w12*w17);
  /* #35: @16 = (@16-@17) */
  w16 -= w17;
  /* #36: @20 = vertcat(@14, @18, @16) */
  rr=w20;
  *rr++ = w14;
  *rr++ = w18;
  *rr++ = w16;
  /* #37: @21 = @20' */
  casadi_copy(w20, 3, w21);
  /* #38: @22 = 
  [[30, 0, 0], 
   [0, 30, 0], 
   [0, 0, 30]] */
  wr22 = casadi_c2;
  /* #39: @23 = mac(@21,@22,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=wr22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @14 = mac(@23,@20,@0) */
  casadi_copy((&w00), 1, (&w14));
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @7 = (@7+@14) */
  w07 += w14;
  /* #42: @14 = @3[10] */
  w14 = wr03[10];
  /* #43: @20 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+9 : 0, 3, w20);
  /* #44: @18 = @20[2] */
  for (rr=(&w18), cs=w20+2; cs!=w20+3; cs+=1) *rr++ = *cs;
  /* #45: @16 = (@14*@18) */
  w16  = (w14*w18);
  /* #46: @17 = @3[11] */
  w17 = wr03[11];
  /* #47: @13 = @20[1] */
  for (rr=(&w13), cs=w20+1; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #48: @24 = (@17*@13) */
  w24  = (w17*w13);
  /* #49: @16 = (@16-@24) */
  w16 -= w24;
  /* #50: @24 = @20[0] */
  for (rr=(&w24), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #51: @25 = (@17*@24) */
  w25  = (w17*w24);
  /* #52: @26 = @3[9] */
  w26 = wr03[9];
  /* #53: @18 = (@26*@18) */
  w18  = (w26*w18);
  /* #54: @25 = (@25-@18) */
  w25 -= w18;
  /* #55: @13 = (@26*@13) */
  w13  = (w26*w13);
  /* #56: @24 = (@14*@24) */
  w24  = (w14*w24);
  /* #57: @13 = (@13-@24) */
  w13 -= w24;
  /* #58: @27 = vertcat(@16, @25, @13) */
  rr=w27;
  *rr++ = w16;
  *rr++ = w25;
  *rr++ = w13;
  /* #59: @28 = @27' */
  casadi_copy(w27, 3, w28);
  /* #60: @29 = mac(@28,@22,@1) */
  casadi_copy(w01, 3, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=wr22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #61: @16 = mac(@29,@27,@0) */
  casadi_copy((&w00), 1, (&w16));
  for (i=0, rr=(&w16); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #62: @7 = (@7+@16) */
  w07 += w16;
  /* #63: @16 = @3[13] */
  w16 = wr03[13];
  /* #64: @27 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+12 : 0, 3, w27);
  /* #65: @25 = @27[2] */
  for (rr=(&w25), cs=w27+2; cs!=w27+3; cs+=1) *rr++ = *cs;
  /* #66: @13 = (@16*@25) */
  w13  = (w16*w25);
  /* #67: @24 = @3[14] */
  w24 = wr03[14];
  /* #68: @18 = @27[1] */
  for (rr=(&w18), cs=w27+1; cs!=w27+2; cs+=1) *rr++ = *cs;
  /* #69: @30 = (@24*@18) */
  w30  = (w24*w18);
  /* #70: @13 = (@13-@30) */
  w13 -= w30;
  /* #71: @30 = @27[0] */
  for (rr=(&w30), cs=w27+0; cs!=w27+1; cs+=1) *rr++ = *cs;
  /* #72: @31 = (@24*@30) */
  w31  = (w24*w30);
  /* #73: @32 = @3[12] */
  w32 = wr03[12];
  /* #74: @25 = (@32*@25) */
  w25  = (w32*w25);
  /* #75: @31 = (@31-@25) */
  w31 -= w25;
  /* #76: @18 = (@32*@18) */
  w18  = (w32*w18);
  /* #77: @30 = (@16*@30) */
  w30  = (w16*w30);
  /* #78: @18 = (@18-@30) */
  w18 -= w30;
  /* #79: @33 = vertcat(@13, @31, @18) */
  rr=w33;
  *rr++ = w13;
  *rr++ = w31;
  *rr++ = w18;
  /* #80: @34 = @33' */
  casadi_copy(w33, 3, w34);
  /* #81: @35 = mac(@34,@22,@1) */
  casadi_copy(w01, 3, w35);
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=wr22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #82: @13 = mac(@35,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #83: @7 = (@7+@13) */
  w07 += w13;
  /* #84: @33 = input[0][5] */
  casadi_copy(arg[0] ? arg[0]+15 : 0, 3, w33);
  /* #85: @36 = zeros(3x1) */
  casadi_clear(w36, 3);
  /* #86: @37 = zeros(3x3) */
  casadi_clear(w37, 9);
  /* #87: @38 = @2' */
  casadi_copy(w02, 3, w38);
  /* #88: @39 = mac(@2,@38,@37) */
  casadi_copy(w37, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w02+j, ct=w38+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #89: @39 = (@10-@39) */
  for (i=0, rr=w39, cr=wr10, cs=w39; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #90: @40 = @3[15:18] */
  wr40 = wr03+15;
  /* #91: @41 = mac(@39,@40,@36) */
  casadi_copy(w36, 3, w41);
  for (i=0, rr=w41; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=wr40+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #92: @33 = (@33-@41) */
  for (i=0, rr=w33, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #93: @41 = @33' */
  casadi_copy(w33, 3, w41);
  /* #94: @42 = mac(@41,@10,@1) */
  casadi_copy(w01, 3, w42);
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #95: @13 = mac(@42,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w42+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #96: @7 = (@7+@13) */
  w07 += w13;
  /* #97: @33 = input[0][6] */
  casadi_copy(arg[0] ? arg[0]+18 : 0, 3, w33);
  /* #98: @43 = @20' */
  casadi_copy(w20, 3, w43);
  /* #99: @39 = mac(@20,@43,@37) */
  casadi_copy(w37, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w20+j, ct=w43+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #100: @39 = (@10-@39) */
  for (i=0, rr=w39, cr=wr10, cs=w39; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #101: @44 = @3[18:21] */
  wr44 = wr03+18;
  /* #102: @45 = mac(@39,@44,@36) */
  casadi_copy(w36, 3, w45);
  for (i=0, rr=w45; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=wr44+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #103: @33 = (@33-@45) */
  for (i=0, rr=w33, cs=w45; i<3; ++i) (*rr++) -= (*cs++);
  /* #104: @45 = @33' */
  casadi_copy(w33, 3, w45);
  /* #105: @46 = mac(@45,@10,@1) */
  casadi_copy(w01, 3, w46);
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w45+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #106: @13 = mac(@46,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w46+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #107: @7 = (@7+@13) */
  w07 += w13;
  /* #108: @33 = input[0][7] */
  casadi_copy(arg[0] ? arg[0]+21 : 0, 3, w33);
  /* #109: @47 = @27' */
  casadi_copy(w27, 3, w47);
  /* #110: @39 = mac(@27,@47,@37) */
  casadi_copy(w37, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w47+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #111: @39 = (@10-@39) */
  for (i=0, rr=w39, cr=wr10, cs=w39; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #112: @48 = @3[21:24] */
  wr48 = wr03+21;
  /* #113: @49 = mac(@39,@48,@36) */
  casadi_copy(w36, 3, w49);
  for (i=0, rr=w49; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=wr48+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #114: @33 = (@33-@49) */
  for (i=0, rr=w33, cs=w49; i<3; ++i) (*rr++) -= (*cs++);
  /* #115: @49 = @33' */
  casadi_copy(w33, 3, w49);
  /* #116: @50 = mac(@49,@10,@1) */
  casadi_copy(w01, 3, w50);
  for (i=0, rr=w50; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w49+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #117: @13 = mac(@50,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w50+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #118: @7 = (@7+@13) */
  w07 += w13;
  /* #119: @33 = input[1][0] */
  casadi_copy(arg[1], 3, w33);
  /* #120: @51 = @33' */
  casadi_copy(w33, 3, w51);
  /* #121: @39 = 
  [[0.1, 0, 0], 
   [0, 0.1, 0], 
   [0, 0, 0.1]] */
  wr39 = casadi_c3;
  /* #122: @52 = mac(@51,@39,@1) */
  casadi_copy(w01, 3, w52);
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w51+j, ct=wr39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #123: @13 = mac(@52,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w52+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #124: @7 = (@7+@13) */
  w07 += w13;
  /* #125: @33 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+3 : 0, 3, w33);
  /* #126: @53 = @33' */
  casadi_copy(w33, 3, w53);
  /* #127: @54 = mac(@53,@39,@1) */
  casadi_copy(w01, 3, w54);
  for (i=0, rr=w54; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w53+j, ct=wr39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #128: @13 = mac(@54,@33,@0) */
  casadi_copy((&w00), 1, (&w13));
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w54+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #129: @7 = (@7+@13) */
  w07 += w13;
  /* #130: @33 = input[1][2] */
  casadi_copy(arg[1] ? arg[1]+6 : 0, 3, w33);
  /* #131: @55 = @33' */
  casadi_copy(w33, 3, w55);
  /* #132: @56 = mac(@55,@39,@1) */
  casadi_copy(w01, 3, w56);
  for (i=0, rr=w56; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w55+j, ct=wr39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #133: @0 = mac(@56,@33,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w56+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #134: @7 = (@7+@0) */
  w07 += w00;
  /* #135: output[0][0] = @7 */
  if (res[0]) res[0][0] = w07;
  /* #136: @52 = @52' */
  /* #137: @57 = @39' */
  for (i=0, rr=w57, cs=wr39; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #138: @33 = mac(@51,@57,@1) */
  casadi_copy(w01, 3, w33);
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w51+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #139: @33 = @33' */
  /* #140: @52 = (@52+@33) */
  for (i=0, rr=w52, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #141: output[1][0] = @52 */
  casadi_copy(w52, 3, res[1]);
  /* #142: @54 = @54' */
  /* #143: @52 = mac(@53,@57,@1) */
  casadi_copy(w01, 3, w52);
  for (i=0, rr=w52; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w53+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #144: @52 = @52' */
  /* #145: @54 = (@54+@52) */
  for (i=0, rr=w54, cs=w52; i<3; ++i) (*rr++) += (*cs++);
  /* #146: output[1][1] = @54 */
  if (res[1]) casadi_copy(w54, 3, res[1]+3);
  /* #147: @56 = @56' */
  /* #148: @54 = mac(@55,@57,@1) */
  casadi_copy(w01, 3, w54);
  for (i=0, rr=w54; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w55+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #149: @54 = @54' */
  /* #150: @56 = (@56+@54) */
  for (i=0, rr=w56, cs=w54; i<3; ++i) (*rr++) += (*cs++);
  /* #151: output[1][2] = @56 */
  if (res[1]) casadi_copy(w56, 3, res[1]+6);
  /* #152: @6 = @6' */
  /* #153: @58 = @5' */
  for (i=0, rr=w58, cs=wr05; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #154: @56 = mac(@4,@58,@1) */
  casadi_copy(w01, 3, w56);
  for (i=0, rr=w56; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w04+j, ct=w58+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #155: @56 = @56' */
  /* #156: @6 = (@6+@56) */
  for (i=0, rr=w06, cs=w56; i<3; ++i) (*rr++) += (*cs++);
  /* #157: output[1][3] = @6 */
  if (res[1]) casadi_copy(w06, 3, res[1]+9);
  /* #158: @11 = @11' */
  /* #159: @11 = (@8*@11) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #160: @9 = (@8*@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #161: @59 = @10' */
  for (i=0, rr=w59, cs=wr10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #162: @6 = mac(@9,@59,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #163: @6 = @6' */
  /* #164: @11 = (@11+@6) */
  for (i=0, rr=w11, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #165: output[1][4] = @11 */
  if (res[1]) casadi_copy(w11, 3, res[1]+12);
  /* #166: @42 = @42' */
  /* #167: @11 = mac(@41,@59,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #168: @11 = @11' */
  /* #169: @42 = (@42+@11) */
  for (i=0, rr=w42, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #170: @11 = (-@42) */
  for (i=0, rr=w11, cs=w42; i<3; ++i) *rr++ = (- *cs++ );
  /* #171: @41 = @40' */
  wr41 = wr40;
  /* #172: @60 = mac(@11,@41,@37) */
  casadi_copy(w37, 9, w60);
  for (i=0, rr=w60; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #173: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<9; ++i) *rr++ = (- *cs++ );
  /* #174: @11 = mac(@60,@2,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w60+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #175: @6 = mac(@38,@60,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w60+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #176: @6 = @6' */
  /* #177: @11 = (@11+@6) */
  for (i=0, rr=w11, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #178: @23 = @23' */
  /* #179: @61 = @22' */
  for (i=0, rr=w61, cs=wr22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #180: @6 = mac(@21,@61,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #181: @6 = @6' */
  /* #182: @23 = (@23+@6) */
  for (i=0, rr=w23, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #183: {@7, @0, @13} = vertsplit(@23) */
  w07 = w23[0];
  w00 = w23[1];
  w13 = w23[2];
  /* #184: @31 = (@15*@0) */
  w31  = (w15*w00);
  /* #185: @18 = (@12*@13) */
  w18  = (w12*w13);
  /* #186: @31 = (@31-@18) */
  w31 -= w18;
  /* #187: (@11[0] += @31) */
  for (rr=w11+0, cs=(&w31); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #188: @13 = (@19*@13) */
  w13  = (w19*w13);
  /* #189: @31 = (@15*@7) */
  w31  = (w15*w07);
  /* #190: @13 = (@13-@31) */
  w13 -= w31;
  /* #191: (@11[1] += @13) */
  for (rr=w11+1, cs=(&w13); rr!=w11+2; rr+=1) *rr += *cs++;
  /* #192: @7 = (@12*@7) */
  w07  = (w12*w07);
  /* #193: @0 = (@19*@0) */
  w00  = (w19*w00);
  /* #194: @7 = (@7-@0) */
  w07 -= w00;
  /* #195: (@11[2] += @7) */
  for (rr=w11+2, cs=(&w07); rr!=w11+3; rr+=1) *rr += *cs++;
  /* #196: output[1][5] = @11 */
  if (res[1]) casadi_copy(w11, 3, res[1]+15);
  /* #197: @46 = @46' */
  /* #198: @11 = mac(@45,@59,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w45+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #199: @11 = @11' */
  /* #200: @46 = (@46+@11) */
  for (i=0, rr=w46, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #201: @11 = (-@46) */
  for (i=0, rr=w11, cs=w46; i<3; ++i) *rr++ = (- *cs++ );
  /* #202: @45 = @44' */
  wr45 = wr44;
  /* #203: @62 = mac(@11,@45,@37) */
  casadi_copy(w37, 9, w62);
  for (i=0, rr=w62; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #204: @62 = (-@62) */
  for (i=0, rr=w62, cs=w62; i<9; ++i) *rr++ = (- *cs++ );
  /* #205: @11 = mac(@62,@20,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w62+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #206: @23 = mac(@43,@62,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w62+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #207: @23 = @23' */
  /* #208: @11 = (@11+@23) */
  for (i=0, rr=w11, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #209: @29 = @29' */
  /* #210: @23 = mac(@28,@61,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #211: @23 = @23' */
  /* #212: @29 = (@29+@23) */
  for (i=0, rr=w29, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #213: {@7, @0, @13} = vertsplit(@29) */
  w07 = w29[0];
  w00 = w29[1];
  w13 = w29[2];
  /* #214: @31 = (@17*@0) */
  w31  = (w17*w00);
  /* #215: @18 = (@14*@13) */
  w18  = (w14*w13);
  /* #216: @31 = (@31-@18) */
  w31 -= w18;
  /* #217: (@11[0] += @31) */
  for (rr=w11+0, cs=(&w31); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #218: @13 = (@26*@13) */
  w13  = (w26*w13);
  /* #219: @31 = (@17*@7) */
  w31  = (w17*w07);
  /* #220: @13 = (@13-@31) */
  w13 -= w31;
  /* #221: (@11[1] += @13) */
  for (rr=w11+1, cs=(&w13); rr!=w11+2; rr+=1) *rr += *cs++;
  /* #222: @7 = (@14*@7) */
  w07  = (w14*w07);
  /* #223: @0 = (@26*@0) */
  w00  = (w26*w00);
  /* #224: @7 = (@7-@0) */
  w07 -= w00;
  /* #225: (@11[2] += @7) */
  for (rr=w11+2, cs=(&w07); rr!=w11+3; rr+=1) *rr += *cs++;
  /* #226: output[1][6] = @11 */
  if (res[1]) casadi_copy(w11, 3, res[1]+18);
  /* #227: @50 = @50' */
  /* #228: @11 = mac(@49,@59,@1) */
  casadi_copy(w01, 3, w11);
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w49+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #229: @11 = @11' */
  /* #230: @50 = (@50+@11) */
  for (i=0, rr=w50, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #231: @11 = (-@50) */
  for (i=0, rr=w11, cs=w50; i<3; ++i) *rr++ = (- *cs++ );
  /* #232: @49 = @48' */
  wr49 = wr48;
  /* #233: @63 = mac(@11,@49,@37) */
  casadi_copy(w37, 9, w63);
  for (i=0, rr=w63; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #234: @63 = (-@63) */
  for (i=0, rr=w63, cs=w63; i<9; ++i) *rr++ = (- *cs++ );
  /* #235: @11 = mac(@63,@27,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w63+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #236: @29 = mac(@47,@63,@1) */
  casadi_copy(w01, 3, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w63+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #237: @29 = @29' */
  /* #238: @11 = (@11+@29) */
  for (i=0, rr=w11, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #239: @35 = @35' */
  /* #240: @29 = mac(@34,@61,@1) */
  casadi_copy(w01, 3, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #241: @29 = @29' */
  /* #242: @35 = (@35+@29) */
  for (i=0, rr=w35, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #243: {@7, @0, @13} = vertsplit(@35) */
  w07 = w35[0];
  w00 = w35[1];
  w13 = w35[2];
  /* #244: @31 = (@24*@0) */
  w31  = (w24*w00);
  /* #245: @18 = (@16*@13) */
  w18  = (w16*w13);
  /* #246: @31 = (@31-@18) */
  w31 -= w18;
  /* #247: (@11[0] += @31) */
  for (rr=w11+0, cs=(&w31); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #248: @13 = (@32*@13) */
  w13  = (w32*w13);
  /* #249: @31 = (@24*@7) */
  w31  = (w24*w07);
  /* #250: @13 = (@13-@31) */
  w13 -= w31;
  /* #251: (@11[1] += @13) */
  for (rr=w11+1, cs=(&w13); rr!=w11+2; rr+=1) *rr += *cs++;
  /* #252: @7 = (@16*@7) */
  w07  = (w16*w07);
  /* #253: @0 = (@32*@0) */
  w00  = (w32*w00);
  /* #254: @7 = (@7-@0) */
  w07 -= w00;
  /* #255: (@11[2] += @7) */
  for (rr=w11+2, cs=(&w07); rr!=w11+3; rr+=1) *rr += *cs++;
  /* #256: output[1][7] = @11 */
  if (res[1]) casadi_copy(w11, 3, res[1]+21);
  /* #257: output[1][8] = @42 */
  if (res[1]) casadi_copy(w42, 3, res[1]+24);
  /* #258: output[1][9] = @46 */
  if (res[1]) casadi_copy(w46, 3, res[1]+27);
  /* #259: output[1][10] = @50 */
  if (res[1]) casadi_copy(w50, 3, res[1]+30);
  /* #260: @64 = zeros(33x33,153nz) */
  casadi_clear(w64, 153);
  /* #261: @65 = ones(33x1,8nz) */
  casadi_fill(w65, 8, 1.);
  /* #262: {@7, @0, @13, @31, @18, @30, @25, @66, NULL, NULL, NULL} = vertsplit(@65) */
  w07 = w65[0];
  w00 = w65[1];
  w13 = w65[2];
  w31 = w65[3];
  w18 = w65[4];
  w30 = w65[5];
  w25 = w65[6];
  w66 = w65[7];
  /* #263: @7 = @7' */
  /* #264: @50 = mac(@7,@39,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w07), casadi_s2, wr39, casadi_s1, w50, casadi_s0, w, 0);
  /* #265: @50 = @50' */
  /* #266: @46 = mac(@7,@57,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w07), casadi_s2, w57, casadi_s1, w46, casadi_s0, w, 0);
  /* #267: @46 = @46' */
  /* #268: @50 = (@50+@46) */
  for (i=0, rr=w50, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #269: @0 = @0' */
  /* #270: @46 = mac(@0,@39,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w00), casadi_s2, wr39, casadi_s1, w46, casadi_s0, w, 0);
  /* #271: @46 = @46' */
  /* #272: @42 = mac(@0,@57,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w00), casadi_s2, w57, casadi_s1, w42, casadi_s0, w, 0);
  /* #273: @42 = @42' */
  /* #274: @46 = (@46+@42) */
  for (i=0, rr=w46, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #275: @13 = @13' */
  /* #276: @42 = mac(@13,@39,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w13), casadi_s2, wr39, casadi_s1, w42, casadi_s0, w, 0);
  /* #277: @42 = @42' */
  /* #278: @11 = mac(@13,@57,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w13), casadi_s2, w57, casadi_s1, w11, casadi_s0, w, 0);
  /* #279: @11 = @11' */
  /* #280: @42 = (@42+@11) */
  for (i=0, rr=w42, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #281: @31 = @31' */
  /* #282: @11 = mac(@31,@5,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w31), casadi_s2, wr05, casadi_s1, w11, casadi_s0, w, 0);
  /* #283: @11 = @11' */
  /* #284: @35 = mac(@31,@58,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes((&w31), casadi_s2, w58, casadi_s1, w35, casadi_s0, w, 0);
  /* #285: @35 = @35' */
  /* #286: @11 = (@11+@35) */
  for (i=0, rr=w11, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #287: @18 = @18' */
  /* #288: @35 = mac(@18,@10,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes((&w18), casadi_s2, wr10, casadi_s1, w35, casadi_s0, w, 0);
  /* #289: @35 = @35' */
  /* #290: @35 = (@8*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #291: @18 = (@8*@18) */
  w18  = (w08*w18);
  /* #292: @29 = mac(@18,@59,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes((&w18), casadi_s2, w59, casadi_s1, w29, casadi_s0, w, 0);
  /* #293: @29 = @29' */
  /* #294: @35 = (@35+@29) */
  for (i=0, rr=w35, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #295: @29 = mac(@60,@30,@36) */
  casadi_copy(w36, 3, w29);
  casadi_mtimes(w60, casadi_s1, (&w30), casadi_s4, w29, casadi_s3, w, 0);
  /* #296: @18 = @30' */
  w18 = w30;
  /* #297: @67 = mac(@2,@18,@37) */
  casadi_copy(w37, 9, w67);
  casadi_mtimes(w02, casadi_s3, (&w18), casadi_s2, w67, casadi_s1, w, 0);
  /* #298: @68 = mac(@30,@38,@37) */
  casadi_copy(w37, 9, w68);
  casadi_mtimes((&w30), casadi_s4, w38, casadi_s0, w68, casadi_s1, w, 0);
  /* #299: @67 = (@67+@68) */
  for (i=0, rr=w67, cs=w68; i<9; ++i) (*rr++) += (*cs++);
  /* #300: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #301: @34 = mac(@67,@40,@36) */
  casadi_copy(w36, 3, w34);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=wr40+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #302: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #303: @34 = @34' */
  /* #304: @23 = mac(@34,@10,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #305: @23 = @23' */
  /* #306: @28 = mac(@34,@59,@1) */
  casadi_copy(w01, 3, w28);
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #307: @28 = @28' */
  /* #308: @23 = (@23+@28) */
  for (i=0, rr=w23, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #309: @28 = (-@23) */
  for (i=0, rr=w28, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #310: @67 = mac(@28,@41,@37) */
  casadi_copy(w37, 9, w67);
  for (i=0, rr=w67; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #311: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #312: @28 = mac(@67,@2,@36) */
  casadi_copy(w36, 3, w28);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #313: @29 = (@29+@28) */
  for (i=0, rr=w29, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #314: @28 = mac(@38,@67,@1) */
  casadi_copy(w01, 3, w28);
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w67+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #315: @34 = mac(@18,@60,@1) */
  casadi_copy(w01, 3, w34);
  casadi_mtimes((&w18), casadi_s2, w60, casadi_s1, w34, casadi_s0, w, 0);
  /* #316: @28 = (@28+@34) */
  for (i=0, rr=w28, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #317: @28 = @28' */
  /* #318: @29 = (@29+@28) */
  for (i=0, rr=w29, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #319: @69 = 00 */
  /* #320: @18 = @30[0] */
  for (rr=(&w18), cs=(&w30)+0; cs!=(&w30)+1; cs+=1) *rr++ = *cs;
  /* #321: @30 = (@15*@18) */
  w30  = (w15*w18);
  /* #322: @18 = (@12*@18) */
  w18  = (w12*w18);
  /* #323: @18 = (-@18) */
  w18 = (- w18 );
  /* #324: @70 = vertcat(@69, @30, @18) */
  rr=w70;
  *rr++ = w30;
  *rr++ = w18;
  /* #325: @70 = @70' */
  /* #326: @28 = mac(@70,@22,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes(w70, casadi_s5, wr22, casadi_s1, w28, casadi_s0, w, 0);
  /* #327: @28 = @28' */
  /* #328: @34 = mac(@70,@61,@1) */
  casadi_copy(w01, 3, w34);
  casadi_mtimes(w70, casadi_s5, w61, casadi_s1, w34, casadi_s0, w, 0);
  /* #329: @34 = @34' */
  /* #330: @28 = (@28+@34) */
  for (i=0, rr=w28, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #331: {@30, @18, @31} = vertsplit(@28) */
  w30 = w28[0];
  w18 = w28[1];
  w31 = w28[2];
  /* #332: @13 = (@15*@18) */
  w13  = (w15*w18);
  /* #333: @0 = (@12*@31) */
  w00  = (w12*w31);
  /* #334: @13 = (@13-@0) */
  w13 -= w00;
  /* #335: (@29[0] += @13) */
  for (rr=w29+0, cs=(&w13); rr!=w29+1; rr+=1) *rr += *cs++;
  /* #336: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #337: @13 = (@15*@30) */
  w13  = (w15*w30);
  /* #338: @31 = (@31-@13) */
  w31 -= w13;
  /* #339: (@29[1] += @31) */
  for (rr=w29+1, cs=(&w31); rr!=w29+2; rr+=1) *rr += *cs++;
  /* #340: @30 = (@12*@30) */
  w30  = (w12*w30);
  /* #341: @18 = (@19*@18) */
  w18  = (w19*w18);
  /* #342: @30 = (@30-@18) */
  w30 -= w18;
  /* #343: (@29[2] += @30) */
  for (rr=w29+2, cs=(&w30); rr!=w29+3; rr+=1) *rr += *cs++;
  /* #344: @28 = mac(@62,@25,@36) */
  casadi_copy(w36, 3, w28);
  casadi_mtimes(w62, casadi_s1, (&w25), casadi_s4, w28, casadi_s3, w, 0);
  /* #345: @30 = @25' */
  w30 = w25;
  /* #346: @67 = mac(@20,@30,@37) */
  casadi_copy(w37, 9, w67);
  casadi_mtimes(w20, casadi_s3, (&w30), casadi_s2, w67, casadi_s1, w, 0);
  /* #347: @68 = mac(@25,@43,@37) */
  casadi_copy(w37, 9, w68);
  casadi_mtimes((&w25), casadi_s4, w43, casadi_s0, w68, casadi_s1, w, 0);
  /* #348: @67 = (@67+@68) */
  for (i=0, rr=w67, cs=w68; i<9; ++i) (*rr++) += (*cs++);
  /* #349: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #350: @34 = mac(@67,@44,@36) */
  casadi_copy(w36, 3, w34);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=wr44+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #351: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #352: @34 = @34' */
  /* #353: @6 = mac(@34,@10,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #354: @6 = @6' */
  /* #355: @21 = mac(@34,@59,@1) */
  casadi_copy(w01, 3, w21);
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #356: @21 = @21' */
  /* #357: @6 = (@6+@21) */
  for (i=0, rr=w06, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #358: @21 = (-@6) */
  for (i=0, rr=w21, cs=w06; i<3; ++i) *rr++ = (- *cs++ );
  /* #359: @67 = mac(@21,@45,@37) */
  casadi_copy(w37, 9, w67);
  for (i=0, rr=w67; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #360: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #361: @21 = mac(@67,@20,@36) */
  casadi_copy(w36, 3, w21);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #362: @28 = (@28+@21) */
  for (i=0, rr=w28, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #363: @21 = mac(@43,@67,@1) */
  casadi_copy(w01, 3, w21);
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w67+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #364: @34 = mac(@30,@62,@1) */
  casadi_copy(w01, 3, w34);
  casadi_mtimes((&w30), casadi_s2, w62, casadi_s1, w34, casadi_s0, w, 0);
  /* #365: @21 = (@21+@34) */
  for (i=0, rr=w21, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #366: @21 = @21' */
  /* #367: @28 = (@28+@21) */
  for (i=0, rr=w28, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #368: @30 = @25[0] */
  for (rr=(&w30), cs=(&w25)+0; cs!=(&w25)+1; cs+=1) *rr++ = *cs;
  /* #369: @25 = (@17*@30) */
  w25  = (w17*w30);
  /* #370: @30 = (@14*@30) */
  w30  = (w14*w30);
  /* #371: @30 = (-@30) */
  w30 = (- w30 );
  /* #372: @70 = vertcat(@69, @25, @30) */
  rr=w70;
  *rr++ = w25;
  *rr++ = w30;
  /* #373: @70 = @70' */
  /* #374: @21 = mac(@70,@22,@1) */
  casadi_copy(w01, 3, w21);
  casadi_mtimes(w70, casadi_s5, wr22, casadi_s1, w21, casadi_s0, w, 0);
  /* #375: @21 = @21' */
  /* #376: @34 = mac(@70,@61,@1) */
  casadi_copy(w01, 3, w34);
  casadi_mtimes(w70, casadi_s5, w61, casadi_s1, w34, casadi_s0, w, 0);
  /* #377: @34 = @34' */
  /* #378: @21 = (@21+@34) */
  for (i=0, rr=w21, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #379: {@25, @30, @18} = vertsplit(@21) */
  w25 = w21[0];
  w30 = w21[1];
  w18 = w21[2];
  /* #380: @31 = (@17*@30) */
  w31  = (w17*w30);
  /* #381: @13 = (@14*@18) */
  w13  = (w14*w18);
  /* #382: @31 = (@31-@13) */
  w31 -= w13;
  /* #383: (@28[0] += @31) */
  for (rr=w28+0, cs=(&w31); rr!=w28+1; rr+=1) *rr += *cs++;
  /* #384: @18 = (@26*@18) */
  w18  = (w26*w18);
  /* #385: @31 = (@17*@25) */
  w31  = (w17*w25);
  /* #386: @18 = (@18-@31) */
  w18 -= w31;
  /* #387: (@28[1] += @18) */
  for (rr=w28+1, cs=(&w18); rr!=w28+2; rr+=1) *rr += *cs++;
  /* #388: @25 = (@14*@25) */
  w25  = (w14*w25);
  /* #389: @30 = (@26*@30) */
  w30  = (w26*w30);
  /* #390: @25 = (@25-@30) */
  w25 -= w30;
  /* #391: (@28[2] += @25) */
  for (rr=w28+2, cs=(&w25); rr!=w28+3; rr+=1) *rr += *cs++;
  /* #392: @21 = mac(@63,@66,@36) */
  casadi_copy(w36, 3, w21);
  casadi_mtimes(w63, casadi_s1, (&w66), casadi_s4, w21, casadi_s3, w, 0);
  /* #393: @25 = @66' */
  w25 = w66;
  /* #394: @67 = mac(@27,@25,@37) */
  casadi_copy(w37, 9, w67);
  casadi_mtimes(w27, casadi_s3, (&w25), casadi_s2, w67, casadi_s1, w, 0);
  /* #395: @68 = mac(@66,@47,@37) */
  casadi_copy(w37, 9, w68);
  casadi_mtimes((&w66), casadi_s4, w47, casadi_s0, w68, casadi_s1, w, 0);
  /* #396: @67 = (@67+@68) */
  for (i=0, rr=w67, cs=w68; i<9; ++i) (*rr++) += (*cs++);
  /* #397: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #398: @34 = mac(@67,@48,@36) */
  casadi_copy(w36, 3, w34);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=wr48+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #399: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #400: @34 = @34' */
  /* #401: @9 = mac(@34,@10,@1) */
  casadi_copy(w01, 3, w09);
  for (i=0, rr=w09; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #402: @9 = @9' */
  /* #403: @56 = mac(@34,@59,@1) */
  casadi_copy(w01, 3, w56);
  for (i=0, rr=w56; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #404: @56 = @56' */
  /* #405: @9 = (@9+@56) */
  for (i=0, rr=w09, cs=w56; i<3; ++i) (*rr++) += (*cs++);
  /* #406: @56 = (-@9) */
  for (i=0, rr=w56, cs=w09; i<3; ++i) *rr++ = (- *cs++ );
  /* #407: @67 = mac(@56,@49,@37) */
  casadi_copy(w37, 9, w67);
  for (i=0, rr=w67; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w56+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #408: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #409: @56 = mac(@67,@27,@36) */
  casadi_copy(w36, 3, w56);
  for (i=0, rr=w56; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #410: @21 = (@21+@56) */
  for (i=0, rr=w21, cs=w56; i<3; ++i) (*rr++) += (*cs++);
  /* #411: @56 = mac(@47,@67,@1) */
  casadi_copy(w01, 3, w56);
  for (i=0, rr=w56; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w67+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #412: @34 = mac(@25,@63,@1) */
  casadi_copy(w01, 3, w34);
  casadi_mtimes((&w25), casadi_s2, w63, casadi_s1, w34, casadi_s0, w, 0);
  /* #413: @56 = (@56+@34) */
  for (i=0, rr=w56, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #414: @56 = @56' */
  /* #415: @21 = (@21+@56) */
  for (i=0, rr=w21, cs=w56; i<3; ++i) (*rr++) += (*cs++);
  /* #416: @25 = @66[0] */
  for (rr=(&w25), cs=(&w66)+0; cs!=(&w66)+1; cs+=1) *rr++ = *cs;
  /* #417: @66 = (@24*@25) */
  w66  = (w24*w25);
  /* #418: @25 = (@16*@25) */
  w25  = (w16*w25);
  /* #419: @25 = (-@25) */
  w25 = (- w25 );
  /* #420: @70 = vertcat(@69, @66, @25) */
  rr=w70;
  *rr++ = w66;
  *rr++ = w25;
  /* #421: @70 = @70' */
  /* #422: @56 = mac(@70,@22,@1) */
  casadi_copy(w01, 3, w56);
  casadi_mtimes(w70, casadi_s5, wr22, casadi_s1, w56, casadi_s0, w, 0);
  /* #423: @56 = @56' */
  /* #424: @34 = mac(@70,@61,@1) */
  casadi_copy(w01, 3, w34);
  casadi_mtimes(w70, casadi_s5, w61, casadi_s1, w34, casadi_s0, w, 0);
  /* #425: @34 = @34' */
  /* #426: @56 = (@56+@34) */
  for (i=0, rr=w56, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #427: {@66, @25, @30} = vertsplit(@56) */
  w66 = w56[0];
  w25 = w56[1];
  w30 = w56[2];
  /* #428: @18 = (@24*@25) */
  w18  = (w24*w25);
  /* #429: @31 = (@16*@30) */
  w31  = (w16*w30);
  /* #430: @18 = (@18-@31) */
  w18 -= w31;
  /* #431: (@21[0] += @18) */
  for (rr=w21+0, cs=(&w18); rr!=w21+1; rr+=1) *rr += *cs++;
  /* #432: @30 = (@32*@30) */
  w30  = (w32*w30);
  /* #433: @18 = (@24*@66) */
  w18  = (w24*w66);
  /* #434: @30 = (@30-@18) */
  w30 -= w18;
  /* #435: (@21[1] += @30) */
  for (rr=w21+1, cs=(&w30); rr!=w21+2; rr+=1) *rr += *cs++;
  /* #436: @66 = (@16*@66) */
  w66  = (w16*w66);
  /* #437: @25 = (@32*@25) */
  w25  = (w32*w25);
  /* #438: @66 = (@66-@25) */
  w66 -= w25;
  /* #439: (@21[2] += @66) */
  for (rr=w21+2, cs=(&w66); rr!=w21+3; rr+=1) *rr += *cs++;
  /* #440: @3 = vertcat(@50, @46, @42, @11, @35, @29, @28, @21, @23, @6, @9) */
  rr=w03;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w09; i<3; ++i) *rr++ = *cs++;
  /* #441: (@64[0, 1, 2, 9, 10, 11, 18, 19, 20, 27, 28, 29, 36, 37, 38, 45, 46, 47, 63, 64, 65, 81, 82, 83, 48, 49, 50, 66, 67, 68, 84, 85, 86] = @3) */
  for (cii=casadi_s6, rr=w64, cs=w03; cii!=casadi_s6+33; ++cii, ++cs) rr[*cii] = *cs;
  /* #442: (@64[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 51, 57, 63, 69, 75, 81, 87, 93, 99, 105, 111, 117, 123, 129, 135, 141, 147] = @3) */
  for (cii=casadi_s7, rr=w64, cs=w03; cii!=casadi_s7+33; ++cii, ++cs) rr[*cii] = *cs;
  /* #443: @65 = ones(33x1,8nz) */
  casadi_fill(w65, 8, 1.);
  /* #444: {@66, @25, @30, @18, @31, @13, @0, @7, NULL, NULL, NULL} = vertsplit(@65) */
  w66 = w65[0];
  w25 = w65[1];
  w30 = w65[2];
  w18 = w65[3];
  w31 = w65[4];
  w13 = w65[5];
  w00 = w65[6];
  w07 = w65[7];
  /* #445: @66 = @66' */
  /* #446: @50 = mac(@66,@39,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w66), casadi_s8, wr39, casadi_s1, w50, casadi_s0, w, 0);
  /* #447: @50 = @50' */
  /* #448: @46 = mac(@66,@57,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w66), casadi_s8, w57, casadi_s1, w46, casadi_s0, w, 0);
  /* #449: @46 = @46' */
  /* #450: @50 = (@50+@46) */
  for (i=0, rr=w50, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #451: @25 = @25' */
  /* #452: @46 = mac(@25,@39,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w25), casadi_s8, wr39, casadi_s1, w46, casadi_s0, w, 0);
  /* #453: @46 = @46' */
  /* #454: @42 = mac(@25,@57,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w25), casadi_s8, w57, casadi_s1, w42, casadi_s0, w, 0);
  /* #455: @42 = @42' */
  /* #456: @46 = (@46+@42) */
  for (i=0, rr=w46, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #457: @30 = @30' */
  /* #458: @42 = mac(@30,@39,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w30), casadi_s8, wr39, casadi_s1, w42, casadi_s0, w, 0);
  /* #459: @42 = @42' */
  /* #460: @11 = mac(@30,@57,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w30), casadi_s8, w57, casadi_s1, w11, casadi_s0, w, 0);
  /* #461: @11 = @11' */
  /* #462: @42 = (@42+@11) */
  for (i=0, rr=w42, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #463: @18 = @18' */
  /* #464: @11 = mac(@18,@5,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w18), casadi_s8, wr05, casadi_s1, w11, casadi_s0, w, 0);
  /* #465: @11 = @11' */
  /* #466: @35 = mac(@18,@58,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes((&w18), casadi_s8, w58, casadi_s1, w35, casadi_s0, w, 0);
  /* #467: @35 = @35' */
  /* #468: @11 = (@11+@35) */
  for (i=0, rr=w11, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #469: @31 = @31' */
  /* #470: @35 = mac(@31,@10,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes((&w31), casadi_s8, wr10, casadi_s1, w35, casadi_s0, w, 0);
  /* #471: @35 = @35' */
  /* #472: @35 = (@8*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #473: @31 = (@8*@31) */
  w31  = (w08*w31);
  /* #474: @29 = mac(@31,@59,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes((&w31), casadi_s8, w59, casadi_s1, w29, casadi_s0, w, 0);
  /* #475: @29 = @29' */
  /* #476: @35 = (@35+@29) */
  for (i=0, rr=w35, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #477: @29 = mac(@60,@13,@36) */
  casadi_copy(w36, 3, w29);
  casadi_mtimes(w60, casadi_s1, (&w13), casadi_s9, w29, casadi_s3, w, 0);
  /* #478: @31 = @13' */
  w31 = w13;
  /* #479: @67 = mac(@2,@31,@37) */
  casadi_copy(w37, 9, w67);
  casadi_mtimes(w02, casadi_s3, (&w31), casadi_s8, w67, casadi_s1, w, 0);
  /* #480: @68 = mac(@13,@38,@37) */
  casadi_copy(w37, 9, w68);
  casadi_mtimes((&w13), casadi_s9, w38, casadi_s0, w68, casadi_s1, w, 0);
  /* #481: @67 = (@67+@68) */
  for (i=0, rr=w67, cs=w68; i<9; ++i) (*rr++) += (*cs++);
  /* #482: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #483: @28 = mac(@67,@40,@36) */
  casadi_copy(w36, 3, w28);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=wr40+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #484: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) *rr++ = (- *cs++ );
  /* #485: @28 = @28' */
  /* #486: @21 = mac(@28,@10,@1) */
  casadi_copy(w01, 3, w21);
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #487: @21 = @21' */
  /* #488: @23 = mac(@28,@59,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #489: @23 = @23' */
  /* #490: @21 = (@21+@23) */
  for (i=0, rr=w21, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #491: @23 = (-@21) */
  for (i=0, rr=w23, cs=w21; i<3; ++i) *rr++ = (- *cs++ );
  /* #492: @67 = mac(@23,@41,@37) */
  casadi_copy(w37, 9, w67);
  for (i=0, rr=w67; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w23+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #493: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #494: @23 = mac(@67,@2,@36) */
  casadi_copy(w36, 3, w23);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #495: @29 = (@29+@23) */
  for (i=0, rr=w29, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #496: @23 = mac(@38,@67,@1) */
  casadi_copy(w01, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w67+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #497: @28 = mac(@31,@60,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes((&w31), casadi_s8, w60, casadi_s1, w28, casadi_s0, w, 0);
  /* #498: @23 = (@23+@28) */
  for (i=0, rr=w23, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #499: @23 = @23' */
  /* #500: @29 = (@29+@23) */
  for (i=0, rr=w29, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #501: @31 = @13[0] */
  for (rr=(&w31), cs=(&w13)+0; cs!=(&w13)+1; cs+=1) *rr++ = *cs;
  /* #502: @13 = (@15*@31) */
  w13  = (w15*w31);
  /* #503: @13 = (-@13) */
  w13 = (- w13 );
  /* #504: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #505: @70 = vertcat(@13, @69, @31) */
  rr=w70;
  *rr++ = w13;
  *rr++ = w31;
  /* #506: @70 = @70' */
  /* #507: @23 = mac(@70,@22,@1) */
  casadi_copy(w01, 3, w23);
  casadi_mtimes(w70, casadi_s10, wr22, casadi_s1, w23, casadi_s0, w, 0);
  /* #508: @23 = @23' */
  /* #509: @28 = mac(@70,@61,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes(w70, casadi_s10, w61, casadi_s1, w28, casadi_s0, w, 0);
  /* #510: @28 = @28' */
  /* #511: @23 = (@23+@28) */
  for (i=0, rr=w23, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #512: {@13, @31, @18} = vertsplit(@23) */
  w13 = w23[0];
  w31 = w23[1];
  w18 = w23[2];
  /* #513: @30 = (@15*@31) */
  w30  = (w15*w31);
  /* #514: @25 = (@12*@18) */
  w25  = (w12*w18);
  /* #515: @30 = (@30-@25) */
  w30 -= w25;
  /* #516: (@29[0] += @30) */
  for (rr=w29+0, cs=(&w30); rr!=w29+1; rr+=1) *rr += *cs++;
  /* #517: @18 = (@19*@18) */
  w18  = (w19*w18);
  /* #518: @30 = (@15*@13) */
  w30  = (w15*w13);
  /* #519: @18 = (@18-@30) */
  w18 -= w30;
  /* #520: (@29[1] += @18) */
  for (rr=w29+1, cs=(&w18); rr!=w29+2; rr+=1) *rr += *cs++;
  /* #521: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #522: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #523: @13 = (@13-@31) */
  w13 -= w31;
  /* #524: (@29[2] += @13) */
  for (rr=w29+2, cs=(&w13); rr!=w29+3; rr+=1) *rr += *cs++;
  /* #525: @23 = mac(@62,@0,@36) */
  casadi_copy(w36, 3, w23);
  casadi_mtimes(w62, casadi_s1, (&w00), casadi_s9, w23, casadi_s3, w, 0);
  /* #526: @13 = @0' */
  w13 = w00;
  /* #527: @67 = mac(@20,@13,@37) */
  casadi_copy(w37, 9, w67);
  casadi_mtimes(w20, casadi_s3, (&w13), casadi_s8, w67, casadi_s1, w, 0);
  /* #528: @68 = mac(@0,@43,@37) */
  casadi_copy(w37, 9, w68);
  casadi_mtimes((&w00), casadi_s9, w43, casadi_s0, w68, casadi_s1, w, 0);
  /* #529: @67 = (@67+@68) */
  for (i=0, rr=w67, cs=w68; i<9; ++i) (*rr++) += (*cs++);
  /* #530: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #531: @28 = mac(@67,@44,@36) */
  casadi_copy(w36, 3, w28);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=wr44+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #532: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) *rr++ = (- *cs++ );
  /* #533: @28 = @28' */
  /* #534: @6 = mac(@28,@10,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #535: @6 = @6' */
  /* #536: @9 = mac(@28,@59,@1) */
  casadi_copy(w01, 3, w09);
  for (i=0, rr=w09; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #537: @9 = @9' */
  /* #538: @6 = (@6+@9) */
  for (i=0, rr=w06, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #539: @9 = (-@6) */
  for (i=0, rr=w09, cs=w06; i<3; ++i) *rr++ = (- *cs++ );
  /* #540: @67 = mac(@9,@45,@37) */
  casadi_copy(w37, 9, w67);
  for (i=0, rr=w67; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w09+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #541: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #542: @9 = mac(@67,@20,@36) */
  casadi_copy(w36, 3, w09);
  for (i=0, rr=w09; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #543: @23 = (@23+@9) */
  for (i=0, rr=w23, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #544: @9 = mac(@43,@67,@1) */
  casadi_copy(w01, 3, w09);
  for (i=0, rr=w09; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w67+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #545: @28 = mac(@13,@62,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes((&w13), casadi_s8, w62, casadi_s1, w28, casadi_s0, w, 0);
  /* #546: @9 = (@9+@28) */
  for (i=0, rr=w09, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #547: @9 = @9' */
  /* #548: @23 = (@23+@9) */
  for (i=0, rr=w23, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #549: @13 = @0[0] */
  for (rr=(&w13), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #550: @0 = (@17*@13) */
  w00  = (w17*w13);
  /* #551: @0 = (-@0) */
  w00 = (- w00 );
  /* #552: @13 = (@26*@13) */
  w13  = (w26*w13);
  /* #553: @70 = vertcat(@0, @69, @13) */
  rr=w70;
  *rr++ = w00;
  *rr++ = w13;
  /* #554: @70 = @70' */
  /* #555: @9 = mac(@70,@22,@1) */
  casadi_copy(w01, 3, w09);
  casadi_mtimes(w70, casadi_s10, wr22, casadi_s1, w09, casadi_s0, w, 0);
  /* #556: @9 = @9' */
  /* #557: @28 = mac(@70,@61,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes(w70, casadi_s10, w61, casadi_s1, w28, casadi_s0, w, 0);
  /* #558: @28 = @28' */
  /* #559: @9 = (@9+@28) */
  for (i=0, rr=w09, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #560: {@0, @13, @31} = vertsplit(@9) */
  w00 = w09[0];
  w13 = w09[1];
  w31 = w09[2];
  /* #561: @18 = (@17*@13) */
  w18  = (w17*w13);
  /* #562: @30 = (@14*@31) */
  w30  = (w14*w31);
  /* #563: @18 = (@18-@30) */
  w18 -= w30;
  /* #564: (@23[0] += @18) */
  for (rr=w23+0, cs=(&w18); rr!=w23+1; rr+=1) *rr += *cs++;
  /* #565: @31 = (@26*@31) */
  w31  = (w26*w31);
  /* #566: @18 = (@17*@0) */
  w18  = (w17*w00);
  /* #567: @31 = (@31-@18) */
  w31 -= w18;
  /* #568: (@23[1] += @31) */
  for (rr=w23+1, cs=(&w31); rr!=w23+2; rr+=1) *rr += *cs++;
  /* #569: @0 = (@14*@0) */
  w00  = (w14*w00);
  /* #570: @13 = (@26*@13) */
  w13  = (w26*w13);
  /* #571: @0 = (@0-@13) */
  w00 -= w13;
  /* #572: (@23[2] += @0) */
  for (rr=w23+2, cs=(&w00); rr!=w23+3; rr+=1) *rr += *cs++;
  /* #573: @9 = mac(@63,@7,@36) */
  casadi_copy(w36, 3, w09);
  casadi_mtimes(w63, casadi_s1, (&w07), casadi_s9, w09, casadi_s3, w, 0);
  /* #574: @0 = @7' */
  w00 = w07;
  /* #575: @67 = mac(@27,@0,@37) */
  casadi_copy(w37, 9, w67);
  casadi_mtimes(w27, casadi_s3, (&w00), casadi_s8, w67, casadi_s1, w, 0);
  /* #576: @68 = mac(@7,@47,@37) */
  casadi_copy(w37, 9, w68);
  casadi_mtimes((&w07), casadi_s9, w47, casadi_s0, w68, casadi_s1, w, 0);
  /* #577: @67 = (@67+@68) */
  for (i=0, rr=w67, cs=w68; i<9; ++i) (*rr++) += (*cs++);
  /* #578: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #579: @28 = mac(@67,@48,@36) */
  casadi_copy(w36, 3, w28);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=wr48+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #580: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) *rr++ = (- *cs++ );
  /* #581: @28 = @28' */
  /* #582: @56 = mac(@28,@10,@1) */
  casadi_copy(w01, 3, w56);
  for (i=0, rr=w56; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #583: @56 = @56' */
  /* #584: @34 = mac(@28,@59,@1) */
  casadi_copy(w01, 3, w34);
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #585: @34 = @34' */
  /* #586: @56 = (@56+@34) */
  for (i=0, rr=w56, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #587: @34 = (-@56) */
  for (i=0, rr=w34, cs=w56; i<3; ++i) *rr++ = (- *cs++ );
  /* #588: @67 = mac(@34,@49,@37) */
  casadi_copy(w37, 9, w67);
  for (i=0, rr=w67; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w34+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #589: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<9; ++i) *rr++ = (- *cs++ );
  /* #590: @34 = mac(@67,@27,@36) */
  casadi_copy(w36, 3, w34);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w67+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #591: @9 = (@9+@34) */
  for (i=0, rr=w09, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #592: @34 = mac(@47,@67,@1) */
  casadi_copy(w01, 3, w34);
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w67+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #593: @28 = mac(@0,@63,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes((&w00), casadi_s8, w63, casadi_s1, w28, casadi_s0, w, 0);
  /* #594: @34 = (@34+@28) */
  for (i=0, rr=w34, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #595: @34 = @34' */
  /* #596: @9 = (@9+@34) */
  for (i=0, rr=w09, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #597: @0 = @7[0] */
  for (rr=(&w00), cs=(&w07)+0; cs!=(&w07)+1; cs+=1) *rr++ = *cs;
  /* #598: @7 = (@24*@0) */
  w07  = (w24*w00);
  /* #599: @7 = (-@7) */
  w07 = (- w07 );
  /* #600: @0 = (@32*@0) */
  w00  = (w32*w00);
  /* #601: @70 = vertcat(@7, @69, @0) */
  rr=w70;
  *rr++ = w07;
  *rr++ = w00;
  /* #602: @70 = @70' */
  /* #603: @34 = mac(@70,@22,@1) */
  casadi_copy(w01, 3, w34);
  casadi_mtimes(w70, casadi_s10, wr22, casadi_s1, w34, casadi_s0, w, 0);
  /* #604: @34 = @34' */
  /* #605: @28 = mac(@70,@61,@1) */
  casadi_copy(w01, 3, w28);
  casadi_mtimes(w70, casadi_s10, w61, casadi_s1, w28, casadi_s0, w, 0);
  /* #606: @28 = @28' */
  /* #607: @34 = (@34+@28) */
  for (i=0, rr=w34, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #608: {@7, @0, @13} = vertsplit(@34) */
  w07 = w34[0];
  w00 = w34[1];
  w13 = w34[2];
  /* #609: @31 = (@24*@0) */
  w31  = (w24*w00);
  /* #610: @18 = (@16*@13) */
  w18  = (w16*w13);
  /* #611: @31 = (@31-@18) */
  w31 -= w18;
  /* #612: (@9[0] += @31) */
  for (rr=w09+0, cs=(&w31); rr!=w09+1; rr+=1) *rr += *cs++;
  /* #613: @13 = (@32*@13) */
  w13  = (w32*w13);
  /* #614: @31 = (@24*@7) */
  w31  = (w24*w07);
  /* #615: @13 = (@13-@31) */
  w13 -= w31;
  /* #616: (@9[1] += @13) */
  for (rr=w09+1, cs=(&w13); rr!=w09+2; rr+=1) *rr += *cs++;
  /* #617: @7 = (@16*@7) */
  w07  = (w16*w07);
  /* #618: @0 = (@32*@0) */
  w00  = (w32*w00);
  /* #619: @7 = (@7-@0) */
  w07 -= w00;
  /* #620: (@9[2] += @7) */
  for (rr=w09+2, cs=(&w07); rr!=w09+3; rr+=1) *rr += *cs++;
  /* #621: @3 = vertcat(@50, @46, @42, @11, @35, @29, @23, @9, @21, @6, @56) */
  rr=w03;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w09; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w56; i<3; ++i) *rr++ = *cs++;
  /* #622: (@64[3, 4, 5, 12, 13, 14, 21, 22, 23, 30, 31, 32, 39, 40, 41, 51, 52, 53, 69, 70, 71, 87, 88, 89, 54, 55, 56, 72, 73, 74, 90, 91, 92] = @3) */
  for (cii=casadi_s11, rr=w64, cs=w03; cii!=casadi_s11+33; ++cii, ++cs) rr[*cii] = *cs;
  /* #623: (@64[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 52, 58, 64, 70, 76, 82, 88, 94, 100, 106, 112, 118, 124, 130, 136, 142, 148] = @3) */
  for (cii=casadi_s12, rr=w64, cs=w03; cii!=casadi_s12+33; ++cii, ++cs) rr[*cii] = *cs;
  /* #624: @65 = ones(33x1,8nz) */
  casadi_fill(w65, 8, 1.);
  /* #625: {@7, @0, @13, @31, @18, @30, @25, @66, NULL, NULL, NULL} = vertsplit(@65) */
  w07 = w65[0];
  w00 = w65[1];
  w13 = w65[2];
  w31 = w65[3];
  w18 = w65[4];
  w30 = w65[5];
  w25 = w65[6];
  w66 = w65[7];
  /* #626: @7 = @7' */
  /* #627: @50 = mac(@7,@39,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w07), casadi_s13, wr39, casadi_s1, w50, casadi_s0, w, 0);
  /* #628: @50 = @50' */
  /* #629: @46 = mac(@7,@57,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w07), casadi_s13, w57, casadi_s1, w46, casadi_s0, w, 0);
  /* #630: @46 = @46' */
  /* #631: @50 = (@50+@46) */
  for (i=0, rr=w50, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #632: @0 = @0' */
  /* #633: @46 = mac(@0,@39,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w00), casadi_s13, wr39, casadi_s1, w46, casadi_s0, w, 0);
  /* #634: @46 = @46' */
  /* #635: @42 = mac(@0,@57,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w00), casadi_s13, w57, casadi_s1, w42, casadi_s0, w, 0);
  /* #636: @42 = @42' */
  /* #637: @46 = (@46+@42) */
  for (i=0, rr=w46, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #638: @13 = @13' */
  /* #639: @42 = mac(@13,@39,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w13), casadi_s13, wr39, casadi_s1, w42, casadi_s0, w, 0);
  /* #640: @42 = @42' */
  /* #641: @11 = mac(@13,@57,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w13), casadi_s13, w57, casadi_s1, w11, casadi_s0, w, 0);
  /* #642: @11 = @11' */
  /* #643: @42 = (@42+@11) */
  for (i=0, rr=w42, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #644: @31 = @31' */
  /* #645: @11 = mac(@31,@5,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w31), casadi_s13, wr05, casadi_s1, w11, casadi_s0, w, 0);
  /* #646: @11 = @11' */
  /* #647: @35 = mac(@31,@58,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes((&w31), casadi_s13, w58, casadi_s1, w35, casadi_s0, w, 0);
  /* #648: @35 = @35' */
  /* #649: @11 = (@11+@35) */
  for (i=0, rr=w11, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #650: @18 = @18' */
  /* #651: @35 = mac(@18,@10,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes((&w18), casadi_s13, wr10, casadi_s1, w35, casadi_s0, w, 0);
  /* #652: @35 = @35' */
  /* #653: @35 = (@8*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #654: @8 = (@8*@18) */
  w08 *= w18;
  /* #655: @29 = mac(@8,@59,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes((&w08), casadi_s13, w59, casadi_s1, w29, casadi_s0, w, 0);
  /* #656: @29 = @29' */
  /* #657: @35 = (@35+@29) */
  for (i=0, rr=w35, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #658: @29 = mac(@60,@30,@36) */
  casadi_copy(w36, 3, w29);
  casadi_mtimes(w60, casadi_s1, (&w30), casadi_s14, w29, casadi_s3, w, 0);
  /* #659: @8 = @30' */
  w08 = w30;
  /* #660: @58 = mac(@2,@8,@37) */
  casadi_copy(w37, 9, w58);
  casadi_mtimes(w02, casadi_s3, (&w08), casadi_s13, w58, casadi_s1, w, 0);
  /* #661: @5 = mac(@30,@38,@37) */
  casadi_copy(w37, 9, w05);
  casadi_mtimes((&w30), casadi_s14, w38, casadi_s0, w05, casadi_s1, w, 0);
  /* #662: @58 = (@58+@5) */
  for (i=0, rr=w58, cs=w05; i<9; ++i) (*rr++) += (*cs++);
  /* #663: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #664: @23 = mac(@58,@40,@36) */
  casadi_copy(w36, 3, w23);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=wr40+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #665: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #666: @23 = @23' */
  /* #667: @40 = mac(@23,@10,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #668: @40 = @40' */
  /* #669: @9 = mac(@23,@59,@1) */
  casadi_copy(w01, 3, w09);
  for (i=0, rr=w09; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #670: @9 = @9' */
  /* #671: @40 = (@40+@9) */
  for (i=0, rr=w40, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #672: @9 = (-@40) */
  for (i=0, rr=w09, cs=w40; i<3; ++i) *rr++ = (- *cs++ );
  /* #673: @58 = mac(@9,@41,@37) */
  casadi_copy(w37, 9, w58);
  for (i=0, rr=w58; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w09+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #674: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<9; ++i) *rr++ = (- *cs++ );
  /* #675: @9 = mac(@58,@2,@36) */
  casadi_copy(w36, 3, w09);
  for (i=0, rr=w09; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w58+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #676: @29 = (@29+@9) */
  for (i=0, rr=w29, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #677: @9 = mac(@38,@58,@1) */
  casadi_copy(w01, 3, w09);
  for (i=0, rr=w09; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w58+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #678: @23 = mac(@8,@60,@1) */
  casadi_copy(w01, 3, w23);
  casadi_mtimes((&w08), casadi_s13, w60, casadi_s1, w23, casadi_s0, w, 0);
  /* #679: @9 = (@9+@23) */
  for (i=0, rr=w09, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #680: @9 = @9' */
  /* #681: @29 = (@29+@9) */
  for (i=0, rr=w29, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #682: @8 = @30[0] */
  for (rr=(&w08), cs=(&w30)+0; cs!=(&w30)+1; cs+=1) *rr++ = *cs;
  /* #683: @30 = (@12*@8) */
  w30  = (w12*w08);
  /* #684: @8 = (@19*@8) */
  w08  = (w19*w08);
  /* #685: @8 = (-@8) */
  w08 = (- w08 );
  /* #686: @70 = vertcat(@30, @8, @69) */
  rr=w70;
  *rr++ = w30;
  *rr++ = w08;
  /* #687: @70 = @70' */
  /* #688: @9 = mac(@70,@22,@1) */
  casadi_copy(w01, 3, w09);
  casadi_mtimes(w70, casadi_s15, wr22, casadi_s1, w09, casadi_s0, w, 0);
  /* #689: @9 = @9' */
  /* #690: @23 = mac(@70,@61,@1) */
  casadi_copy(w01, 3, w23);
  casadi_mtimes(w70, casadi_s15, w61, casadi_s1, w23, casadi_s0, w, 0);
  /* #691: @23 = @23' */
  /* #692: @9 = (@9+@23) */
  for (i=0, rr=w09, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #693: {@30, @8, @18} = vertsplit(@9) */
  w30 = w09[0];
  w08 = w09[1];
  w18 = w09[2];
  /* #694: @31 = (@15*@8) */
  w31  = (w15*w08);
  /* #695: @13 = (@12*@18) */
  w13  = (w12*w18);
  /* #696: @31 = (@31-@13) */
  w31 -= w13;
  /* #697: (@29[0] += @31) */
  for (rr=w29+0, cs=(&w31); rr!=w29+1; rr+=1) *rr += *cs++;
  /* #698: @18 = (@19*@18) */
  w18  = (w19*w18);
  /* #699: @15 = (@15*@30) */
  w15 *= w30;
  /* #700: @18 = (@18-@15) */
  w18 -= w15;
  /* #701: (@29[1] += @18) */
  for (rr=w29+1, cs=(&w18); rr!=w29+2; rr+=1) *rr += *cs++;
  /* #702: @12 = (@12*@30) */
  w12 *= w30;
  /* #703: @19 = (@19*@8) */
  w19 *= w08;
  /* #704: @12 = (@12-@19) */
  w12 -= w19;
  /* #705: (@29[2] += @12) */
  for (rr=w29+2, cs=(&w12); rr!=w29+3; rr+=1) *rr += *cs++;
  /* #706: @9 = mac(@62,@25,@36) */
  casadi_copy(w36, 3, w09);
  casadi_mtimes(w62, casadi_s1, (&w25), casadi_s14, w09, casadi_s3, w, 0);
  /* #707: @12 = @25' */
  w12 = w25;
  /* #708: @60 = mac(@20,@12,@37) */
  casadi_copy(w37, 9, w60);
  casadi_mtimes(w20, casadi_s3, (&w12), casadi_s13, w60, casadi_s1, w, 0);
  /* #709: @58 = mac(@25,@43,@37) */
  casadi_copy(w37, 9, w58);
  casadi_mtimes((&w25), casadi_s14, w43, casadi_s0, w58, casadi_s1, w, 0);
  /* #710: @60 = (@60+@58) */
  for (i=0, rr=w60, cs=w58; i<9; ++i) (*rr++) += (*cs++);
  /* #711: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<9; ++i) *rr++ = (- *cs++ );
  /* #712: @23 = mac(@60,@44,@36) */
  casadi_copy(w36, 3, w23);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w60+j, ct=wr44+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #713: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #714: @23 = @23' */
  /* #715: @44 = mac(@23,@10,@1) */
  casadi_copy(w01, 3, w44);
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #716: @44 = @44' */
  /* #717: @21 = mac(@23,@59,@1) */
  casadi_copy(w01, 3, w21);
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #718: @21 = @21' */
  /* #719: @44 = (@44+@21) */
  for (i=0, rr=w44, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #720: @21 = (-@44) */
  for (i=0, rr=w21, cs=w44; i<3; ++i) *rr++ = (- *cs++ );
  /* #721: @60 = mac(@21,@45,@37) */
  casadi_copy(w37, 9, w60);
  for (i=0, rr=w60; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #722: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<9; ++i) *rr++ = (- *cs++ );
  /* #723: @21 = mac(@60,@20,@36) */
  casadi_copy(w36, 3, w21);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w60+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #724: @9 = (@9+@21) */
  for (i=0, rr=w09, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #725: @21 = mac(@43,@60,@1) */
  casadi_copy(w01, 3, w21);
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w60+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #726: @23 = mac(@12,@62,@1) */
  casadi_copy(w01, 3, w23);
  casadi_mtimes((&w12), casadi_s13, w62, casadi_s1, w23, casadi_s0, w, 0);
  /* #727: @21 = (@21+@23) */
  for (i=0, rr=w21, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #728: @21 = @21' */
  /* #729: @9 = (@9+@21) */
  for (i=0, rr=w09, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #730: @12 = @25[0] */
  for (rr=(&w12), cs=(&w25)+0; cs!=(&w25)+1; cs+=1) *rr++ = *cs;
  /* #731: @25 = (@14*@12) */
  w25  = (w14*w12);
  /* #732: @12 = (@26*@12) */
  w12  = (w26*w12);
  /* #733: @12 = (-@12) */
  w12 = (- w12 );
  /* #734: @70 = vertcat(@25, @12, @69) */
  rr=w70;
  *rr++ = w25;
  *rr++ = w12;
  /* #735: @70 = @70' */
  /* #736: @21 = mac(@70,@22,@1) */
  casadi_copy(w01, 3, w21);
  casadi_mtimes(w70, casadi_s15, wr22, casadi_s1, w21, casadi_s0, w, 0);
  /* #737: @21 = @21' */
  /* #738: @23 = mac(@70,@61,@1) */
  casadi_copy(w01, 3, w23);
  casadi_mtimes(w70, casadi_s15, w61, casadi_s1, w23, casadi_s0, w, 0);
  /* #739: @23 = @23' */
  /* #740: @21 = (@21+@23) */
  for (i=0, rr=w21, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #741: {@25, @12, @19} = vertsplit(@21) */
  w25 = w21[0];
  w12 = w21[1];
  w19 = w21[2];
  /* #742: @8 = (@17*@12) */
  w08  = (w17*w12);
  /* #743: @30 = (@14*@19) */
  w30  = (w14*w19);
  /* #744: @8 = (@8-@30) */
  w08 -= w30;
  /* #745: (@9[0] += @8) */
  for (rr=w09+0, cs=(&w08); rr!=w09+1; rr+=1) *rr += *cs++;
  /* #746: @19 = (@26*@19) */
  w19  = (w26*w19);
  /* #747: @17 = (@17*@25) */
  w17 *= w25;
  /* #748: @19 = (@19-@17) */
  w19 -= w17;
  /* #749: (@9[1] += @19) */
  for (rr=w09+1, cs=(&w19); rr!=w09+2; rr+=1) *rr += *cs++;
  /* #750: @14 = (@14*@25) */
  w14 *= w25;
  /* #751: @26 = (@26*@12) */
  w26 *= w12;
  /* #752: @14 = (@14-@26) */
  w14 -= w26;
  /* #753: (@9[2] += @14) */
  for (rr=w09+2, cs=(&w14); rr!=w09+3; rr+=1) *rr += *cs++;
  /* #754: @21 = mac(@63,@66,@36) */
  casadi_copy(w36, 3, w21);
  casadi_mtimes(w63, casadi_s1, (&w66), casadi_s14, w21, casadi_s3, w, 0);
  /* #755: @14 = @66' */
  w14 = w66;
  /* #756: @62 = mac(@27,@14,@37) */
  casadi_copy(w37, 9, w62);
  casadi_mtimes(w27, casadi_s3, (&w14), casadi_s13, w62, casadi_s1, w, 0);
  /* #757: @60 = mac(@66,@47,@37) */
  casadi_copy(w37, 9, w60);
  casadi_mtimes((&w66), casadi_s14, w47, casadi_s0, w60, casadi_s1, w, 0);
  /* #758: @62 = (@62+@60) */
  for (i=0, rr=w62, cs=w60; i<9; ++i) (*rr++) += (*cs++);
  /* #759: @62 = (-@62) */
  for (i=0, rr=w62, cs=w62; i<9; ++i) *rr++ = (- *cs++ );
  /* #760: @23 = mac(@62,@48,@36) */
  casadi_copy(w36, 3, w23);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w62+j, ct=wr48+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #761: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #762: @23 = @23' */
  /* #763: @48 = mac(@23,@10,@1) */
  casadi_copy(w01, 3, w48);
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=wr10+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #764: @48 = @48' */
  /* #765: @6 = mac(@23,@59,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=w59+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #766: @6 = @6' */
  /* #767: @48 = (@48+@6) */
  for (i=0, rr=w48, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #768: @6 = (-@48) */
  for (i=0, rr=w06, cs=w48; i<3; ++i) *rr++ = (- *cs++ );
  /* #769: @62 = mac(@6,@49,@37) */
  casadi_copy(w37, 9, w62);
  for (i=0, rr=w62; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w06+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #770: @62 = (-@62) */
  for (i=0, rr=w62, cs=w62; i<9; ++i) *rr++ = (- *cs++ );
  /* #771: @6 = mac(@62,@27,@36) */
  casadi_copy(w36, 3, w06);
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w62+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #772: @21 = (@21+@6) */
  for (i=0, rr=w21, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #773: @6 = mac(@47,@62,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w62+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #774: @23 = mac(@14,@63,@1) */
  casadi_copy(w01, 3, w23);
  casadi_mtimes((&w14), casadi_s13, w63, casadi_s1, w23, casadi_s0, w, 0);
  /* #775: @6 = (@6+@23) */
  for (i=0, rr=w06, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #776: @6 = @6' */
  /* #777: @21 = (@21+@6) */
  for (i=0, rr=w21, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #778: @14 = @66[0] */
  for (rr=(&w14), cs=(&w66)+0; cs!=(&w66)+1; cs+=1) *rr++ = *cs;
  /* #779: @66 = (@16*@14) */
  w66  = (w16*w14);
  /* #780: @14 = (@32*@14) */
  w14  = (w32*w14);
  /* #781: @14 = (-@14) */
  w14 = (- w14 );
  /* #782: @70 = vertcat(@66, @14, @69) */
  rr=w70;
  *rr++ = w66;
  *rr++ = w14;
  /* #783: @70 = @70' */
  /* #784: @6 = mac(@70,@22,@1) */
  casadi_copy(w01, 3, w06);
  casadi_mtimes(w70, casadi_s15, wr22, casadi_s1, w06, casadi_s0, w, 0);
  /* #785: @6 = @6' */
  /* #786: @23 = mac(@70,@61,@1) */
  casadi_copy(w01, 3, w23);
  casadi_mtimes(w70, casadi_s15, w61, casadi_s1, w23, casadi_s0, w, 0);
  /* #787: @23 = @23' */
  /* #788: @6 = (@6+@23) */
  for (i=0, rr=w06, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #789: {@66, @14, @26} = vertsplit(@6) */
  w66 = w06[0];
  w14 = w06[1];
  w26 = w06[2];
  /* #790: @12 = (@24*@14) */
  w12  = (w24*w14);
  /* #791: @25 = (@16*@26) */
  w25  = (w16*w26);
  /* #792: @12 = (@12-@25) */
  w12 -= w25;
  /* #793: (@21[0] += @12) */
  for (rr=w21+0, cs=(&w12); rr!=w21+1; rr+=1) *rr += *cs++;
  /* #794: @26 = (@32*@26) */
  w26  = (w32*w26);
  /* #795: @24 = (@24*@66) */
  w24 *= w66;
  /* #796: @26 = (@26-@24) */
  w26 -= w24;
  /* #797: (@21[1] += @26) */
  for (rr=w21+1, cs=(&w26); rr!=w21+2; rr+=1) *rr += *cs++;
  /* #798: @16 = (@16*@66) */
  w16 *= w66;
  /* #799: @32 = (@32*@14) */
  w32 *= w14;
  /* #800: @16 = (@16-@32) */
  w16 -= w32;
  /* #801: (@21[2] += @16) */
  for (rr=w21+2, cs=(&w16); rr!=w21+3; rr+=1) *rr += *cs++;
  /* #802: @3 = vertcat(@50, @46, @42, @11, @35, @29, @9, @21, @40, @44, @48) */
  rr=w03;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w09; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<3; ++i) *rr++ = *cs++;
  /* #803: (@64[6, 7, 8, 15, 16, 17, 24, 25, 26, 33, 34, 35, 42, 43, 44, 57, 58, 59, 75, 76, 77, 93, 94, 95, 60, 61, 62, 78, 79, 80, 96, 97, 98] = @3) */
  for (cii=casadi_s16, rr=w64, cs=w03; cii!=casadi_s16+33; ++cii, ++cs) rr[*cii] = *cs;
  /* #804: (@64[2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 53, 59, 65, 71, 77, 83, 89, 95, 101, 107, 113, 119, 125, 131, 137, 143, 149] = @3) */
  for (cii=casadi_s17, rr=w64, cs=w03; cii!=casadi_s17+33; ++cii, ++cs) rr[*cii] = *cs;
  /* #805: @69 = zeros(3x1,0nz) */
  /* #806: @50 = ones(33x1,3nz) */
  casadi_fill(w50, 3, 1.);
  /* #807: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @16, @32, @14} = vertsplit(@50) */
  w16 = w50[0];
  w32 = w50[1];
  w14 = w50[2];
  /* #808: @16 = @16' */
  /* #809: @50 = mac(@16,@10,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w16), casadi_s2, wr10, casadi_s1, w50, casadi_s0, w, 0);
  /* #810: @50 = @50' */
  /* #811: @46 = mac(@16,@59,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w16), casadi_s2, w59, casadi_s1, w46, casadi_s0, w, 0);
  /* #812: @46 = @46' */
  /* #813: @50 = (@50+@46) */
  for (i=0, rr=w50, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #814: @46 = (-@50) */
  for (i=0, rr=w46, cs=w50; i<3; ++i) *rr++ = (- *cs++ );
  /* #815: @61 = mac(@46,@41,@37) */
  casadi_copy(w37, 9, w61);
  for (i=0, rr=w61; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w46+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #816: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<9; ++i) *rr++ = (- *cs++ );
  /* #817: @46 = mac(@61,@2,@36) */
  casadi_copy(w36, 3, w46);
  for (i=0, rr=w46; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w61+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #818: @42 = mac(@38,@61,@1) */
  casadi_copy(w01, 3, w42);
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #819: @42 = @42' */
  /* #820: @46 = (@46+@42) */
  for (i=0, rr=w46, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #821: @32 = @32' */
  /* #822: @42 = mac(@32,@10,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w32), casadi_s2, wr10, casadi_s1, w42, casadi_s0, w, 0);
  /* #823: @42 = @42' */
  /* #824: @11 = mac(@32,@59,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w32), casadi_s2, w59, casadi_s1, w11, casadi_s0, w, 0);
  /* #825: @11 = @11' */
  /* #826: @42 = (@42+@11) */
  for (i=0, rr=w42, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #827: @11 = (-@42) */
  for (i=0, rr=w11, cs=w42; i<3; ++i) *rr++ = (- *cs++ );
  /* #828: @61 = mac(@11,@45,@37) */
  casadi_copy(w37, 9, w61);
  for (i=0, rr=w61; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #829: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<9; ++i) *rr++ = (- *cs++ );
  /* #830: @11 = mac(@61,@20,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w61+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #831: @35 = mac(@43,@61,@1) */
  casadi_copy(w01, 3, w35);
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #832: @35 = @35' */
  /* #833: @11 = (@11+@35) */
  for (i=0, rr=w11, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #834: @14 = @14' */
  /* #835: @35 = mac(@14,@10,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes((&w14), casadi_s2, wr10, casadi_s1, w35, casadi_s0, w, 0);
  /* #836: @35 = @35' */
  /* #837: @29 = mac(@14,@59,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes((&w14), casadi_s2, w59, casadi_s1, w29, casadi_s0, w, 0);
  /* #838: @29 = @29' */
  /* #839: @35 = (@35+@29) */
  for (i=0, rr=w35, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #840: @29 = (-@35) */
  for (i=0, rr=w29, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #841: @61 = mac(@29,@49,@37) */
  casadi_copy(w37, 9, w61);
  for (i=0, rr=w61; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #842: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<9; ++i) *rr++ = (- *cs++ );
  /* #843: @29 = mac(@61,@27,@36) */
  casadi_copy(w36, 3, w29);
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w61+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #844: @9 = mac(@47,@61,@1) */
  casadi_copy(w01, 3, w09);
  for (i=0, rr=w09; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #845: @9 = @9' */
  /* #846: @29 = (@29+@9) */
  for (i=0, rr=w29, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #847: @71 = vertcat(@69, @69, @69, @69, @69, @46, @11, @29, @50, @42, @35) */
  rr=w71;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  /* #848: @72 = @71[:18] */
  for (rr=w72, cs=w71+0; cs!=w71+18; cs+=1) *rr++ = *cs;
  /* #849: (@64[99, 100, 101, 117, 118, 119, 135, 136, 137, 102, 103, 104, 120, 121, 122, 138, 139, 140] = @72) */
  for (cii=casadi_s18, rr=w64, cs=w72; cii!=casadi_s18+18; ++cii, ++cs) rr[*cii] = *cs;
  /* #850: (@64[48:156:6] = @72) */
  for (rr=w64+48, cs=w72; rr!=w64+156; rr+=6) *rr = *cs++;
  /* #851: @46 = ones(33x1,3nz) */
  casadi_fill(w46, 3, 1.);
  /* #852: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @14, @32, @16} = vertsplit(@46) */
  w14 = w46[0];
  w32 = w46[1];
  w16 = w46[2];
  /* #853: @14 = @14' */
  /* #854: @46 = mac(@14,@10,@1) */
  casadi_copy(w01, 3, w46);
  casadi_mtimes((&w14), casadi_s8, wr10, casadi_s1, w46, casadi_s0, w, 0);
  /* #855: @46 = @46' */
  /* #856: @11 = mac(@14,@59,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w14), casadi_s8, w59, casadi_s1, w11, casadi_s0, w, 0);
  /* #857: @11 = @11' */
  /* #858: @46 = (@46+@11) */
  for (i=0, rr=w46, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #859: @11 = (-@46) */
  for (i=0, rr=w11, cs=w46; i<3; ++i) *rr++ = (- *cs++ );
  /* #860: @61 = mac(@11,@41,@37) */
  casadi_copy(w37, 9, w61);
  for (i=0, rr=w61; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #861: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<9; ++i) *rr++ = (- *cs++ );
  /* #862: @11 = mac(@61,@2,@36) */
  casadi_copy(w36, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w61+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #863: @29 = mac(@38,@61,@1) */
  casadi_copy(w01, 3, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #864: @29 = @29' */
  /* #865: @11 = (@11+@29) */
  for (i=0, rr=w11, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #866: @32 = @32' */
  /* #867: @29 = mac(@32,@10,@1) */
  casadi_copy(w01, 3, w29);
  casadi_mtimes((&w32), casadi_s8, wr10, casadi_s1, w29, casadi_s0, w, 0);
  /* #868: @29 = @29' */
  /* #869: @50 = mac(@32,@59,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w32), casadi_s8, w59, casadi_s1, w50, casadi_s0, w, 0);
  /* #870: @50 = @50' */
  /* #871: @29 = (@29+@50) */
  for (i=0, rr=w29, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #872: @50 = (-@29) */
  for (i=0, rr=w50, cs=w29; i<3; ++i) *rr++ = (- *cs++ );
  /* #873: @61 = mac(@50,@45,@37) */
  casadi_copy(w37, 9, w61);
  for (i=0, rr=w61; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w50+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #874: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<9; ++i) *rr++ = (- *cs++ );
  /* #875: @50 = mac(@61,@20,@36) */
  casadi_copy(w36, 3, w50);
  for (i=0, rr=w50; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w61+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #876: @42 = mac(@43,@61,@1) */
  casadi_copy(w01, 3, w42);
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #877: @42 = @42' */
  /* #878: @50 = (@50+@42) */
  for (i=0, rr=w50, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #879: @16 = @16' */
  /* #880: @42 = mac(@16,@10,@1) */
  casadi_copy(w01, 3, w42);
  casadi_mtimes((&w16), casadi_s8, wr10, casadi_s1, w42, casadi_s0, w, 0);
  /* #881: @42 = @42' */
  /* #882: @35 = mac(@16,@59,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes((&w16), casadi_s8, w59, casadi_s1, w35, casadi_s0, w, 0);
  /* #883: @35 = @35' */
  /* #884: @42 = (@42+@35) */
  for (i=0, rr=w42, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #885: @35 = (-@42) */
  for (i=0, rr=w35, cs=w42; i<3; ++i) *rr++ = (- *cs++ );
  /* #886: @61 = mac(@35,@49,@37) */
  casadi_copy(w37, 9, w61);
  for (i=0, rr=w61; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w35+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #887: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<9; ++i) *rr++ = (- *cs++ );
  /* #888: @35 = mac(@61,@27,@36) */
  casadi_copy(w36, 3, w35);
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w61+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #889: @9 = mac(@47,@61,@1) */
  casadi_copy(w01, 3, w09);
  for (i=0, rr=w09; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #890: @9 = @9' */
  /* #891: @35 = (@35+@9) */
  for (i=0, rr=w35, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #892: @72 = vertcat(@69, @69, @69, @69, @69, @11, @50, @35, @46, @29, @42) */
  rr=w72;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  /* #893: @71 = @72[:18] */
  for (rr=w71, cs=w72+0; cs!=w72+18; cs+=1) *rr++ = *cs;
  /* #894: (@64[105, 106, 107, 123, 124, 125, 141, 142, 143, 108, 109, 110, 126, 127, 128, 144, 145, 146] = @71) */
  for (cii=casadi_s19, rr=w64, cs=w71; cii!=casadi_s19+18; ++cii, ++cs) rr[*cii] = *cs;
  /* #895: (@64[49:157:6] = @71) */
  for (rr=w64+49, cs=w71; rr!=w64+157; rr+=6) *rr = *cs++;
  /* #896: @11 = ones(33x1,3nz) */
  casadi_fill(w11, 3, 1.);
  /* #897: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @16, @32, @14} = vertsplit(@11) */
  w16 = w11[0];
  w32 = w11[1];
  w14 = w11[2];
  /* #898: @16 = @16' */
  /* #899: @11 = mac(@16,@10,@1) */
  casadi_copy(w01, 3, w11);
  casadi_mtimes((&w16), casadi_s13, wr10, casadi_s1, w11, casadi_s0, w, 0);
  /* #900: @11 = @11' */
  /* #901: @50 = mac(@16,@59,@1) */
  casadi_copy(w01, 3, w50);
  casadi_mtimes((&w16), casadi_s13, w59, casadi_s1, w50, casadi_s0, w, 0);
  /* #902: @50 = @50' */
  /* #903: @11 = (@11+@50) */
  for (i=0, rr=w11, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #904: @50 = (-@11) */
  for (i=0, rr=w50, cs=w11; i<3; ++i) *rr++ = (- *cs++ );
  /* #905: @61 = mac(@50,@41,@37) */
  casadi_copy(w37, 9, w61);
  for (i=0, rr=w61; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w50+j, ct=wr41+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #906: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<9; ++i) *rr++ = (- *cs++ );
  /* #907: @50 = mac(@61,@2,@36) */
  casadi_copy(w36, 3, w50);
  for (i=0, rr=w50; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w61+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #908: @2 = mac(@38,@61,@1) */
  casadi_copy(w01, 3, w02);
  for (i=0, rr=w02; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #909: @2 = @2' */
  /* #910: @50 = (@50+@2) */
  for (i=0, rr=w50, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #911: @32 = @32' */
  /* #912: @2 = mac(@32,@10,@1) */
  casadi_copy(w01, 3, w02);
  casadi_mtimes((&w32), casadi_s13, wr10, casadi_s1, w02, casadi_s0, w, 0);
  /* #913: @2 = @2' */
  /* #914: @38 = mac(@32,@59,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w32), casadi_s13, w59, casadi_s1, w38, casadi_s0, w, 0);
  /* #915: @38 = @38' */
  /* #916: @2 = (@2+@38) */
  for (i=0, rr=w02, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #917: @38 = (-@2) */
  for (i=0, rr=w38, cs=w02; i<3; ++i) *rr++ = (- *cs++ );
  /* #918: @61 = mac(@38,@45,@37) */
  casadi_copy(w37, 9, w61);
  for (i=0, rr=w61; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w38+j, ct=wr45+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #919: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<9; ++i) *rr++ = (- *cs++ );
  /* #920: @38 = mac(@61,@20,@36) */
  casadi_copy(w36, 3, w38);
  for (i=0, rr=w38; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w61+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #921: @20 = mac(@43,@61,@1) */
  casadi_copy(w01, 3, w20);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #922: @20 = @20' */
  /* #923: @38 = (@38+@20) */
  for (i=0, rr=w38, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #924: @14 = @14' */
  /* #925: @20 = mac(@14,@10,@1) */
  casadi_copy(w01, 3, w20);
  casadi_mtimes((&w14), casadi_s13, wr10, casadi_s1, w20, casadi_s0, w, 0);
  /* #926: @20 = @20' */
  /* #927: @43 = mac(@14,@59,@1) */
  casadi_copy(w01, 3, w43);
  casadi_mtimes((&w14), casadi_s13, w59, casadi_s1, w43, casadi_s0, w, 0);
  /* #928: @43 = @43' */
  /* #929: @20 = (@20+@43) */
  for (i=0, rr=w20, cs=w43; i<3; ++i) (*rr++) += (*cs++);
  /* #930: @43 = (-@20) */
  for (i=0, rr=w43, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #931: @37 = mac(@43,@49,@37) */
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w43+j, ct=wr49+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #932: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<9; ++i) *rr++ = (- *cs++ );
  /* #933: @36 = mac(@37,@27,@36) */
  for (i=0, rr=w36; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w37+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #934: @1 = mac(@47,@37,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w37+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #935: @1 = @1' */
  /* #936: @36 = (@36+@1) */
  for (i=0, rr=w36, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #937: @71 = vertcat(@69, @69, @69, @69, @69, @50, @38, @36, @11, @2, @20) */
  rr=w71;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  /* #938: @72 = @71[:18] */
  for (rr=w72, cs=w71+0; cs!=w71+18; cs+=1) *rr++ = *cs;
  /* #939: (@64[111, 112, 113, 129, 130, 131, 147, 148, 149, 114, 115, 116, 132, 133, 134, 150, 151, 152] = @72) */
  for (cii=casadi_s20, rr=w64, cs=w72; cii!=casadi_s20+18; ++cii, ++cs) rr[*cii] = *cs;
  /* #940: (@64[50:158:6] = @72) */
  for (rr=w64+50, cs=w72; rr!=w64+158; rr+=6) *rr = *cs++;
  /* #941: @73 = @64' */
  casadi_trans(w64,casadi_s21, w73, casadi_s21, iw);
  /* #942: output[2][0] = @73 */
  casadi_copy(w73, 153, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s22;
    case 1: return casadi_s23;
    case 2: return casadi_s24;
    case 3: return casadi_s25;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s26;
    case 1: return casadi_s25;
    case 2: return casadi_s21;
    case 3: return casadi_s27;
    case 4: return casadi_s28;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 34;
  if (sz_w) *sz_w = 634;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 16*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 34*sizeof(casadi_int);
  if (sz_w) *sz_w = 634*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
