/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_pointmass_multiple_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[18] = 
  {6, 3, 0, 4, 8, 12, 0, 3,
  4, 5, 1, 3, 4, 5, 2, 3,
  4, 5};
static const casadi_int casadi_s1[21] = 
  {3, 6, 0, 1, 2, 3, 6, 9,
  12, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2};
static const casadi_int casadi_s2[39] = 
  {6, 6, 0, 4, 8, 12, 18, 24,
  30, 0, 3, 4, 5, 1, 3, 4,
  5, 2, 3, 4, 5, 0, 1, 2,
  3, 4, 5, 0, 1, 2, 3, 4,
  5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[6] = {0, 4, 5, 1, 2, 3};
static const casadi_int casadi_s4[6] = {0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[27] = 
  {6, 6, 0, 4, 8, 12, 15, 17,
  18, 0, 1, 2, 3, 1, 2, 3,
  4, 2, 3, 4, 5, 3, 4, 5,
  4, 5, 5};
static const casadi_int casadi_s6[30] = 
  {6, 6, 0, 1, 3, 6, 10, 15,
  21, 0, 0, 1, 0, 1, 2, 0,
  1, 2, 3, 0, 1, 2, 3, 4,
  0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[3] = {24, 1, 1};
static const casadi_int casadi_s8[3] = {9, 1, 1};
static const casadi_int casadi_s9[3] = {0, 1, 1};
static const casadi_int casadi_s10[3] = {33, 1, 1};
static const casadi_int casadi_s11[3] = {6, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -1.9620000000000002e+00};

/* planner_payload_pointmass_multiple_constr_h_fun:(i0[24],i1[9],i2[0],i3[33])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+6, w01, *w02=w+10, *w03=w+13, *w04=w+16, *w05=w+19, w06, w07, w08, w09, *w10=w+26;
  casadi_real *w11=w+32, *w12=w+44, *w13=w+56, *w14=w+62, *w15=w+68, *w16=w+74, *w17=w+104;
  const casadi_real *cs, *ss;
  /* #0: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w00);
  /* #1: @1 = dot(@0, @0) */
  w01 = casadi_dot(3, w00, w00);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: @2 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+9 : 0, 3, w02);
  /* #4: @1 = dot(@2, @2) */
  w01 = casadi_dot(3, w02, w02);
  /* #5: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #6: @3 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+12 : 0, 3, w03);
  /* #7: @1 = dot(@3, @3) */
  w01 = casadi_dot(3, w03, w03);
  /* #8: output[0][2] = @1 */
  if (res[0]) res[0][2] = w01;
  /* #9: @4 = [-0, -0, -1.962] */
  casadi_copy(casadi_c0, 3, w04);
  /* #10: @5 = input[1][0] */
  casadi_copy(arg[1], 3, w05);
  /* #11: @1 = dot(@0, @5) */
  w01 = casadi_dot(3, w00, w05);
  /* #12: @6 = 0.77 */
  w06 = 7.7000000000000002e-01;
  /* #13: @5 = input[0][5] */
  casadi_copy(arg[0] ? arg[0]+15 : 0, 3, w05);
  /* #14: @7 = dot(@5, @5) */
  w07 = casadi_dot(3, w05, w05);
  /* #15: @7 = (@6*@7) */
  w07  = (w06*w07);
  /* #16: @1 = (@1-@7) */
  w01 -= w07;
  /* #17: @5 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+3 : 0, 3, w05);
  /* #18: @7 = dot(@2, @5) */
  w07 = casadi_dot(3, w02, w05);
  /* #19: @5 = input[0][6] */
  casadi_copy(arg[0] ? arg[0]+18 : 0, 3, w05);
  /* #20: @8 = dot(@5, @5) */
  w08 = casadi_dot(3, w05, w05);
  /* #21: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #22: @7 = (@7-@8) */
  w07 -= w08;
  /* #23: @5 = input[1][2] */
  casadi_copy(arg[1] ? arg[1]+6 : 0, 3, w05);
  /* #24: @8 = dot(@3, @5) */
  w08 = casadi_dot(3, w03, w05);
  /* #25: @5 = input[0][7] */
  casadi_copy(arg[0] ? arg[0]+21 : 0, 3, w05);
  /* #26: @9 = dot(@5, @5) */
  w09 = casadi_dot(3, w05, w05);
  /* #27: @6 = (@6*@9) */
  w06 *= w09;
  /* #28: @8 = (@8-@6) */
  w08 -= w06;
  /* #29: @10 = vertcat(@4, @1, @7, @8) */
  rr=w10;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w01;
  *rr++ = w07;
  *rr++ = w08;
  /* #30: @4 = all_0.2(3x3,3nz) */
  casadi_fill(w04, 3, 2.0000000000000001e-01);
  /* #31: @11 = horzcat(@4, @0, @2, @3) */
  rr=w11;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  /* #32: @12 = @11' */
  casadi_trans(w11,casadi_s1, w12, casadi_s0, iw);
  /* #33: @0 = @0' */
  /* #34: @1 = 0 */
  w01 = 0.;
  /* #35: @13 = horzcat(@0, @1, @1, @1) */
  rr=w13;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  *rr++ = w01;
  *rr++ = w01;
  *rr++ = w01;
  /* #36: @13 = @13' */
  /* #37: @2 = @2' */
  /* #38: @14 = horzcat(@2, @1, @1, @1) */
  rr=w14;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  *rr++ = w01;
  *rr++ = w01;
  *rr++ = w01;
  /* #39: @14 = @14' */
  /* #40: @3 = @3' */
  /* #41: @15 = horzcat(@3, @1, @1, @1) */
  rr=w15;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  *rr++ = w01;
  *rr++ = w01;
  *rr++ = w01;
  /* #42: @15 = @15' */
  /* #43: @16 = horzcat(@12, @13, @14, @15) */
  rr=w16;
  for (i=0, cs=w12; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<6; ++i) *rr++ = *cs++;
  /* #44: @17 = @16' */
  casadi_trans(w16,casadi_s2, w17, casadi_s2, iw);
  /* #45: @10 = (@17\@10) */
  rr = w10;
  ss = w17;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[18], r[21], beta[6], w[12];
    casadi_qr(casadi_s2, ss, w, casadi_s5, v, casadi_s6, r, beta, casadi_s3, casadi_s4);
    casadi_qr_solve(rr, 1, 0, casadi_s5, v, casadi_s6, r, beta, casadi_s3, casadi_s4, w);
  }
  /* #46: @3 = @10[3:6] */
  for (rr=w03, cs=w10+3; cs!=w10+6; cs+=1) *rr++ = *cs;
  /* #47: output[0][3] = @3 */
  if (res[0]) casadi_copy(w03, 3, res[0]+3);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_pointmass_multiple_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 134;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 7*sizeof(casadi_int);
  if (sz_w) *sz_w = 134*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
