/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[18] = 
  {6, 3, 0, 4, 8, 12, 0, 3,
  4, 5, 1, 3, 4, 5, 2, 3,
  4, 5};
static const casadi_int casadi_s1[21] = 
  {3, 6, 0, 1, 2, 3, 6, 9,
  12, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2};
static const casadi_int casadi_s2[39] = 
  {6, 6, 0, 4, 8, 12, 18, 24,
  30, 0, 3, 4, 5, 1, 3, 4,
  5, 2, 3, 4, 5, 0, 1, 2,
  3, 4, 5, 0, 1, 2, 3, 4,
  5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[6] = {0, 4, 5, 1, 2, 3};
static const casadi_int casadi_s4[6] = {0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[27] = 
  {6, 6, 0, 4, 8, 12, 15, 17,
  18, 0, 1, 2, 3, 1, 2, 3,
  4, 2, 3, 4, 5, 3, 4, 5,
  4, 5, 5};
static const casadi_int casadi_s6[30] = 
  {6, 6, 0, 1, 3, 6, 10, 15,
  21, 0, 0, 1, 0, 1, 2, 0,
  1, 2, 3, 0, 1, 2, 3, 4,
  0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[15] = 
  {1, 6, 0, 1, 2, 3, 4, 5,
  6, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s8[10] = 
  {6, 1, 0, 6, 0, 1, 2, 3,
  4, 5};
static const casadi_int casadi_s9[3] = {24, 1, 1};
static const casadi_int casadi_s10[3] = {9, 1, 1};
static const casadi_int casadi_s11[3] = {0, 1, 1};
static const casadi_int casadi_s12[3] = {33, 1, 1};
static const casadi_int casadi_s13[3] = {6, 1, 1};
static const casadi_int casadi_s14[99] = 
  {33, 6, 0, 3, 6, 9, 36, 63,
  90, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 15, 16, 17, 18, 19,
  20, 21, 22, 23, 24, 25, 26, 27,
  28, 29, 30, 31, 32, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 15, 16,
  17, 18, 19, 20, 21, 22, 23, 24,
  25, 26, 27, 28, 29, 30, 31, 32,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29,
  30, 31, 32};
static const casadi_int casadi_s15[3] = {6, 0, 1};

static const casadi_real casadi_c0[3] = {0., 0., -1.9620000000000002e+00};

/* planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt:(i0[24],i1[9],i2[0],i3[33])->(o0[6],o1[33x6,90nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+6, w01, *w02=w+10, *w03=w+13, *w04=w+16, *w05=w+19, w06, *w07=w+23, w08, *w09=w+27, *w10=w+30;
  casadi_real w11, *w12=w+34, *w13=w+37, w14, *w15=w+41, *w16=w+47, *w17=w+59, *w18=w+71, *w19=w+77, *w20=w+83, *w21=w+89, *w22=w+119;
  casadi_real *w23=w+149, *w24=w+239, *w25=w+257, *w26=w+287, *w27=w+293, *w28=w+299, *w29=w+302, *w30=w+305;
  const casadi_real *cs, *ss;
  /* #0: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w00);
  /* #1: @1 = dot(@0, @0) */
  w01 = casadi_dot(3, w00, w00);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: @2 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+9 : 0, 3, w02);
  /* #4: @1 = dot(@2, @2) */
  w01 = casadi_dot(3, w02, w02);
  /* #5: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #6: @3 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+12 : 0, 3, w03);
  /* #7: @1 = dot(@3, @3) */
  w01 = casadi_dot(3, w03, w03);
  /* #8: output[0][2] = @1 */
  if (res[0]) res[0][2] = w01;
  /* #9: @4 = [-0, -0, -1.962] */
  casadi_copy(casadi_c0, 3, w04);
  /* #10: @5 = input[1][0] */
  casadi_copy(arg[1], 3, w05);
  /* #11: @1 = dot(@0, @5) */
  w01 = casadi_dot(3, w00, w05);
  /* #12: @6 = 0.77 */
  w06 = 7.7000000000000002e-01;
  /* #13: @7 = input[0][5] */
  casadi_copy(arg[0] ? arg[0]+15 : 0, 3, w07);
  /* #14: @8 = dot(@7, @7) */
  w08 = casadi_dot(3, w07, w07);
  /* #15: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #16: @1 = (@1-@8) */
  w01 -= w08;
  /* #17: @9 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+3 : 0, 3, w09);
  /* #18: @8 = dot(@2, @9) */
  w08 = casadi_dot(3, w02, w09);
  /* #19: @10 = input[0][6] */
  casadi_copy(arg[0] ? arg[0]+18 : 0, 3, w10);
  /* #20: @11 = dot(@10, @10) */
  w11 = casadi_dot(3, w10, w10);
  /* #21: @11 = (@6*@11) */
  w11  = (w06*w11);
  /* #22: @8 = (@8-@11) */
  w08 -= w11;
  /* #23: @12 = input[1][2] */
  casadi_copy(arg[1] ? arg[1]+6 : 0, 3, w12);
  /* #24: @11 = dot(@3, @12) */
  w11 = casadi_dot(3, w03, w12);
  /* #25: @13 = input[0][7] */
  casadi_copy(arg[0] ? arg[0]+21 : 0, 3, w13);
  /* #26: @14 = dot(@13, @13) */
  w14 = casadi_dot(3, w13, w13);
  /* #27: @14 = (@6*@14) */
  w14  = (w06*w14);
  /* #28: @11 = (@11-@14) */
  w11 -= w14;
  /* #29: @15 = vertcat(@4, @1, @8, @11) */
  rr=w15;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w01;
  *rr++ = w08;
  *rr++ = w11;
  /* #30: @4 = all_0.2(3x3,3nz) */
  casadi_fill(w04, 3, 2.0000000000000001e-01);
  /* #31: @16 = horzcat(@4, @0, @2, @3) */
  rr=w16;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  /* #32: @17 = @16' */
  casadi_trans(w16,casadi_s1, w17, casadi_s0, iw);
  /* #33: @4 = @0' */
  casadi_copy(w00, 3, w04);
  /* #34: @1 = 0 */
  w01 = 0.;
  /* #35: @18 = horzcat(@4, @1, @1, @1) */
  rr=w18;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w01;
  *rr++ = w01;
  *rr++ = w01;
  /* #36: @18 = @18' */
  /* #37: @4 = @2' */
  casadi_copy(w02, 3, w04);
  /* #38: @19 = horzcat(@4, @1, @1, @1) */
  rr=w19;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w01;
  *rr++ = w01;
  *rr++ = w01;
  /* #39: @19 = @19' */
  /* #40: @4 = @3' */
  casadi_copy(w03, 3, w04);
  /* #41: @20 = horzcat(@4, @1, @1, @1) */
  rr=w20;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w01;
  *rr++ = w01;
  *rr++ = w01;
  /* #42: @20 = @20' */
  /* #43: @21 = horzcat(@17, @18, @19, @20) */
  rr=w21;
  for (i=0, cs=w17; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<6; ++i) *rr++ = *cs++;
  /* #44: @22 = @21' */
  casadi_trans(w21,casadi_s2, w22, casadi_s2, iw);
  /* #45: @15 = (@22\@15) */
  rr = w15;
  ss = w22;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[18], r[21], beta[6], w[12];
    casadi_qr(casadi_s2, ss, w, casadi_s5, v, casadi_s6, r, beta, casadi_s3, casadi_s4);
    casadi_qr_solve(rr, 1, 0, casadi_s5, v, casadi_s6, r, beta, casadi_s3, casadi_s4, w);
  }
  /* #46: @4 = @15[3:6] */
  for (rr=w04, cs=w15+3; cs!=w15+6; cs+=1) *rr++ = *cs;
  /* #47: output[0][3] = @4 */
  if (res[0]) casadi_copy(w04, 3, res[0]+3);
  /* #48: @23 = zeros(33x6,90nz) */
  casadi_clear(w23, 90);
  /* #49: @4 = ones(6x1,3nz) */
  casadi_fill(w04, 3, 1.);
  /* #50: {@1, @8, @11, NULL} = vertsplit(@4) */
  w01 = w04[0];
  w08 = w04[1];
  w11 = w04[2];
  /* #51: @4 = (@1*@0) */
  for (i=0, rr=w04, cs=w00; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #52: @4 = (2.*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #53: @1 = @4[0] */
  for (rr=(&w01), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #54: (@23[0] = @1) */
  for (rr=w23+0, cs=(&w01); rr!=w23+1; rr+=1) *rr = *cs++;
  /* #55: @1 = @4[1] */
  for (rr=(&w01), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #56: (@23[1] = @1) */
  for (rr=w23+1, cs=(&w01); rr!=w23+2; rr+=1) *rr = *cs++;
  /* #57: @1 = @4[2] */
  for (rr=(&w01), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #58: (@23[2] = @1) */
  for (rr=w23+2, cs=(&w01); rr!=w23+3; rr+=1) *rr = *cs++;
  /* #59: @4 = (@8*@2) */
  for (i=0, rr=w04, cs=w02; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #60: @4 = (2.*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #61: @8 = @4[0] */
  for (rr=(&w08), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #62: (@23[3] = @8) */
  for (rr=w23+3, cs=(&w08); rr!=w23+4; rr+=1) *rr = *cs++;
  /* #63: @8 = @4[1] */
  for (rr=(&w08), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #64: (@23[4] = @8) */
  for (rr=w23+4, cs=(&w08); rr!=w23+5; rr+=1) *rr = *cs++;
  /* #65: @8 = @4[2] */
  for (rr=(&w08), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #66: (@23[5] = @8) */
  for (rr=w23+5, cs=(&w08); rr!=w23+6; rr+=1) *rr = *cs++;
  /* #67: @4 = (@11*@3) */
  for (i=0, rr=w04, cs=w03; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #68: @4 = (2.*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #69: @11 = @4[0] */
  for (rr=(&w11), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #70: (@23[6] = @11) */
  for (rr=w23+6, cs=(&w11); rr!=w23+7; rr+=1) *rr = *cs++;
  /* #71: @11 = @4[1] */
  for (rr=(&w11), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #72: (@23[7] = @11) */
  for (rr=w23+7, cs=(&w11); rr!=w23+8; rr+=1) *rr = *cs++;
  /* #73: @11 = @4[2] */
  for (rr=(&w11), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #74: (@23[8] = @11) */
  for (rr=w23+8, cs=(&w11); rr!=w23+9; rr+=1) *rr = *cs++;
  /* #75: @18 = zeros(6x1) */
  casadi_clear(w18, 6);
  /* #76: @11 = ones(6x1,1nz) */
  w11 = 1.;
  /* #77: {NULL, NULL, NULL, @8} = vertsplit(@11) */
  w08 = w11;
  /* #78: @19 = @18; (@19[3] += @8) */
  casadi_copy(w18, 6, w19);
  for (rr=w19+3, cs=(&w08); rr!=w19+4; rr+=1) *rr += *cs++;
  /* #79: @8 = ones(6x1,1nz) */
  w08 = 1.;
  /* #80: {NULL, NULL, NULL, @11} = vertsplit(@8) */
  w11 = w08;
  /* #81: @20 = @18; (@20[4] += @11) */
  casadi_copy(w18, 6, w20);
  for (rr=w20+4, cs=(&w11); rr!=w20+5; rr+=1) *rr += *cs++;
  /* #82: @11 = ones(6x1,1nz) */
  w11 = 1.;
  /* #83: {NULL, NULL, NULL, @8} = vertsplit(@11) */
  w08 = w11;
  /* #84: (@18[5] += @8) */
  for (rr=w18+5, cs=(&w08); rr!=w18+6; rr+=1) *rr += *cs++;
  /* #85: @24 = horzcat(@19, @20, @18) */
  rr=w24;
  for (i=0, cs=w19; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<6; ++i) *rr++ = *cs++;
  /* #86: @24 = (@22'\@24) */
  rr = w24;
  ss = w22;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[18], r[21], beta[6], w[12];
    casadi_qr(casadi_s2, ss, w, casadi_s5, v, casadi_s6, r, beta, casadi_s3, casadi_s4);
    casadi_qr_solve(rr, 3, 1, casadi_s5, v, casadi_s6, r, beta, casadi_s3, casadi_s4, w);
  }
  /* #87: {@19, @20, @18} = horzsplit(@24) */
  casadi_copy(w24, 6, w19);
  casadi_copy(w24+6, 6, w20);
  casadi_copy(w24+12, 6, w18);
  /* #88: {NULL, @8, @11, @1} = vertsplit(@19) */
  w08 = w19[3];
  w11 = w19[4];
  w01 = w19[5];
  /* #89: @4 = (@8*@0) */
  for (i=0, rr=w04, cs=w00; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #90: @14 = @4[0] */
  for (rr=(&w14), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #91: (@23[9] = @14) */
  for (rr=w23+9, cs=(&w14); rr!=w23+10; rr+=1) *rr = *cs++;
  /* #92: @14 = @4[1] */
  for (rr=(&w14), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #93: (@23[10] = @14) */
  for (rr=w23+10, cs=(&w14); rr!=w23+11; rr+=1) *rr = *cs++;
  /* #94: @14 = @4[2] */
  for (rr=(&w14), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #95: (@23[11] = @14) */
  for (rr=w23+11, cs=(&w14); rr!=w23+12; rr+=1) *rr = *cs++;
  /* #96: @4 = (@11*@2) */
  for (i=0, rr=w04, cs=w02; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #97: @14 = @4[0] */
  for (rr=(&w14), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #98: (@23[12] = @14) */
  for (rr=w23+12, cs=(&w14); rr!=w23+13; rr+=1) *rr = *cs++;
  /* #99: @14 = @4[1] */
  for (rr=(&w14), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #100: (@23[13] = @14) */
  for (rr=w23+13, cs=(&w14); rr!=w23+14; rr+=1) *rr = *cs++;
  /* #101: @14 = @4[2] */
  for (rr=(&w14), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #102: (@23[14] = @14) */
  for (rr=w23+14, cs=(&w14); rr!=w23+15; rr+=1) *rr = *cs++;
  /* #103: @4 = (@1*@3) */
  for (i=0, rr=w04, cs=w03; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #104: @14 = @4[0] */
  for (rr=(&w14), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #105: (@23[15] = @14) */
  for (rr=w23+15, cs=(&w14); rr!=w23+16; rr+=1) *rr = *cs++;
  /* #106: @14 = @4[1] */
  for (rr=(&w14), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #107: (@23[16] = @14) */
  for (rr=w23+16, cs=(&w14); rr!=w23+17; rr+=1) *rr = *cs++;
  /* #108: @14 = @4[2] */
  for (rr=(&w14), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #109: (@23[17] = @14) */
  for (rr=w23+17, cs=(&w14); rr!=w23+18; rr+=1) *rr = *cs++;
  /* #110: @22 = zeros(6x6,30nz) */
  casadi_clear(w22, 30);
  /* #111: @15 = @15' */
  /* #112: @21 = mac(@19,@15,@22) */
  casadi_copy(w22, 30, w21);
  casadi_mtimes(w19, casadi_s8, w15, casadi_s7, w21, casadi_s2, w, 0);
  /* #113: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<30; ++i) *rr++ = (- *cs++ );
  /* #114: @25 = @21' */
  casadi_trans(w21,casadi_s2, w25, casadi_s2, iw);
  /* #115: {@17, @19, @26, @27} = horzsplit(@25) */
  casadi_copy(w25, 12, w17);
  casadi_copy(w25+12, 6, w19);
  casadi_copy(w25+18, 6, w26);
  casadi_copy(w25+24, 6, w27);
  /* #116: @19 = @19' */
  /* #117: {@4, NULL, NULL, NULL} = horzsplit(@19) */
  casadi_copy(w19, 3, w04);
  /* #118: @4 = @4' */
  /* #119: @16 = @17' */
  casadi_trans(w17,casadi_s0, w16, casadi_s1, iw);
  /* #120: {NULL, @28, @29, @30} = horzsplit(@16) */
  casadi_copy(w16+3, 3, w28);
  casadi_copy(w16+6, 3, w29);
  casadi_copy(w16+9, 3, w30);
  /* #121: @4 = (@4+@28) */
  for (i=0, rr=w04, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #122: @28 = (@8*@5) */
  for (i=0, rr=w28, cs=w05; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #123: @4 = (@4+@28) */
  for (i=0, rr=w04, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #124: @14 = @4[0] */
  for (rr=(&w14), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #125: (@23[18] = @14) */
  for (rr=w23+18, cs=(&w14); rr!=w23+19; rr+=1) *rr = *cs++;
  /* #126: @14 = @4[1] */
  for (rr=(&w14), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #127: (@23[19] = @14) */
  for (rr=w23+19, cs=(&w14); rr!=w23+20; rr+=1) *rr = *cs++;
  /* #128: @14 = @4[2] */
  for (rr=(&w14), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #129: (@23[20] = @14) */
  for (rr=w23+20, cs=(&w14); rr!=w23+21; rr+=1) *rr = *cs++;
  /* #130: @26 = @26' */
  /* #131: {@4, NULL, NULL, NULL} = horzsplit(@26) */
  casadi_copy(w26, 3, w04);
  /* #132: @4 = @4' */
  /* #133: @4 = (@4+@29) */
  for (i=0, rr=w04, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #134: @29 = (@11*@9) */
  for (i=0, rr=w29, cs=w09; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #135: @4 = (@4+@29) */
  for (i=0, rr=w04, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #136: @14 = @4[0] */
  for (rr=(&w14), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #137: (@23[21] = @14) */
  for (rr=w23+21, cs=(&w14); rr!=w23+22; rr+=1) *rr = *cs++;
  /* #138: @14 = @4[1] */
  for (rr=(&w14), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #139: (@23[22] = @14) */
  for (rr=w23+22, cs=(&w14); rr!=w23+23; rr+=1) *rr = *cs++;
  /* #140: @14 = @4[2] */
  for (rr=(&w14), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #141: (@23[23] = @14) */
  for (rr=w23+23, cs=(&w14); rr!=w23+24; rr+=1) *rr = *cs++;
  /* #142: @27 = @27' */
  /* #143: {@4, NULL, NULL, NULL} = horzsplit(@27) */
  casadi_copy(w27, 3, w04);
  /* #144: @4 = @4' */
  /* #145: @4 = (@4+@30) */
  for (i=0, rr=w04, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #146: @30 = (@1*@12) */
  for (i=0, rr=w30, cs=w12; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #147: @4 = (@4+@30) */
  for (i=0, rr=w04, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #148: @14 = @4[0] */
  for (rr=(&w14), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #149: (@23[24] = @14) */
  for (rr=w23+24, cs=(&w14); rr!=w23+25; rr+=1) *rr = *cs++;
  /* #150: @14 = @4[1] */
  for (rr=(&w14), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #151: (@23[25] = @14) */
  for (rr=w23+25, cs=(&w14); rr!=w23+26; rr+=1) *rr = *cs++;
  /* #152: @14 = @4[2] */
  for (rr=(&w14), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #153: (@23[26] = @14) */
  for (rr=w23+26, cs=(&w14); rr!=w23+27; rr+=1) *rr = *cs++;
  /* #154: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #155: @4 = (@8*@7) */
  for (i=0, rr=w04, cs=w07; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #156: @30 = (-@4) */
  for (i=0, rr=w30, cs=w04; i<3; ++i) *rr++ = (- *cs++ );
  /* #157: @30 = (@30-@4) */
  for (i=0, rr=w30, cs=w04; i<3; ++i) (*rr++) -= (*cs++);
  /* #158: @8 = @30[0] */
  for (rr=(&w08), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #159: (@23[27] = @8) */
  for (rr=w23+27, cs=(&w08); rr!=w23+28; rr+=1) *rr = *cs++;
  /* #160: @8 = @30[1] */
  for (rr=(&w08), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #161: (@23[28] = @8) */
  for (rr=w23+28, cs=(&w08); rr!=w23+29; rr+=1) *rr = *cs++;
  /* #162: @8 = @30[2] */
  for (rr=(&w08), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #163: (@23[29] = @8) */
  for (rr=w23+29, cs=(&w08); rr!=w23+30; rr+=1) *rr = *cs++;
  /* #164: @11 = (@6*@11) */
  w11  = (w06*w11);
  /* #165: @30 = (@11*@10) */
  for (i=0, rr=w30, cs=w10; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #166: @4 = (-@30) */
  for (i=0, rr=w04, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #167: @4 = (@4-@30) */
  for (i=0, rr=w04, cs=w30; i<3; ++i) (*rr++) -= (*cs++);
  /* #168: @11 = @4[0] */
  for (rr=(&w11), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #169: (@23[30] = @11) */
  for (rr=w23+30, cs=(&w11); rr!=w23+31; rr+=1) *rr = *cs++;
  /* #170: @11 = @4[1] */
  for (rr=(&w11), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #171: (@23[31] = @11) */
  for (rr=w23+31, cs=(&w11); rr!=w23+32; rr+=1) *rr = *cs++;
  /* #172: @11 = @4[2] */
  for (rr=(&w11), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #173: (@23[32] = @11) */
  for (rr=w23+32, cs=(&w11); rr!=w23+33; rr+=1) *rr = *cs++;
  /* #174: @1 = (@6*@1) */
  w01  = (w06*w01);
  /* #175: @4 = (@1*@13) */
  for (i=0, rr=w04, cs=w13; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #176: @30 = (-@4) */
  for (i=0, rr=w30, cs=w04; i<3; ++i) *rr++ = (- *cs++ );
  /* #177: @30 = (@30-@4) */
  for (i=0, rr=w30, cs=w04; i<3; ++i) (*rr++) -= (*cs++);
  /* #178: @1 = @30[0] */
  for (rr=(&w01), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #179: (@23[33] = @1) */
  for (rr=w23+33, cs=(&w01); rr!=w23+34; rr+=1) *rr = *cs++;
  /* #180: @1 = @30[1] */
  for (rr=(&w01), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #181: (@23[34] = @1) */
  for (rr=w23+34, cs=(&w01); rr!=w23+35; rr+=1) *rr = *cs++;
  /* #182: @1 = @30[2] */
  for (rr=(&w01), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #183: (@23[35] = @1) */
  for (rr=w23+35, cs=(&w01); rr!=w23+36; rr+=1) *rr = *cs++;
  /* #184: {NULL, @1, @11, @8} = vertsplit(@20) */
  w01 = w20[3];
  w11 = w20[4];
  w08 = w20[5];
  /* #185: @30 = (@1*@0) */
  for (i=0, rr=w30, cs=w00; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #186: @14 = @30[0] */
  for (rr=(&w14), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #187: (@23[36] = @14) */
  for (rr=w23+36, cs=(&w14); rr!=w23+37; rr+=1) *rr = *cs++;
  /* #188: @14 = @30[1] */
  for (rr=(&w14), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #189: (@23[37] = @14) */
  for (rr=w23+37, cs=(&w14); rr!=w23+38; rr+=1) *rr = *cs++;
  /* #190: @14 = @30[2] */
  for (rr=(&w14), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #191: (@23[38] = @14) */
  for (rr=w23+38, cs=(&w14); rr!=w23+39; rr+=1) *rr = *cs++;
  /* #192: @30 = (@11*@2) */
  for (i=0, rr=w30, cs=w02; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #193: @14 = @30[0] */
  for (rr=(&w14), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #194: (@23[39] = @14) */
  for (rr=w23+39, cs=(&w14); rr!=w23+40; rr+=1) *rr = *cs++;
  /* #195: @14 = @30[1] */
  for (rr=(&w14), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #196: (@23[40] = @14) */
  for (rr=w23+40, cs=(&w14); rr!=w23+41; rr+=1) *rr = *cs++;
  /* #197: @14 = @30[2] */
  for (rr=(&w14), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #198: (@23[41] = @14) */
  for (rr=w23+41, cs=(&w14); rr!=w23+42; rr+=1) *rr = *cs++;
  /* #199: @30 = (@8*@3) */
  for (i=0, rr=w30, cs=w03; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #200: @14 = @30[0] */
  for (rr=(&w14), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #201: (@23[42] = @14) */
  for (rr=w23+42, cs=(&w14); rr!=w23+43; rr+=1) *rr = *cs++;
  /* #202: @14 = @30[1] */
  for (rr=(&w14), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #203: (@23[43] = @14) */
  for (rr=w23+43, cs=(&w14); rr!=w23+44; rr+=1) *rr = *cs++;
  /* #204: @14 = @30[2] */
  for (rr=(&w14), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #205: (@23[44] = @14) */
  for (rr=w23+44, cs=(&w14); rr!=w23+45; rr+=1) *rr = *cs++;
  /* #206: @25 = mac(@20,@15,@22) */
  casadi_copy(w22, 30, w25);
  casadi_mtimes(w20, casadi_s8, w15, casadi_s7, w25, casadi_s2, w, 0);
  /* #207: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<30; ++i) *rr++ = (- *cs++ );
  /* #208: @21 = @25' */
  casadi_trans(w25,casadi_s2, w21, casadi_s2, iw);
  /* #209: {@16, @20, @27, @26} = horzsplit(@21) */
  casadi_copy(w21, 12, w16);
  casadi_copy(w21+12, 6, w20);
  casadi_copy(w21+18, 6, w27);
  casadi_copy(w21+24, 6, w26);
  /* #210: @20 = @20' */
  /* #211: {@30, NULL, NULL, NULL} = horzsplit(@20) */
  casadi_copy(w20, 3, w30);
  /* #212: @30 = @30' */
  /* #213: @17 = @16' */
  casadi_trans(w16,casadi_s0, w17, casadi_s1, iw);
  /* #214: {NULL, @4, @29, @28} = horzsplit(@17) */
  casadi_copy(w17+3, 3, w04);
  casadi_copy(w17+6, 3, w29);
  casadi_copy(w17+9, 3, w28);
  /* #215: @30 = (@30+@4) */
  for (i=0, rr=w30, cs=w04; i<3; ++i) (*rr++) += (*cs++);
  /* #216: @4 = (@1*@5) */
  for (i=0, rr=w04, cs=w05; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #217: @30 = (@30+@4) */
  for (i=0, rr=w30, cs=w04; i<3; ++i) (*rr++) += (*cs++);
  /* #218: @14 = @30[0] */
  for (rr=(&w14), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #219: (@23[45] = @14) */
  for (rr=w23+45, cs=(&w14); rr!=w23+46; rr+=1) *rr = *cs++;
  /* #220: @14 = @30[1] */
  for (rr=(&w14), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #221: (@23[46] = @14) */
  for (rr=w23+46, cs=(&w14); rr!=w23+47; rr+=1) *rr = *cs++;
  /* #222: @14 = @30[2] */
  for (rr=(&w14), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #223: (@23[47] = @14) */
  for (rr=w23+47, cs=(&w14); rr!=w23+48; rr+=1) *rr = *cs++;
  /* #224: @27 = @27' */
  /* #225: {@30, NULL, NULL, NULL} = horzsplit(@27) */
  casadi_copy(w27, 3, w30);
  /* #226: @30 = @30' */
  /* #227: @30 = (@30+@29) */
  for (i=0, rr=w30, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #228: @29 = (@11*@9) */
  for (i=0, rr=w29, cs=w09; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #229: @30 = (@30+@29) */
  for (i=0, rr=w30, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #230: @14 = @30[0] */
  for (rr=(&w14), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #231: (@23[48] = @14) */
  for (rr=w23+48, cs=(&w14); rr!=w23+49; rr+=1) *rr = *cs++;
  /* #232: @14 = @30[1] */
  for (rr=(&w14), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #233: (@23[49] = @14) */
  for (rr=w23+49, cs=(&w14); rr!=w23+50; rr+=1) *rr = *cs++;
  /* #234: @14 = @30[2] */
  for (rr=(&w14), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #235: (@23[50] = @14) */
  for (rr=w23+50, cs=(&w14); rr!=w23+51; rr+=1) *rr = *cs++;
  /* #236: @26 = @26' */
  /* #237: {@30, NULL, NULL, NULL} = horzsplit(@26) */
  casadi_copy(w26, 3, w30);
  /* #238: @30 = @30' */
  /* #239: @30 = (@30+@28) */
  for (i=0, rr=w30, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #240: @28 = (@8*@12) */
  for (i=0, rr=w28, cs=w12; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #241: @30 = (@30+@28) */
  for (i=0, rr=w30, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #242: @14 = @30[0] */
  for (rr=(&w14), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #243: (@23[51] = @14) */
  for (rr=w23+51, cs=(&w14); rr!=w23+52; rr+=1) *rr = *cs++;
  /* #244: @14 = @30[1] */
  for (rr=(&w14), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #245: (@23[52] = @14) */
  for (rr=w23+52, cs=(&w14); rr!=w23+53; rr+=1) *rr = *cs++;
  /* #246: @14 = @30[2] */
  for (rr=(&w14), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #247: (@23[53] = @14) */
  for (rr=w23+53, cs=(&w14); rr!=w23+54; rr+=1) *rr = *cs++;
  /* #248: @1 = (@6*@1) */
  w01  = (w06*w01);
  /* #249: @30 = (@1*@7) */
  for (i=0, rr=w30, cs=w07; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #250: @28 = (-@30) */
  for (i=0, rr=w28, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #251: @28 = (@28-@30) */
  for (i=0, rr=w28, cs=w30; i<3; ++i) (*rr++) -= (*cs++);
  /* #252: @1 = @28[0] */
  for (rr=(&w01), cs=w28+0; cs!=w28+1; cs+=1) *rr++ = *cs;
  /* #253: (@23[54] = @1) */
  for (rr=w23+54, cs=(&w01); rr!=w23+55; rr+=1) *rr = *cs++;
  /* #254: @1 = @28[1] */
  for (rr=(&w01), cs=w28+1; cs!=w28+2; cs+=1) *rr++ = *cs;
  /* #255: (@23[55] = @1) */
  for (rr=w23+55, cs=(&w01); rr!=w23+56; rr+=1) *rr = *cs++;
  /* #256: @1 = @28[2] */
  for (rr=(&w01), cs=w28+2; cs!=w28+3; cs+=1) *rr++ = *cs;
  /* #257: (@23[56] = @1) */
  for (rr=w23+56, cs=(&w01); rr!=w23+57; rr+=1) *rr = *cs++;
  /* #258: @11 = (@6*@11) */
  w11  = (w06*w11);
  /* #259: @28 = (@11*@10) */
  for (i=0, rr=w28, cs=w10; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #260: @30 = (-@28) */
  for (i=0, rr=w30, cs=w28; i<3; ++i) *rr++ = (- *cs++ );
  /* #261: @30 = (@30-@28) */
  for (i=0, rr=w30, cs=w28; i<3; ++i) (*rr++) -= (*cs++);
  /* #262: @11 = @30[0] */
  for (rr=(&w11), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #263: (@23[57] = @11) */
  for (rr=w23+57, cs=(&w11); rr!=w23+58; rr+=1) *rr = *cs++;
  /* #264: @11 = @30[1] */
  for (rr=(&w11), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #265: (@23[58] = @11) */
  for (rr=w23+58, cs=(&w11); rr!=w23+59; rr+=1) *rr = *cs++;
  /* #266: @11 = @30[2] */
  for (rr=(&w11), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #267: (@23[59] = @11) */
  for (rr=w23+59, cs=(&w11); rr!=w23+60; rr+=1) *rr = *cs++;
  /* #268: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #269: @30 = (@8*@13) */
  for (i=0, rr=w30, cs=w13; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #270: @28 = (-@30) */
  for (i=0, rr=w28, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #271: @28 = (@28-@30) */
  for (i=0, rr=w28, cs=w30; i<3; ++i) (*rr++) -= (*cs++);
  /* #272: @8 = @28[0] */
  for (rr=(&w08), cs=w28+0; cs!=w28+1; cs+=1) *rr++ = *cs;
  /* #273: (@23[60] = @8) */
  for (rr=w23+60, cs=(&w08); rr!=w23+61; rr+=1) *rr = *cs++;
  /* #274: @8 = @28[1] */
  for (rr=(&w08), cs=w28+1; cs!=w28+2; cs+=1) *rr++ = *cs;
  /* #275: (@23[61] = @8) */
  for (rr=w23+61, cs=(&w08); rr!=w23+62; rr+=1) *rr = *cs++;
  /* #276: @8 = @28[2] */
  for (rr=(&w08), cs=w28+2; cs!=w28+3; cs+=1) *rr++ = *cs;
  /* #277: (@23[62] = @8) */
  for (rr=w23+62, cs=(&w08); rr!=w23+63; rr+=1) *rr = *cs++;
  /* #278: {NULL, @8, @11, @1} = vertsplit(@18) */
  w08 = w18[3];
  w11 = w18[4];
  w01 = w18[5];
  /* #279: @0 = (@8*@0) */
  for (i=0, rr=w00, cs=w00; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #280: @14 = @0[0] */
  for (rr=(&w14), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #281: (@23[63] = @14) */
  for (rr=w23+63, cs=(&w14); rr!=w23+64; rr+=1) *rr = *cs++;
  /* #282: @14 = @0[1] */
  for (rr=(&w14), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #283: (@23[64] = @14) */
  for (rr=w23+64, cs=(&w14); rr!=w23+65; rr+=1) *rr = *cs++;
  /* #284: @14 = @0[2] */
  for (rr=(&w14), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #285: (@23[65] = @14) */
  for (rr=w23+65, cs=(&w14); rr!=w23+66; rr+=1) *rr = *cs++;
  /* #286: @2 = (@11*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #287: @14 = @2[0] */
  for (rr=(&w14), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #288: (@23[66] = @14) */
  for (rr=w23+66, cs=(&w14); rr!=w23+67; rr+=1) *rr = *cs++;
  /* #289: @14 = @2[1] */
  for (rr=(&w14), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #290: (@23[67] = @14) */
  for (rr=w23+67, cs=(&w14); rr!=w23+68; rr+=1) *rr = *cs++;
  /* #291: @14 = @2[2] */
  for (rr=(&w14), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #292: (@23[68] = @14) */
  for (rr=w23+68, cs=(&w14); rr!=w23+69; rr+=1) *rr = *cs++;
  /* #293: @3 = (@1*@3) */
  for (i=0, rr=w03, cs=w03; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #294: @14 = @3[0] */
  for (rr=(&w14), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #295: (@23[69] = @14) */
  for (rr=w23+69, cs=(&w14); rr!=w23+70; rr+=1) *rr = *cs++;
  /* #296: @14 = @3[1] */
  for (rr=(&w14), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #297: (@23[70] = @14) */
  for (rr=w23+70, cs=(&w14); rr!=w23+71; rr+=1) *rr = *cs++;
  /* #298: @14 = @3[2] */
  for (rr=(&w14), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #299: (@23[71] = @14) */
  for (rr=w23+71, cs=(&w14); rr!=w23+72; rr+=1) *rr = *cs++;
  /* #300: @22 = mac(@18,@15,@22) */
  casadi_mtimes(w18, casadi_s8, w15, casadi_s7, w22, casadi_s2, w, 0);
  /* #301: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<30; ++i) *rr++ = (- *cs++ );
  /* #302: @21 = @22' */
  casadi_trans(w22,casadi_s2, w21, casadi_s2, iw);
  /* #303: {@17, @18, @15, @26} = horzsplit(@21) */
  casadi_copy(w21, 12, w17);
  casadi_copy(w21+12, 6, w18);
  casadi_copy(w21+18, 6, w15);
  casadi_copy(w21+24, 6, w26);
  /* #304: @18 = @18' */
  /* #305: {@3, NULL, NULL, NULL} = horzsplit(@18) */
  casadi_copy(w18, 3, w03);
  /* #306: @3 = @3' */
  /* #307: @16 = @17' */
  casadi_trans(w17,casadi_s0, w16, casadi_s1, iw);
  /* #308: {NULL, @2, @0, @28} = horzsplit(@16) */
  casadi_copy(w16+3, 3, w02);
  casadi_copy(w16+6, 3, w00);
  casadi_copy(w16+9, 3, w28);
  /* #309: @3 = (@3+@2) */
  for (i=0, rr=w03, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #310: @5 = (@8*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #311: @3 = (@3+@5) */
  for (i=0, rr=w03, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #312: @14 = @3[0] */
  for (rr=(&w14), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #313: (@23[72] = @14) */
  for (rr=w23+72, cs=(&w14); rr!=w23+73; rr+=1) *rr = *cs++;
  /* #314: @14 = @3[1] */
  for (rr=(&w14), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #315: (@23[73] = @14) */
  for (rr=w23+73, cs=(&w14); rr!=w23+74; rr+=1) *rr = *cs++;
  /* #316: @14 = @3[2] */
  for (rr=(&w14), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #317: (@23[74] = @14) */
  for (rr=w23+74, cs=(&w14); rr!=w23+75; rr+=1) *rr = *cs++;
  /* #318: @15 = @15' */
  /* #319: {@3, NULL, NULL, NULL} = horzsplit(@15) */
  casadi_copy(w15, 3, w03);
  /* #320: @3 = @3' */
  /* #321: @3 = (@3+@0) */
  for (i=0, rr=w03, cs=w00; i<3; ++i) (*rr++) += (*cs++);
  /* #322: @9 = (@11*@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #323: @3 = (@3+@9) */
  for (i=0, rr=w03, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #324: @14 = @3[0] */
  for (rr=(&w14), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #325: (@23[75] = @14) */
  for (rr=w23+75, cs=(&w14); rr!=w23+76; rr+=1) *rr = *cs++;
  /* #326: @14 = @3[1] */
  for (rr=(&w14), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #327: (@23[76] = @14) */
  for (rr=w23+76, cs=(&w14); rr!=w23+77; rr+=1) *rr = *cs++;
  /* #328: @14 = @3[2] */
  for (rr=(&w14), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #329: (@23[77] = @14) */
  for (rr=w23+77, cs=(&w14); rr!=w23+78; rr+=1) *rr = *cs++;
  /* #330: @26 = @26' */
  /* #331: {@3, NULL, NULL, NULL} = horzsplit(@26) */
  casadi_copy(w26, 3, w03);
  /* #332: @3 = @3' */
  /* #333: @3 = (@3+@28) */
  for (i=0, rr=w03, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #334: @12 = (@1*@12) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #335: @3 = (@3+@12) */
  for (i=0, rr=w03, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #336: @14 = @3[0] */
  for (rr=(&w14), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #337: (@23[78] = @14) */
  for (rr=w23+78, cs=(&w14); rr!=w23+79; rr+=1) *rr = *cs++;
  /* #338: @14 = @3[1] */
  for (rr=(&w14), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #339: (@23[79] = @14) */
  for (rr=w23+79, cs=(&w14); rr!=w23+80; rr+=1) *rr = *cs++;
  /* #340: @14 = @3[2] */
  for (rr=(&w14), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #341: (@23[80] = @14) */
  for (rr=w23+80, cs=(&w14); rr!=w23+81; rr+=1) *rr = *cs++;
  /* #342: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #343: @7 = (@8*@7) */
  for (i=0, rr=w07, cs=w07; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #344: @3 = (-@7) */
  for (i=0, rr=w03, cs=w07; i<3; ++i) *rr++ = (- *cs++ );
  /* #345: @3 = (@3-@7) */
  for (i=0, rr=w03, cs=w07; i<3; ++i) (*rr++) -= (*cs++);
  /* #346: @8 = @3[0] */
  for (rr=(&w08), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #347: (@23[81] = @8) */
  for (rr=w23+81, cs=(&w08); rr!=w23+82; rr+=1) *rr = *cs++;
  /* #348: @8 = @3[1] */
  for (rr=(&w08), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #349: (@23[82] = @8) */
  for (rr=w23+82, cs=(&w08); rr!=w23+83; rr+=1) *rr = *cs++;
  /* #350: @8 = @3[2] */
  for (rr=(&w08), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #351: (@23[83] = @8) */
  for (rr=w23+83, cs=(&w08); rr!=w23+84; rr+=1) *rr = *cs++;
  /* #352: @11 = (@6*@11) */
  w11  = (w06*w11);
  /* #353: @10 = (@11*@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #354: @3 = (-@10) */
  for (i=0, rr=w03, cs=w10; i<3; ++i) *rr++ = (- *cs++ );
  /* #355: @3 = (@3-@10) */
  for (i=0, rr=w03, cs=w10; i<3; ++i) (*rr++) -= (*cs++);
  /* #356: @11 = @3[0] */
  for (rr=(&w11), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #357: (@23[84] = @11) */
  for (rr=w23+84, cs=(&w11); rr!=w23+85; rr+=1) *rr = *cs++;
  /* #358: @11 = @3[1] */
  for (rr=(&w11), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #359: (@23[85] = @11) */
  for (rr=w23+85, cs=(&w11); rr!=w23+86; rr+=1) *rr = *cs++;
  /* #360: @11 = @3[2] */
  for (rr=(&w11), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #361: (@23[86] = @11) */
  for (rr=w23+86, cs=(&w11); rr!=w23+87; rr+=1) *rr = *cs++;
  /* #362: @6 = (@6*@1) */
  w06 *= w01;
  /* #363: @13 = (@6*@13) */
  for (i=0, rr=w13, cs=w13; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #364: @3 = (-@13) */
  for (i=0, rr=w03, cs=w13; i<3; ++i) *rr++ = (- *cs++ );
  /* #365: @3 = (@3-@13) */
  for (i=0, rr=w03, cs=w13; i<3; ++i) (*rr++) -= (*cs++);
  /* #366: @6 = @3[0] */
  for (rr=(&w06), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #367: (@23[87] = @6) */
  for (rr=w23+87, cs=(&w06); rr!=w23+88; rr+=1) *rr = *cs++;
  /* #368: @6 = @3[1] */
  for (rr=(&w06), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #369: (@23[88] = @6) */
  for (rr=w23+88, cs=(&w06); rr!=w23+89; rr+=1) *rr = *cs++;
  /* #370: @6 = @3[2] */
  for (rr=(&w06), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #371: (@23[89] = @6) */
  for (rr=w23+89, cs=(&w06); rr!=w23+90; rr+=1) *rr = *cs++;
  /* #372: output[1][0] = @23 */
  casadi_copy(w23, 90, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    case 2: return casadi_s11;
    case 3: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 308;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 7*sizeof(casadi_int);
  if (sz_w) *sz_w = 308*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
