/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_pointmass_multiple_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[18] = 
  {6, 3, 0, 4, 8, 12, 0, 3,
  4, 5, 1, 3, 4, 5, 2, 3,
  4, 5};
static const casadi_int casadi_s1[21] = 
  {3, 6, 0, 1, 2, 3, 6, 9,
  12, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2};
static const casadi_int casadi_s2[39] = 
  {6, 6, 0, 4, 8, 12, 18, 24,
  30, 0, 3, 4, 5, 1, 3, 4,
  5, 2, 3, 4, 5, 0, 1, 2,
  3, 4, 5, 0, 1, 2, 3, 4,
  5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[6] = {0, 4, 5, 1, 2, 3};
static const casadi_int casadi_s4[6] = {0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[27] = 
  {6, 6, 0, 4, 8, 12, 15, 17,
  18, 0, 1, 2, 3, 1, 2, 3,
  4, 2, 3, 4, 5, 3, 4, 5,
  4, 5, 5};
static const casadi_int casadi_s6[30] = 
  {6, 6, 0, 1, 3, 6, 10, 15,
  21, 0, 0, 1, 0, 1, 2, 0,
  1, 2, 3, 0, 1, 2, 3, 4,
  0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[3] = {24, 1, 1};
static const casadi_int casadi_s8[3] = {9, 1, 1};
static const casadi_int casadi_s9[3] = {0, 1, 1};
static const casadi_int casadi_s10[3] = {0, 0, 1};
static const casadi_int casadi_s11[3] = {33, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -1.9620000000000002e+00};

static const casadi_real casadi_zeros[24] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* planner_payload_pointmass_multiple_impl_dae_fun:(i0[24],i1[24],i2[9],i3[0],i4[],i5[33])->(o0[24]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+6, *w01=w+30, *w02=w+33, *w03=w+36, *w04=w+39, w05, w06, *w07=w+44, w08, *w09=w+48, *w10=w+51;
  casadi_real *w11=w+54, w12, *w13=w+58, *w14=w+61, *w15=w+64, w16, *w17=w+68, *w18=w+74, *w19=w+86, *w20=w+98, *w21=w+104, *w22=w+110;
  casadi_real *w23=w+116, *w24=w+146, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34;
  casadi_real w35, w36, w37, w38, w39, w40, w41, w42, *w43=w+194;
  const casadi_real *cr, *cs, *ss, *wr00;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w01);
  /* #2: @2 = [-0, -0, -1.962] */
  casadi_copy(casadi_c0, 3, w02);
  /* #3: @3 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w03);
  /* #4: @4 = input[2][0] */
  casadi_copy(arg[2], 3, w04);
  /* #5: @5 = dot(@3, @4) */
  w05 = casadi_dot(3, w03, w04);
  /* #6: @6 = 0.77 */
  w06 = 7.7000000000000002e-01;
  /* #7: @7 = input[0][5] */
  casadi_copy(arg[0] ? arg[0]+15 : 0, 3, w07);
  /* #8: @8 = dot(@7, @7) */
  w08 = casadi_dot(3, w07, w07);
  /* #9: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #10: @5 = (@5-@8) */
  w05 -= w08;
  /* #11: @9 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+9 : 0, 3, w09);
  /* #12: @10 = input[2][1] */
  casadi_copy(arg[2] ? arg[2]+3 : 0, 3, w10);
  /* #13: @8 = dot(@9, @10) */
  w08 = casadi_dot(3, w09, w10);
  /* #14: @11 = input[0][6] */
  casadi_copy(arg[0] ? arg[0]+18 : 0, 3, w11);
  /* #15: @12 = dot(@11, @11) */
  w12 = casadi_dot(3, w11, w11);
  /* #16: @12 = (@6*@12) */
  w12  = (w06*w12);
  /* #17: @8 = (@8-@12) */
  w08 -= w12;
  /* #18: @13 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+12 : 0, 3, w13);
  /* #19: @14 = input[2][2] */
  casadi_copy(arg[2] ? arg[2]+6 : 0, 3, w14);
  /* #20: @12 = dot(@13, @14) */
  w12 = casadi_dot(3, w13, w14);
  /* #21: @15 = input[0][7] */
  casadi_copy(arg[0] ? arg[0]+21 : 0, 3, w15);
  /* #22: @16 = dot(@15, @15) */
  w16 = casadi_dot(3, w15, w15);
  /* #23: @6 = (@6*@16) */
  w06 *= w16;
  /* #24: @12 = (@12-@6) */
  w12 -= w06;
  /* #25: @17 = vertcat(@2, @5, @8, @12) */
  rr=w17;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  *rr++ = w05;
  *rr++ = w08;
  *rr++ = w12;
  /* #26: @2 = all_0.2(3x3,3nz) */
  casadi_fill(w02, 3, 2.0000000000000001e-01);
  /* #27: @18 = horzcat(@2, @3, @9, @13) */
  rr=w18;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w09; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #28: @19 = @18' */
  casadi_trans(w18,casadi_s1, w19, casadi_s0, iw);
  /* #29: @2 = @3' */
  casadi_copy(w03, 3, w02);
  /* #30: @5 = 0 */
  w05 = 0.;
  /* #31: @20 = horzcat(@2, @5, @5, @5) */
  rr=w20;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  *rr++ = w05;
  *rr++ = w05;
  *rr++ = w05;
  /* #32: @20 = @20' */
  /* #33: @2 = @9' */
  casadi_copy(w09, 3, w02);
  /* #34: @21 = horzcat(@2, @5, @5, @5) */
  rr=w21;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  *rr++ = w05;
  *rr++ = w05;
  *rr++ = w05;
  /* #35: @21 = @21' */
  /* #36: @2 = @13' */
  casadi_copy(w13, 3, w02);
  /* #37: @22 = horzcat(@2, @5, @5, @5) */
  rr=w22;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  *rr++ = w05;
  *rr++ = w05;
  *rr++ = w05;
  /* #38: @22 = @22' */
  /* #39: @23 = horzcat(@19, @20, @21, @22) */
  rr=w23;
  for (i=0, cs=w19; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<6; ++i) *rr++ = *cs++;
  /* #40: @24 = @23' */
  casadi_trans(w23,casadi_s2, w24, casadi_s2, iw);
  /* #41: @17 = (@24\@17) */
  rr = w17;
  ss = w24;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[18], r[21], beta[6], w[12];
    casadi_qr(casadi_s2, ss, w, casadi_s5, v, casadi_s6, r, beta, casadi_s3, casadi_s4);
    casadi_qr_solve(rr, 1, 0, casadi_s5, v, casadi_s6, r, beta, casadi_s3, casadi_s4, w);
  }
  /* #42: @2 = @17[:3] */
  for (rr=w02, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #43: @5 = @7[1] */
  for (rr=(&w05), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #44: @8 = @3[2] */
  for (rr=(&w08), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #45: @12 = (@5*@8) */
  w12  = (w05*w08);
  /* #46: @6 = @7[2] */
  for (rr=(&w06), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #47: @16 = @3[1] */
  for (rr=(&w16), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #48: @25 = (@6*@16) */
  w25  = (w06*w16);
  /* #49: @12 = (@12-@25) */
  w12 -= w25;
  /* #50: @25 = @3[0] */
  for (rr=(&w25), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #51: @6 = (@6*@25) */
  w06 *= w25;
  /* #52: @26 = @7[0] */
  for (rr=(&w26), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #53: @27 = (@26*@8) */
  w27  = (w26*w08);
  /* #54: @6 = (@6-@27) */
  w06 -= w27;
  /* #55: @26 = (@26*@16) */
  w26 *= w16;
  /* #56: @5 = (@5*@25) */
  w05 *= w25;
  /* #57: @26 = (@26-@5) */
  w26 -= w05;
  /* #58: @5 = @11[1] */
  for (rr=(&w05), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #59: @27 = @9[2] */
  for (rr=(&w27), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #60: @28 = (@5*@27) */
  w28  = (w05*w27);
  /* #61: @29 = @11[2] */
  for (rr=(&w29), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #62: @30 = @9[1] */
  for (rr=(&w30), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #63: @31 = (@29*@30) */
  w31  = (w29*w30);
  /* #64: @28 = (@28-@31) */
  w28 -= w31;
  /* #65: @31 = @9[0] */
  for (rr=(&w31), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #66: @29 = (@29*@31) */
  w29 *= w31;
  /* #67: @32 = @11[0] */
  for (rr=(&w32), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #68: @33 = (@32*@27) */
  w33  = (w32*w27);
  /* #69: @29 = (@29-@33) */
  w29 -= w33;
  /* #70: @32 = (@32*@30) */
  w32 *= w30;
  /* #71: @5 = (@5*@31) */
  w05 *= w31;
  /* #72: @32 = (@32-@5) */
  w32 -= w05;
  /* #73: @5 = @15[1] */
  for (rr=(&w05), cs=w15+1; cs!=w15+2; cs+=1) *rr++ = *cs;
  /* #74: @33 = @13[2] */
  for (rr=(&w33), cs=w13+2; cs!=w13+3; cs+=1) *rr++ = *cs;
  /* #75: @34 = (@5*@33) */
  w34  = (w05*w33);
  /* #76: @35 = @15[2] */
  for (rr=(&w35), cs=w15+2; cs!=w15+3; cs+=1) *rr++ = *cs;
  /* #77: @36 = @13[1] */
  for (rr=(&w36), cs=w13+1; cs!=w13+2; cs+=1) *rr++ = *cs;
  /* #78: @37 = (@35*@36) */
  w37  = (w35*w36);
  /* #79: @34 = (@34-@37) */
  w34 -= w37;
  /* #80: @37 = @13[0] */
  for (rr=(&w37), cs=w13+0; cs!=w13+1; cs+=1) *rr++ = *cs;
  /* #81: @35 = (@35*@37) */
  w35 *= w37;
  /* #82: @38 = @15[0] */
  for (rr=(&w38), cs=w15+0; cs!=w15+1; cs+=1) *rr++ = *cs;
  /* #83: @39 = (@38*@33) */
  w39  = (w38*w33);
  /* #84: @35 = (@35-@39) */
  w35 -= w39;
  /* #85: @38 = (@38*@36) */
  w38 *= w36;
  /* #86: @5 = (@5*@37) */
  w05 *= w37;
  /* #87: @38 = (@38-@5) */
  w38 -= w05;
  /* #88: @5 = 1.2987 */
  w05 = 1.2987012987012987e+00;
  /* #89: @4 = (@2-@4) */
  for (i=0, rr=w04, cr=w02, cs=w04; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #90: @39 = @4[2] */
  for (rr=(&w39), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #91: @40 = (@16*@39) */
  w40  = (w16*w39);
  /* #92: @41 = @4[1] */
  for (rr=(&w41), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #93: @42 = (@8*@41) */
  w42  = (w08*w41);
  /* #94: @40 = (@40-@42) */
  w40 -= w42;
  /* #95: @42 = @4[0] */
  for (rr=(&w42), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #96: @8 = (@8*@42) */
  w08 *= w42;
  /* #97: @39 = (@25*@39) */
  w39  = (w25*w39);
  /* #98: @8 = (@8-@39) */
  w08 -= w39;
  /* #99: @25 = (@25*@41) */
  w25 *= w41;
  /* #100: @16 = (@16*@42) */
  w16 *= w42;
  /* #101: @25 = (@25-@16) */
  w25 -= w16;
  /* #102: @4 = vertcat(@40, @8, @25) */
  rr=w04;
  *rr++ = w40;
  *rr++ = w08;
  *rr++ = w25;
  /* #103: @4 = (@5*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #104: @10 = (@2-@10) */
  for (i=0, rr=w10, cr=w02, cs=w10; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #105: @40 = @10[2] */
  for (rr=(&w40), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #106: @8 = (@30*@40) */
  w08  = (w30*w40);
  /* #107: @25 = @10[1] */
  for (rr=(&w25), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #108: @16 = (@27*@25) */
  w16  = (w27*w25);
  /* #109: @8 = (@8-@16) */
  w08 -= w16;
  /* #110: @16 = @10[0] */
  for (rr=(&w16), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #111: @27 = (@27*@16) */
  w27 *= w16;
  /* #112: @40 = (@31*@40) */
  w40  = (w31*w40);
  /* #113: @27 = (@27-@40) */
  w27 -= w40;
  /* #114: @31 = (@31*@25) */
  w31 *= w25;
  /* #115: @30 = (@30*@16) */
  w30 *= w16;
  /* #116: @31 = (@31-@30) */
  w31 -= w30;
  /* #117: @10 = vertcat(@8, @27, @31) */
  rr=w10;
  *rr++ = w08;
  *rr++ = w27;
  *rr++ = w31;
  /* #118: @10 = (@5*@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #119: @14 = (@2-@14) */
  for (i=0, rr=w14, cr=w02, cs=w14; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #120: @8 = @14[2] */
  for (rr=(&w08), cs=w14+2; cs!=w14+3; cs+=1) *rr++ = *cs;
  /* #121: @27 = (@36*@8) */
  w27  = (w36*w08);
  /* #122: @31 = @14[1] */
  for (rr=(&w31), cs=w14+1; cs!=w14+2; cs+=1) *rr++ = *cs;
  /* #123: @30 = (@33*@31) */
  w30  = (w33*w31);
  /* #124: @27 = (@27-@30) */
  w27 -= w30;
  /* #125: @30 = @14[0] */
  for (rr=(&w30), cs=w14+0; cs!=w14+1; cs+=1) *rr++ = *cs;
  /* #126: @33 = (@33*@30) */
  w33 *= w30;
  /* #127: @8 = (@37*@8) */
  w08  = (w37*w08);
  /* #128: @33 = (@33-@8) */
  w33 -= w08;
  /* #129: @37 = (@37*@31) */
  w37 *= w31;
  /* #130: @36 = (@36*@30) */
  w36 *= w30;
  /* #131: @37 = (@37-@36) */
  w37 -= w36;
  /* #132: @14 = vertcat(@27, @33, @37) */
  rr=w14;
  *rr++ = w27;
  *rr++ = w33;
  *rr++ = w37;
  /* #133: @14 = (@5*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #134: @43 = vertcat(@1, @2, @12, @6, @26, @28, @29, @32, @34, @35, @38, @4, @10, @14) */
  rr=w43;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  *rr++ = w12;
  *rr++ = w06;
  *rr++ = w26;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w32;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w38;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #135: @0 = (@0-@43) */
  for (i=0, rr=w00, cr=wr00, cs=w43; i<24; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #136: output[0][0] = @0 */
  casadi_copy(w00, 24, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_pointmass_multiple_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_pointmass_multiple_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_pointmass_multiple_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_pointmass_multiple_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    case 3: return casadi_s9;
    case 4: return casadi_s10;
    case 5: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_pointmass_multiple_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 218;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_pointmass_multiple_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 7*sizeof(casadi_int);
  if (sz_w) *sz_w = 218*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
